#!/bin/sh

SYM_PLACE=sym/x86

xc =p =a def/POSIX/posix.prj -sym_place:=$SYM_PLACE -decor=rt
xc =p X11.prj                -sym_place:=$SYM_PLACE -decor=rt
xc =p Xm.prj                 -sym_place:=$SYM_PLACE -decor=rt
xc =p XmP.prj                -sym_place:=$SYM_PLACE -decor=rt
