/* XDS v2.60: Copyright (c) 1999-2011 Excelsior, LLC. All Rights Reserved. */
/* "@(#)ChanConsts.c Feb  3 14:30:28 2012" */
/* Generated by XDS Modula-2 to ANSI C v4.20 translator */

#define X2C_int32
#define X2C_index32
#ifndef ChanConsts_H_
#include "ChanConsts.h"
#endif
#define ChanConsts_C_

X2C_CARD8 ChanConsts_read = 0x1U;
X2C_CARD8 ChanConsts_write = 0x2U;
X2C_CARD8 ChanConsts_old = 0x4U;
X2C_CARD8 ChanConsts_text = 0x8U;
X2C_CARD8 ChanConsts_raw = 0x10U;
X2C_CARD8 ChanConsts_interactive = 0x20U;
X2C_CARD8 ChanConsts_echo = 0x40U;

extern void ChanConsts_BEGIN(void)
{
   static int ChanConsts_init = 0;
   if (ChanConsts_init) return;
   ChanConsts_init = 1;
   if (sizeof(X2C_CARD8)!=1) X2C_ASSERT(0);
}

