/* XDS v2.60: Copyright (c) 1999-2011 Excelsior, LLC. All Rights Reserved. */
/* "@(#)ConvTypes.c Feb  3 14:30:28 2012" */
/* Generated by XDS Modula-2 to ANSI C v4.20 translator */

#define X2C_int32
#define X2C_index32
#ifndef ConvTypes_H_
#include "ConvTypes.h"
#endif
#define ConvTypes_C_


extern void ConvTypes_BEGIN(void)
{
   static int ConvTypes_init = 0;
   if (ConvTypes_init) return;
   ConvTypes_init = 1;
}

