/* XDS v2.60: Copyright (c) 1999-2011 Excelsior, LLC. All Rights Reserved. */
/* "@(#)COROUTINES.c Feb  3 14:30:28 2012" */
/* Generated by XDS Modula-2 to ANSI C v4.20 translator */

#define X2C_int32
#define X2C_index32
#ifndef COROUTINES_H_
#include "COROUTINES.h"
#endif
#define COROUTINES_C_
#ifndef xmRTS_H_
#include "xmRTS.h"
#endif
#ifndef M2EXCEPTION_H_
#include "M2EXCEPTION.h"
#endif

static X2C_Coroutine handlers[256];


extern void COROUTINES_NEWCOROUTINE(X2C_PROC procBody, X2C_ADDRESS workspace,
                 X2C_CARD32 size, COROUTINES_COROUTINE * cr,
                X2C_PROTECTION initProtection)
{
   X2C_NEWPROCESS(procBody, workspace, size, initProtection,
                (X2C_Coroutine *)cr);
} /* end NEWCOROUTINE() */


extern void COROUTINES_TRANSFER(COROUTINES_COROUTINE * from,
                COROUTINES_COROUTINE to)
{
   X2C_TRANSFER((X2C_Coroutine *)from, (X2C_Coroutine)to);
} /* end TRANSFER() */


extern void COROUTINES_IOTRANSFER(COROUTINES_COROUTINE * from,
                COROUTINES_COROUTINE to)
{
   X2C_IOTRANSFER((X2C_Coroutine *)from, (X2C_Coroutine)to);
} /* end IOTRANSFER() */


extern void COROUTINES_ATTACH(X2C_CARD8 source)
{
   handlers[source] = X2C_GetCurrent();
   handlers[source]->int_no = (X2C_INT16)(X2C_CARD32)source;
} /* end ATTACH() */


extern void COROUTINES_DETACH(X2C_CARD8 source)
{
   X2C_Coroutine current;
   current = X2C_GetCurrent();
   if ((X2C_CARD32)(X2C_INT32)current->int_no!=(X2C_CARD32)
                source || handlers[source]!=current) X2C_TRAP_F(13L);
   current->int_no = -1;
   handlers[source] = 0;
} /* end DETACH() */


extern X2C_BOOLEAN COROUTINES_IsATTACHED(X2C_CARD8 source)
{
   return handlers[source]!=0;
} /* end IsATTACHED() */


extern COROUTINES_COROUTINE COROUTINES_HANDLER(X2C_CARD8 source)
{
   return (COROUTINES_COROUTINE)handlers[source];
} /* end HANDLER() */


extern COROUTINES_COROUTINE COROUTINES_CURRENT(void)
{
   return (COROUTINES_COROUTINE)X2C_GetCurrent();
} /* end CURRENT() */


extern void COROUTINES_LISTEN(X2C_PROTECTION p)
{
   X2C_PROTECTION o;
   X2C_PROTECT(&o, p);
} /* end LISTEN() */


extern X2C_PROTECTION COROUTINES_PROT(void)
{
   X2C_Coroutine current;
   current = X2C_GetCurrent();
   return current->prot;
} /* end PROT() */

static X2C_CARD8 i;


extern void COROUTINES_BEGIN(void)
{
   static int COROUTINES_init = 0;
   if (COROUTINES_init) return;
   COROUTINES_init = 1;
   M2EXCEPTION_BEGIN();
   for (i = COROUTINES_i0;; i++) {
      handlers[i] = 0;
      if (i==COROUTINES_i255) break;
   } /* end for */
}

