/* XDS v2.60: Copyright (c) 1999-2011 Excelsior, LLC. All Rights Reserved. */
/* "@(#)FIO.c Feb  3 14:31:08 2012" */
/* Generated by XDS Modula-2 to ANSI C v4.20 translator */

#define X2C_int32
#define X2C_index32
#ifndef FIO_H_
#include "FIO.h"
#endif
#define FIO_C_
#ifndef IOChan_H_
#include "IOChan.h"
#endif
#ifndef FileSys_H_
#include "FileSys.h"
#endif
#ifndef SysClock_H_
#include "SysClock.h"
#endif
#ifndef Str_H_
#include "Str.h"
#endif
#ifndef ChanConsts_H_
#include "ChanConsts.h"
#endif
#ifndef IOConsts_H_
#include "IOConsts.h"
#endif
#ifndef Strings_H_
#include "Strings.h"
#endif
#ifndef EXCEPTIONS_H_
#include "EXCEPTIONS.h"
#endif
#ifndef xFilePos_H_
#include "xFilePos.h"
#endif
#ifndef RndFile_H_
#include "RndFile.h"
#endif
#ifndef StdChans_H_
#include "StdChans.h"
#endif
#ifndef SeqFile_H_
#include "SeqFile.h"
#endif
#ifndef SysErr_H_
#include "SysErr.h"
#endif
#ifndef XIOChan_H_
#include "XIOChan.h"
#endif
#ifndef xtsFIO_H_
#include "xtsFIO.h"
#endif

IOChan_ChanId FIO_StandardInput;
IOChan_ChanId FIO_StandardOutput;
IOChan_ChanId FIO_ErrorOutput;
IOChan_ChanId FIO_AuxDevice;
X2C_BOOLEAN FIO_IOcheck;
X2C_BOOLEAN FIO_EOF;
X2C_BOOLEAN FIO_OK;
Str_CHARSET FIO_Separators;
X2C_BOOLEAN FIO_ChopOff;
X2C_BOOLEAN FIO_Eng;
X2C_CHAR FIO_PrefixChar;
X2C_CHAR FIO_SuffixChar;
X2C_CARD8 FIO_ShareMode0;


#define FIO_FirstYear 1970

#define FIO_dirSep "/"

#define FIO_FalseStr "FALSE"

#define FIO_TrueStr "TRUE"

#define FIO_MaxWrLength 256

typedef X2C_CHAR StrM[256];

typedef X2C_CHAR iStr[80];

static EXCEPTIONS_ExceptionSource source;

static iStr exTx;

static Str_CHARSET FIO_LineBreaks = {0x00002400UL,0x00000000UL,0x00000000UL,
                0x00000000UL,0x00000000UL,0x00000000UL,0x00000000UL,
                0x00000000UL};


static void RAISE(X2C_CARD32 n, const X2C_CHAR s[], X2C_CARD32 s_len)
{
   iStr m;
   Str_Concat(m, 80ul, "FIO.", 5ul, s, s_len);
   EXCEPTIONS_RAISE(source, n, m, 80ul);
} /* end RAISE() */


extern X2C_BOOLEAN FIO_IsFIOException(void)
{
   return EXCEPTIONS_IsCurrentSource(source);
} /* end IsFIOException() */

static X2C_CARD32 IOR;


extern X2C_CARD32 FIO_IOresult(void)
{
   return IOR;
} /* end IOresult() */


static void setIOR(X2C_CARD32 rc)
{
   IOR = rc;
} /* end setIOR() */


extern X2C_BOOLEAN FIO_ThreadOK(void)
{
   return FIO_OK;
} /* end ThreadOK() */


static void setOK(X2C_BOOLEAN b)
{
   FIO_OK = b;
} /* end setOK() */


extern X2C_BOOLEAN FIO_ThreadEOF(void)
{
   return FIO_EOF;
} /* end ThreadEOF() */


static void setEOF(X2C_BOOLEAN b)
{
   FIO_EOF = b;
} /* end setEOF() */

static X2C_CARD8 cres;


static X2C_CARD32 RecdOpRes(X2C_CARD8 cres0)
{
   switch ((unsigned)cres0) {
   case ChanConsts_opened:
      return SysErr_allRight;
   case ChanConsts_tooManyOpen:
      return SysErr_tooManyOpen;
   case ChanConsts_noSuchFile:
      return SysErr_fileNotFound;
   case ChanConsts_fileExists:
      return SysErr_fileExists;
   default:;
      return SysErr_otherProblem;
   } /* end switch */
   return 0;
} /* end RecdOpRes() */


static void setShM(X2C_BOOLEAN readonly)
{
   switch ((unsigned)FIO_ShareMode0) {
   case FIO_ShareCompat:
      if (readonly) xtsFIO_setShM(0, 1);
      else xtsFIO_setShM(1, 1);
      break;
   case FIO_ShareDenyRW:
      xtsFIO_setShM(1, 1);
      break;
   case FIO_ShareDenyRD:
      xtsFIO_setShM(1, 0);
      break;
   case FIO_ShareDenyWR:
      xtsFIO_setShM(0, 1);
      break;
   case FIO_ShareDenyNone:
      xtsFIO_setShM(0, 0);
      break;
   default:
      X2C_TRAP(X2C_CASE_TRAP);
   } /* end switch */
} /* end setShM() */


static void restoreShM(void)
{
   xtsFIO_restoreShM();
} /* end restoreShM() */


extern IOChan_ChanId FIO_Open(X2C_CHAR Name[], X2C_CARD32 Name_len)
{
   IOChan_ChanId f;
   struct X2C_XHandler_STR anonym;
   IOChan_ChanId FIO_Open_ret;
   if (X2C_XTRY(&anonym)) {
      setShM(0);
      RndFile_OpenOld(&f, Name, Name_len, 0x13U, &cres);
      restoreShM();
      setIOR(RecdOpRes(cres));
      if (cres && FIO_IOcheck) {
         Str_Concat(exTx, 80ul, "Open: cannot open file ", 24ul, Name,
                Name_len);
         RAISE(FIO_IOresult(), exTx, 80ul);
      }
      FIO_Open_ret = f;
      X2C_XOFF();
   }
   else {
      xtsFIO_restoreShM();
      setIOR(SysErr_otherProblem);
      if (!FIO_IOcheck) {
         FIO_Open_ret = f;
         goto label;
      }
      X2C_XON();
      label:;
   }
   X2C_XREMOVE();
   return FIO_Open_ret;
} /* end Open() */


extern IOChan_ChanId FIO_OpenRead(X2C_CHAR Name[], X2C_CARD32 Name_len)
{
   IOChan_ChanId f;
   struct X2C_XHandler_STR anonym;
   IOChan_ChanId FIO_OpenRead_ret;
   if (X2C_XTRY(&anonym)) {
      setShM(1);
      RndFile_OpenOld(&f, Name, Name_len, 0x11U, &cres);
      restoreShM();
      setIOR(RecdOpRes(cres));
      if (cres && FIO_IOcheck) {
         Str_Concat(exTx, 80ul, "OpenRead: cannot open file ", 28ul, Name,
                Name_len);
         RAISE(FIO_IOresult(), exTx, 80ul);
      }
      FIO_OpenRead_ret = f;
      X2C_XOFF();
   }
   else {
      xtsFIO_restoreShM();
      setIOR(SysErr_otherProblem);
      if (!FIO_IOcheck) {
         FIO_OpenRead_ret = f;
         goto label;
      }
      X2C_XON();
      label:;
   }
   X2C_XREMOVE();
   return FIO_OpenRead_ret;
} /* end OpenRead() */


extern IOChan_ChanId FIO_Create(X2C_CHAR Name[], X2C_CARD32 Name_len)
{
   IOChan_ChanId f;
   struct X2C_XHandler_STR anonym;
   IOChan_ChanId FIO_Create_ret;
   if (X2C_XTRY(&anonym)) {
      setShM(0);
      RndFile_OpenClean(&f, Name, Name_len, 0x17U, &cres);
      restoreShM();
      setIOR(RecdOpRes(cres));
      if (cres && FIO_IOcheck) {
         Str_Concat(exTx, 80ul, "Create: cannot open file ", 26ul, Name,
                Name_len);
         RAISE(FIO_IOresult(), exTx, 80ul);
      }
      FIO_Create_ret = f;
      X2C_XOFF();
   }
   else {
      xtsFIO_restoreShM();
      setIOR(SysErr_otherProblem);
      if (!FIO_IOcheck) {
         FIO_Create_ret = f;
         goto label;
      }
      X2C_XON();
      label:;
   }
   X2C_XREMOVE();
   return FIO_Create_ret;
} /* end Create() */


extern IOChan_ChanId FIO_Append(X2C_CHAR Name[], X2C_CARD32 Name_len)
{
   IOChan_ChanId f;
   struct X2C_XHandler_STR anonym;
   RndFile_FilePos tmp;
   IOChan_ChanId FIO_Append_ret;
   if (X2C_XTRY(&anonym)) {
      setShM(0);
      RndFile_OpenOld(&f, Name, Name_len, 0x13U, &cres);
      restoreShM();
      setIOR(RecdOpRes(cres));
      if (cres==ChanConsts_opened) RndFile_SetPos(f, RndFile_EndPos(tmp, f));
      else if (FIO_IOcheck) {
         Str_Concat(exTx, 80ul, "Append: cannot open file ", 26ul, Name,
                Name_len);
         RAISE(FIO_IOresult(), exTx, 80ul);
      }
      FIO_Append_ret = f;
      X2C_XOFF();
   }
   else {
      xtsFIO_restoreShM();
      setIOR(SysErr_otherProblem);
      if (!FIO_IOcheck) {
         FIO_Append_ret = f;
         goto label;
      }
      X2C_XON();
      label:;
   }
   X2C_XREMOVE();
   return FIO_Append_ret;
} /* end Append() */


extern void FIO_Close(IOChan_ChanId * F)
{
   struct X2C_XHandler_STR anonym;
   if (X2C_XTRY(&anonym)) {
      setIOR(SysErr_allRight);
      RndFile_Close(F);
      X2C_XOFF();
   }
   else {
      setIOR(SysErr_otherProblem);
      if (!FIO_IOcheck) goto label;
      X2C_XON();
      label:;
   }
   X2C_XREMOVE();
} /* end Close() */

static RndFile_FilePos RndPos;


static X2C_CARD32 Rnd2LC(const RndFile_FilePos rndpos)
{
   X2C_BOOLEAN b;
   X2C_CARD32 c;
   b = xFilePos_PosToCard(&c, rndpos);
   return c;
} /* end Rnd2LC() */


static X2C_LOC * LC2Rnd(RndFile_FilePos LC2Rnd_ret, X2C_CARD32 lcPos)
{
   xFilePos_CardToPos(RndPos, lcPos);
   memcpy(LC2Rnd_ret,RndPos,8u);
   return LC2Rnd_ret;
} /* end LC2Rnd() */

static RndFile_FilePos svpos;


static void Save(const RndFile_FilePos pos)
{
   memcpy(svpos,pos,8u);
} /* end Save() */


static X2C_LOC * GetSaved(RndFile_FilePos GetSaved_ret)
{
   memcpy(GetSaved_ret,svpos,8u);
   return GetSaved_ret;
} /* end GetSaved() */


extern X2C_CARD32 FIO_GetPos(IOChan_ChanId F)
{
   struct X2C_XHandler_STR anonym;
   RndFile_FilePos tmp;
   X2C_CARD32 FIO_GetPos_ret;
   if (X2C_XTRY(&anonym)) {
      setIOR(SysErr_allRight);
      setOK(1);
      FIO_GetPos_ret = Rnd2LC(RndFile_CurrentPos(tmp, F));
      X2C_XOFF();
   }
   else {
      setIOR(SysErr_otherProblem);
      if (!FIO_IOcheck) {
         FIO_GetPos_ret = 0UL;
         goto label;
      }
      X2C_XON();
      label:;
   }
   X2C_XREMOVE();
   return FIO_GetPos_ret;
} /* end GetPos() */


extern void FIO_Seek(IOChan_ChanId F, X2C_CARD32 pos)
{
   struct X2C_XHandler_STR anonym;
   RndFile_FilePos tmp;
   if (X2C_XTRY(&anonym)) {
      setIOR(SysErr_allRight);
      RndFile_SetPos(F, LC2Rnd(tmp, pos));
      X2C_XOFF();
   }
   else {
      setIOR(SysErr_otherProblem);
      if (!FIO_IOcheck) goto label;
      X2C_XON();
      label:;
   }
   X2C_XREMOVE();
} /* end Seek() */


extern X2C_CARD32 FIO_Size(IOChan_ChanId F)
{
   X2C_CARD32 Ret;
   struct X2C_XHandler_STR anonym;
   RndFile_FilePos tmp;
   X2C_CARD32 FIO_Size_ret;
   if (X2C_XTRY(&anonym)) {
      Save(RndFile_CurrentPos(tmp, F));
      Ret = Rnd2LC(RndFile_EndPos(tmp, F));
      RndFile_SetPos(F, GetSaved(tmp));
      FIO_Size_ret = Ret;
      X2C_XOFF();
   }
   else {
      setIOR(SysErr_otherProblem);
      if (!FIO_IOcheck) {
         FIO_Size_ret = 0UL;
         goto label;
      }
      X2C_XON();
      label:;
   }
   X2C_XREMOVE();
   return FIO_Size_ret;
} /* end Size() */


extern void FIO_Truncate(IOChan_ChanId F)
{
   setOK(1);
   XIOChan_Truncate(F);
   if (FIO_IOresult()!=SysErr_allRight && FIO_IOcheck) {
      RAISE(FIO_IOresult(), "Truncate: wrong parameters", 27ul);
   }
} /* end Truncate() */


extern IOChan_ChanId FIO_AppendHandle(X2C_CARD32 fh, X2C_BOOLEAN ReadOnly)
{
   X2C_CARD8 flags;
   IOChan_ChanId cid;
   X2C_CARD8 res;
   struct X2C_XHandler_STR anonym;
   IOChan_ChanId FIO_AppendHandle_ret;
   if (X2C_XTRY(&anonym)) {
      flags = 0x11U;
      if (!ReadOnly) flags = 0x13U;
      xtsFIO_mk_chan(cid, fh, flags, &res);
      setIOR(RecdOpRes(res));
      if (res && FIO_IOcheck) {
         RAISE(FIO_IOresult(), "AppendHandle: cannot make channel", 34ul);
      }
      FIO_AppendHandle_ret = cid;
      X2C_XOFF();
   }
   else {
      setIOR(SysErr_otherProblem);
      if (!FIO_IOcheck) {
         FIO_AppendHandle_ret = StdChans_NullChan();
         goto label;
      }
      X2C_XON();
      label:;
   }
   X2C_XREMOVE();
   return FIO_AppendHandle_ret;
} /* end AppendHandle() */


extern void FIO_Erase(X2C_CHAR fname[], X2C_CARD32 fname_len)
{
   X2C_BOOLEAN done;
   FileSys_Remove(fname, fname_len, &done);
   if (done) setIOR(SysErr_allRight);
   else {
      setIOR(SysErr_otherProblem);
      if (FIO_IOcheck) {
         Str_Concat(exTx, 80ul, "Erase: cannot erase file ", 26ul, fname,
                fname_len);
         RAISE(FIO_IOresult(), exTx, 80ul);
      }
   }
} /* end Erase() */


extern void FIO_Rename(X2C_CHAR fname[], X2C_CARD32 fname_len,
                X2C_CHAR newname[], X2C_CARD32 newname_len)
{
   X2C_BOOLEAN done;
   FileSys_Rename(fname, fname_len, newname, newname_len, &done);
   if (done) setIOR(SysErr_allRight);
   else {
      setIOR(SysErr_otherProblem);
      if (FIO_IOcheck) {
         Str_Concat(exTx, 80ul, "Rename: cannot rename file ", 28ul, fname,
                fname_len);
         RAISE(FIO_IOresult(), exTx, 80ul);
      }
   }
} /* end Rename() */


static X2C_CARD32 PackDOSDateTime(struct SysClock_DateTime dt)
{
   return (dt.year-1970UL)*33554432UL+dt.month*2097152UL+dt.day*65536UL+dt.hour*2048UL+dt.minute*32UL+dt.second/2UL;
                
} /* end PackDOSDateTime() */


static void UnpackDOSDateTime(struct SysClock_DateTime * dt, X2C_CARD32 d)
{
   dt->year = d/33554432UL+1970UL;
   d = d&33554431UL;
   dt->month = d/2097152UL;
   d = d&2097151UL;
   dt->day = d/65536UL;
   d = d&65535UL;
   dt->hour = d/2048UL;
   d = d&2047UL;
   dt->minute = d/32UL;
   dt->second = (d&31UL)*2UL;
   dt->zone = 0L;
   dt->fractions = 0UL;
} /* end UnpackDOSDateTime() */


extern X2C_CARD32 FIO_GetCurrentDate(void)
{
   struct SysClock_DateTime dt;
   setIOR(SysErr_allRight);
   SysClock_GetClock(&dt);
   return PackDOSDateTime(dt);
} /* end GetCurrentDate() */


extern X2C_CARD32 FIO_GetFileDate(IOChan_ChanId f)
{
   struct SysClock_DateTime b;
   if (FIO_GetFileStamp(f, &b)) return PackDOSDateTime(b);
   else return 0UL;
   return 0;
} /* end GetFileDate() */


extern void FIO_SetFileDate(IOChan_ChanId f, X2C_CARD32 d)
{
   struct SysClock_DateTime b;
   UnpackDOSDateTime(&b, d);
   xtsFIO_SetFileDate(f, b);
} /* end SetFileDate() */


extern X2C_BOOLEAN FIO_GetFileStamp(IOChan_ChanId F,
                struct SysClock_DateTime * b)
{
   return xtsFIO_GetFileStamp(F, b);
} /* end GetFileStamp() */


extern void FIO_AssignBuffer(IOChan_ChanId F, X2C_LOC Buf[],
                X2C_CARD32 Buf_len)
{
} /* end AssignBuffer() */


extern void FIO_Flush(IOChan_ChanId F)
{
   IOChan_Flush(F);
} /* end Flush() */


extern X2C_CARD32 FIO_RdBin(IOChan_ChanId F, X2C_LOC Buf[],
                X2C_CARD32 Buf_len, X2C_CARD32 Count)
{
   X2C_CARD32 actRead;
   struct X2C_XHandler_STR anonym;
   X2C_CARD32 FIO_RdBin_ret;
   if (X2C_XTRY(&anonym)) {
      setIOR(SysErr_allRight);
      if (Count>(Buf_len-1)+1UL) Count = (Buf_len-1)+1UL;
      IOChan_RawRead(F, (X2C_ADDRESS)Buf, Count, &actRead);
      setEOF(IOChan_ReadResult(F)==IOConsts_endOfInput);
      FIO_RdBin_ret = actRead;
      X2C_XOFF();
   }
   else {
      setIOR(SysErr_otherProblem);
      setOK(0);
      if (!FIO_IOcheck) {
         FIO_RdBin_ret = 0UL;
         goto label;
      }
      X2C_XON();
      label:;
   }
   X2C_XREMOVE();
   return FIO_RdBin_ret;
} /* end RdBin() */


extern void FIO_WrBin(IOChan_ChanId F, X2C_LOC Buf[], X2C_CARD32 Buf_len,
                X2C_CARD32 Count)
{
   struct X2C_XHandler_STR anonym;
   if (X2C_XTRY(&anonym)) {
      setIOR(SysErr_allRight);
      IOChan_RawWrite(F, (X2C_ADDRESS)Buf, Count);
      X2C_XOFF();
   }
   else {
      setIOR(SysErr_otherProblem);
      setOK(0);
      if (!FIO_IOcheck) goto label;
      X2C_XON();
      label:;
   }
   X2C_XREMOVE();
} /* end WrBin() */


extern X2C_CHAR FIO_RdChar(IOChan_ChanId F)
{
   X2C_CHAR c;
   X2C_CARD32 actRead;
   struct X2C_XHandler_STR anonym;
   X2C_CHAR FIO_RdChar_ret;
   if (X2C_XTRY(&anonym)) {
      setIOR(SysErr_allRight);
      setOK(1);
      IOChan_RawRead(F, (X2C_ADDRESS) &c, 1UL, &actRead);
      setEOF(IOChan_ReadResult(F)==IOConsts_endOfInput);
      FIO_RdChar_ret = c;
      X2C_XOFF();
   }
   else {
      setIOR(SysErr_otherProblem);
      if (!FIO_IOcheck) {
         FIO_RdChar_ret = 0;
         goto label;
      }
      X2C_XON();
      label:;
   }
   X2C_XREMOVE();
   return FIO_RdChar_ret;
} /* end RdChar() */


extern void FIO_RdStr(IOChan_ChanId F, X2C_CHAR Buf[], X2C_CARD32 Buf_len)
{
   X2C_CARD32 h;
   X2C_CARD32 i;
   X2C_CHAR c;
   X2C_CARD32 tmp;
   setOK(1);
   h = Buf_len-1;
   tmp = h;
   i = 0UL;
   if (i<=tmp) for (;; i++) {
      c = FIO_RdChar(F);
      if (FIO_ThreadEOF() || c=='\032') {
         Buf[i] = 0;
         return;
      }
      if (c==0xDU ) {
         Buf[i] = 0;
         c = FIO_RdChar(F);
         return;
      }
      if (c==0xAU ) {
         Buf[i] = 0;
         return;
      }
      Buf[i] = c;
      if (i==tmp) break;
   } /* end for */
} /* end RdStr() */

static Str_CHARSET _cnst = {0x00002400UL,0x00000000UL,0x00000000UL,
                0x00000000UL,0x00000000UL,0x00000000UL,0x00000000UL,
                0x00000000UL};

extern void FIO_RdItem(IOChan_ChanId F, X2C_CHAR S[], X2C_CARD32 S_len)
{
   X2C_CHAR c;
   X2C_CARD32 L;
   X2C_CARD32 i;
   Str_CHARSET tmp;
   i = 0UL;
   for (;;) {
      c = FIO_RdChar(F);
      if (!FIO_ThreadOK() || !X2C_INL((X2C_INT32)(X2C_CARD8)c,256,X2C_OR(tmp,
                FIO_Separators,_cnst,8))) break;
   }
   L = S_len-1;
   for (;;) {
      if (!FIO_ThreadOK() || X2C_INL((X2C_INT32)(X2C_CARD8)c,256,X2C_OR(tmp,
                FIO_Separators,_cnst,8))) break;
      S[i] = c;
      ++i;
      if (i>L) break;
      c = FIO_RdChar(F);
      if (FIO_ThreadEOF()) {
         setOK(1);
         break;
      }
   }
   if (i<=L) S[i] = 0;
} /* end RdItem() */


extern X2C_BOOLEAN FIO_RdBool(IOChan_ChanId F)
{
   StrM s;
   FIO_RdItem(F, s, 256ul);
   return Str_Compare(s, 256ul, "TRUE", 5ul)==0L;
} /* end RdBool() */


extern X2C_INT8 FIO_RdShtInt(IOChan_ChanId F)
{
   StrM S;
   X2C_INT32 i;
   X2C_BOOLEAN b;
   FIO_RdItem(F, S, 256ul);
   i = Str_StrToInt(S, 256ul, 10UL, &b);
   setOK((b && i>=-128L) && i<=127L);
   return (X2C_INT8)i;
} /* end RdShtInt() */


extern X2C_INT32 FIO_RdInt(IOChan_ChanId F)
{
   StrM S;
   X2C_INT32 i;
   X2C_BOOLEAN b;
   FIO_RdItem(F, S, 256ul);
   i = Str_StrToInt(S, 256ul, 10UL, &b);
   setOK((b && i>=X2C_min_longint) && i<=X2C_max_longint);
   return i;
} /* end RdInt() */


extern X2C_INT32 FIO_RdLngInt(IOChan_ChanId F)
{
   StrM S;
   X2C_INT32 i;
   X2C_BOOLEAN b;
   FIO_RdItem(F, S, 256ul);
   i = Str_StrToInt(S, 256ul, 10UL, &b);
   setOK(b);
   return i;
} /* end RdLngInt() */


extern X2C_CARD8 FIO_RdShtCard(IOChan_ChanId F)
{
   StrM S;
   X2C_CARD32 i;
   X2C_BOOLEAN b;
   FIO_RdItem(F, S, 256ul);
   i = Str_StrToCard(S, 256ul, 10UL, &b);
   setOK(b && i<=255UL);
   return (X2C_CARD8)i;
} /* end RdShtCard() */


extern X2C_CARD32 FIO_RdCard(IOChan_ChanId F)
{
   StrM S;
   X2C_CARD32 i;
   X2C_BOOLEAN b;
   FIO_RdItem(F, S, 256ul);
   i = Str_StrToCard(S, 256ul, 10UL, &b);
   setOK(b && i<=X2C_max_longcard);
   return i;
} /* end RdCard() */


extern X2C_CARD32 FIO_RdLngCard(IOChan_ChanId F)
{
   StrM S;
   X2C_CARD32 i;
   X2C_BOOLEAN b;
   FIO_RdItem(F, S, 256ul);
   i = Str_StrToCard(S, 256ul, 10UL, &b);
   setOK(b);
   return i;
} /* end RdLngCard() */


extern X2C_CARD8 FIO_RdShtHex(IOChan_ChanId F)
{
   StrM S;
   X2C_CARD32 i;
   X2C_BOOLEAN b;
   FIO_RdItem(F, S, 256ul);
   i = Str_StrToCard(S, 256ul, 16UL, &b);
   setOK(b && i<=255UL);
   return (X2C_CARD8)i;
} /* end RdShtHex() */


extern X2C_CARD32 FIO_RdHex(IOChan_ChanId F)
{
   StrM S;
   X2C_CARD32 i;
   X2C_BOOLEAN b;
   FIO_RdItem(F, S, 256ul);
   i = Str_StrToCard(S, 256ul, 16UL, &b);
   setOK(b && i<=X2C_max_longcard);
   return i;
} /* end RdHex() */


extern X2C_CARD32 FIO_RdLngHex(IOChan_ChanId F)
{
   StrM S;
   X2C_CARD32 i;
   X2C_BOOLEAN b;
   FIO_RdItem(F, S, 256ul);
   i = Str_StrToCard(S, 256ul, 16UL, &b);
   setOK(b);
   return i;
} /* end RdLngHex() */


extern X2C_REAL FIO_RdReal(IOChan_ChanId F)
{
   StrM S;
   X2C_LONGREAL r;
   X2C_BOOLEAN b;
   FIO_RdItem(F, S, 256ul);
   r = Str_StrToReal(S, 256ul, &b);
   setOK((b && r<=(X2C_LONGREAL)X2C_max_real) && r>=(X2C_LONGREAL)
                X2C_min_real);
   if (FIO_OK) return (X2C_REAL)r;
   else return 0.0f;
   return 0;
} /* end RdReal() */


extern X2C_LONGREAL FIO_RdLngReal(IOChan_ChanId F)
{
   StrM S;
   X2C_LONGREAL r;
   X2C_BOOLEAN b;
   FIO_RdItem(F, S, 256ul);
   r = Str_StrToReal(S, 256ul, &b);
   setOK(b);
   return r;
} /* end RdLngReal() */


extern void FIO_WrChar(IOChan_ChanId F, X2C_CHAR c)
{
   struct X2C_XHandler_STR anonym;
   if (X2C_XTRY(&anonym)) {
      setIOR(SysErr_allRight);
      setOK(1);
      FIO_WrBin(F, (X2C_LOC *) &c, 1u/1u, 1UL);
      X2C_XOFF();
   }
   else {
      setIOR(SysErr_otherProblem);
      if (!FIO_IOcheck) goto label;
      X2C_XON();
      label:;
   }
   X2C_XREMOVE();
} /* end WrChar() */


extern void FIO_WrStr(IOChan_ChanId F, X2C_CHAR Buf[], X2C_CARD32 Buf_len)
{
   struct X2C_XHandler_STR anonym;
   if (X2C_XTRY(&anonym)) {
      setIOR(SysErr_allRight);
      setOK(1);
      FIO_WrBin(F, (X2C_LOC *)Buf, (Buf_len)/1u, Strings_Length(Buf,
                Buf_len));
      X2C_XOFF();
   }
   else {
      setIOR(SysErr_otherProblem);
      if (!FIO_IOcheck) goto label;
      X2C_XON();
      label:;
   }
   X2C_XREMOVE();
} /* end WrStr() */


extern void FIO_WrCharRep(IOChan_ChanId F, X2C_CHAR V, X2C_CARD32 count)
{
   StrM s;
   X2C_CARD32 j;
   X2C_CARD32 i;
   while (count>0UL) {
      i = 254UL;
      if (254UL>count) i = count;
      count -= i;
      j = 0UL;
      while (j<i) {
         s[j] = V;
         ++j;
      }
      s[j] = 0;
      FIO_WrStr(F, s, 256ul);
   }
} /* end WrCharRep() */


extern void FIO_WrStrAdj(IOChan_ChanId F, X2C_CHAR S[], X2C_CARD32 S_len,
                X2C_INT32 Length)
{
   X2C_CARD32 L;
   X2C_INT32 d;
   setOK(1);
   L = (X2C_CARD32)labs(Length);
   d = (X2C_INT32)(L-X2C_LENGTH(S,S_len));
   if (d<0L && FIO_ChopOff) {
      FIO_WrCharRep(F, '?', L);
      setOK(0);
      return;
   }
   if (Length>0L && d>0L) FIO_WrCharRep(F, FIO_PrefixChar, (X2C_CARD32)d);
   FIO_WrStr(F, S, S_len);
   if (Length<0L && d>0L) FIO_WrCharRep(F, FIO_SuffixChar, (X2C_CARD32)d);
} /* end WrStrAdj() */


extern void FIO_WrBool(IOChan_ChanId F, X2C_BOOLEAN V, X2C_INT32 Length)
{
   if (V) FIO_WrStrAdj(F, "TRUE", 5ul, Length);
   else FIO_WrStrAdj(F, "FALSE", 6ul, Length);
} /* end WrBool() */


extern void FIO_WrShtInt(IOChan_ChanId F, X2C_INT8 V, X2C_INT32 Length)
{
   StrM S;
   X2C_BOOLEAN b;
   Str_IntToStr((X2C_INT32)V, S, 256ul, 10UL, &b);
   setOK(b);
   if (b) FIO_WrStrAdj(F, S, 256ul, Length);
} /* end WrShtInt() */


extern void FIO_WrInt(IOChan_ChanId F, X2C_INT32 V, X2C_INT32 Length)
{
   StrM S;
   X2C_BOOLEAN b;
   Str_IntToStr(V, S, 256ul, 10UL, &b);
   setOK(b);
   if (b) FIO_WrStrAdj(F, S, 256ul, Length);
} /* end WrInt() */


extern void FIO_WrLngInt(IOChan_ChanId F, X2C_INT32 V, X2C_INT32 Length)
{
   StrM S;
   X2C_BOOLEAN b;
   Str_IntToStr(V, S, 256ul, 10UL, &b);
   setOK(b);
   if (b) FIO_WrStrAdj(F, S, 256ul, Length);
} /* end WrLngInt() */


extern void FIO_WrShtCard(IOChan_ChanId F, X2C_CARD8 V, X2C_INT32 Length)
{
   StrM S;
   X2C_BOOLEAN b;
   Str_CardToStr((X2C_CARD32)V, S, 256ul, 10UL, &b);
   setOK(b);
   if (b) FIO_WrStrAdj(F, S, 256ul, Length);
} /* end WrShtCard() */


extern void FIO_WrCard(IOChan_ChanId F, X2C_CARD32 V, X2C_INT32 Length)
{
   StrM S;
   X2C_BOOLEAN b;
   Str_CardToStr(V, S, 256ul, 10UL, &b);
   setOK(b);
   if (b) FIO_WrStrAdj(F, S, 256ul, Length);
} /* end WrCard() */


extern void FIO_WrLngCard(IOChan_ChanId F, X2C_CARD32 V, X2C_INT32 Length)
{
   StrM S;
   X2C_BOOLEAN b;
   Str_CardToStr(V, S, 256ul, 10UL, &b);
   setOK(b);
   if (b) FIO_WrStrAdj(F, S, 256ul, Length);
} /* end WrLngCard() */


extern void FIO_WrShtHex(IOChan_ChanId F, X2C_CARD8 V, X2C_INT32 Length)
{
   StrM S;
   X2C_BOOLEAN b;
   Str_CardToStr((X2C_CARD32)V, S, 256ul, 16UL, &b);
   setOK(b);
   if (b) FIO_WrStrAdj(F, S, 256ul, Length);
} /* end WrShtHex() */


extern void FIO_WrHex(IOChan_ChanId F, X2C_CARD32 V, X2C_INT32 Length)
{
   StrM S;
   X2C_BOOLEAN b;
   Str_CardToStr(V, S, 256ul, 16UL, &b);
   setOK(b);
   if (b) FIO_WrStrAdj(F, S, 256ul, Length);
} /* end WrHex() */


extern void FIO_WrLngHex(IOChan_ChanId F, X2C_CARD32 V, X2C_INT32 Length)
{
   StrM S;
   X2C_BOOLEAN b;
   Str_CardToStr(V, S, 256ul, 16UL, &b);
   setOK(b);
   if (b) FIO_WrStrAdj(F, S, 256ul, Length);
} /* end WrLngHex() */


extern void FIO_WrReal(IOChan_ChanId F, X2C_REAL V, X2C_CARD32 Precision,
                X2C_INT32 Length)
{
   StrM S;
   X2C_BOOLEAN b;
   Str_RealToStr((X2C_LONGREAL)V, Precision, FIO_Eng, S, 256ul, &b);
   setOK(b);
   if (b) FIO_WrStrAdj(F, S, 256ul, Length);
} /* end WrReal() */


extern void FIO_WrFixReal(IOChan_ChanId F, X2C_REAL V, X2C_CARD32 Precision,
                X2C_INT32 Length)
{
   StrM S;
   X2C_BOOLEAN b;
   Str_FixRealToStr((X2C_LONGREAL)V, Precision, S, 256ul, &b);
   setOK(b);
   if (b) FIO_WrStrAdj(F, S, 256ul, Length);
} /* end WrFixReal() */


extern void FIO_WrLngReal(IOChan_ChanId F, X2C_LONGREAL V,
                X2C_CARD32 Precision, X2C_INT32 Length)
{
   StrM S;
   X2C_BOOLEAN b;
   Str_RealToStr(V, Precision, FIO_Eng, S, 256ul, &b);
   setOK(b);
   if (b) FIO_WrStrAdj(F, S, 256ul, Length);
} /* end WrLngReal() */


extern void FIO_WrFixLngReal(IOChan_ChanId F, X2C_LONGREAL V,
                X2C_CARD32 Precision, X2C_INT32 Length)
{
   StrM S;
   X2C_BOOLEAN b;
   Str_FixRealToStr(V, Precision, S, 256ul, &b);
   setOK(b);
   if (b) FIO_WrStrAdj(F, S, 256ul, Length);
} /* end WrFixLngReal() */

typedef X2C_CHAR dmt[2];

static dmt _cnst0 = {'\015','\012'};

extern void FIO_WrLn(IOChan_ChanId F)
{
   FIO_WrBin(F, (X2C_LOC *)_cnst0, 2u/1u, 2UL);
} /* end WrLn() */


extern void FIO_ChDir(X2C_CHAR Name[], X2C_CARD32 Name_len)
{
   X2C_CARD32 rc;
   xtsFIO_ChgDir(Name, Name_len, &rc);
   setIOR(rc);
   if (FIO_IOcheck && rc!=SysErr_allRight) {
      Str_Concat(exTx, 80ul, "ChDir: wrong path ", 19ul, Name, Name_len);
      RAISE(rc, exTx, 80ul);
   }
} /* end ChDir() */


extern void FIO_MkDir(X2C_CHAR Name[], X2C_CARD32 Name_len)
{
   X2C_CARD32 rc;
   xtsFIO_CreateDir(Name, Name_len, &rc);
   setIOR(rc);
   if (FIO_IOcheck && rc!=SysErr_allRight) {
      Str_Concat(exTx, 80ul, "MkDir: wrong path ", 19ul, Name, Name_len);
      RAISE(rc, exTx, 80ul);
   }
} /* end MkDir() */


extern void FIO_RmDir(X2C_CHAR Name[], X2C_CARD32 Name_len)
{
   X2C_CARD32 rc;
   xtsFIO_RmvDir(Name, Name_len, &rc);
   setIOR(rc);
   if (FIO_IOcheck && rc!=SysErr_allRight) {
      Str_Concat(exTx, 80ul, "RmDir: wrong path ", 19ul, Name, Name_len);
      RAISE(rc, exTx, 80ul);
   }
} /* end RmDir() */


extern void FIO_GetDir(X2C_CARD8 Drive, X2C_CHAR Name[],
                X2C_CARD32 Name_len)
{
   X2C_CARD32 rc;
   Name[0UL] = '/';
   xtsFIO_GetDir((X2C_CARD32)Drive, Name, Name_len, &rc);
   setIOR(rc);
   if (FIO_IOcheck && rc!=SysErr_allRight) {
      RAISE(rc, "GetDir: invalid argument", 25ul);
   }
} /* end GetDir() */


extern X2C_CARD8 FIO_GetDrive(void)
{
   setIOR(SysErr_allRight);
   return (X2C_CARD8)xtsFIO_GetDrive();
} /* end GetDrive() */


extern void FIO_SetDrive(X2C_CARD8 Drive)
{
   X2C_CARD32 rc;
   xtsFIO_SetDrive((X2C_CARD32)Drive, &rc);
   setIOR(rc);
   if (FIO_IOcheck && rc!=SysErr_allRight) {
      RAISE(rc, "SetDrive: invalid argument", 27ul);
   }
} /* end SetDrive() */


extern X2C_BOOLEAN FIO_ReadFirstEntry(X2C_CHAR DirName[],
                X2C_CARD32 DirName_len, X2C_CARD8 attr,
                struct FIO_DirEntry * D)
{
   X2C_CARD32 rc;
   xtsFIO_ScanFirst(DirName, DirName_len, attr, D, &rc);
   setIOR(rc);
   if ((FIO_IOcheck && rc!=SysErr_allRight) && rc!=SysErr_noMoreFiles) {
      RAISE(rc, "ReadFirstEntry: invalid argument", 33ul);
   }
   return rc==SysErr_allRight;
} /* end ReadFirstEntry() */


extern X2C_BOOLEAN FIO_ReadNextEntry(struct FIO_DirEntry * D)
{
   X2C_CARD32 rc;
   xtsFIO_ScanNext(D, &rc);
   setIOR(rc);
   if ((FIO_IOcheck && rc!=SysErr_allRight) && rc!=SysErr_noMoreFiles) {
      RAISE(rc, "ReadNextEntry: invalid argument", 32ul);
   }
   return rc==SysErr_allRight;
} /* end ReadNextEntry() */


extern void FIO_ReadClose(struct FIO_DirEntry * D)
{
   setIOR(SysErr_allRight);
   xtsFIO_ScanClose(D);
} /* end ReadClose() */

static Str_CHARSET _cnst1 = {0x04002600UL,0x00000001UL,0x00000000UL,
                0x00000000UL,0x00000000UL,0x00000000UL,0x00000000UL,
                0x00000000UL};

extern void FIO_BEGIN(void)
{
   static int FIO_init = 0;
   if (FIO_init) return;
   FIO_init = 1;
   if (sizeof(X2C_CARD8)!=1) X2C_ASSERT(0);
   if (sizeof(FIO_FileName)!=256) X2C_ASSERT(0);
   if (sizeof(StrM)!=256) X2C_ASSERT(0);
   if (sizeof(iStr)!=80) X2C_ASSERT(0);
   xtsFIO_BEGIN();
   XIOChan_BEGIN();
   SysErr_BEGIN();
   IOConsts_BEGIN();
   ChanConsts_BEGIN();
   SeqFile_BEGIN();
   StdChans_BEGIN();
   RndFile_BEGIN();
   xFilePos_BEGIN();
   EXCEPTIONS_BEGIN();
   Str_BEGIN();
   FileSys_BEGIN();
   IOChan_BEGIN();
   SysClock_BEGIN();
   EXCEPTIONS_AllocateSource(&source);
   setIOR(SysErr_allRight);
   setOK(1);
   setEOF(0);
   FIO_Eng = 0;
   FIO_IOcheck = 1;
   FIO_ChopOff = 0;
   FIO_PrefixChar = ' ';
   FIO_SuffixChar = ' ';
   FIO_ShareMode0 = FIO_ShareCompat;
   memcpy(FIO_Separators,_cnst1,32u);
   FIO_StandardInput = StdChans_StdInChan();
   FIO_StandardOutput = StdChans_StdOutChan();
   FIO_ErrorOutput = StdChans_StdErrChan();
   FIO_AuxDevice = StdChans_NullChan();
}

