/* XDS v2.60: Copyright (c) 1999-2011 Excelsior, LLC. All Rights Reserved. */
/* "@(#)IOConsts.c Feb  3 14:30:28 2012" */
/* Generated by XDS Modula-2 to ANSI C v4.20 translator */

#define X2C_int32
#define X2C_index32
#ifndef IOConsts_H_
#include "IOConsts.h"
#endif
#define IOConsts_C_


extern void IOConsts_BEGIN(void)
{
   static int IOConsts_init = 0;
   if (IOConsts_init) return;
   IOConsts_init = 1;
}

