/* XDS v2.60: Copyright (c) 1999-2011 Excelsior, LLC. All Rights Reserved. */
/* "@(#)oberonRTS.c Feb  3 14:30:28 2012" */
/* Generated by XDS Modula-2 to ANSI C v4.20 translator */

#define X2C_int32
#define X2C_index32
#ifndef oberonRTS_H_
#include "oberonRTS.h"
#endif
#define oberonRTS_C_
#include "X2C.h"
#ifndef xmRTS_H_
#include "xmRTS.h"
#endif
#ifndef xrMM_H_
#include "xrMM.h"
#endif
#ifndef xrO2MM_H_
#include "xrO2MM.h"
#endif
#ifndef xrBlockManager_H_
#include "xrBlockManager.h"
#endif

oberonRTS_Module oberonRTS_nullModule;
oberonRTS_Type oberonRTS_nullType;
typedef X2C_CHAR * Name;

typedef X2C_PROC * CMDs;

typedef X2C_ADDRESS * CNMs;


extern void oberonRTS_SetHeaplimit(X2C_CARD32 newHeaplimit)
{
   if (newHeaplimit>1073741824UL) X2C_maxmem = 1073741824UL;
   else X2C_maxmem = newHeaplimit;
   xrMM_FloatingHeaplimit = X2C_maxmem==0UL;
} /* end SetHeaplimit() */


extern void oberonRTS_Collect(void)
{
   X2C_COLLECT();
} /* end Collect() */


extern void oberonRTS_CompactHeap(void)
{
   xrMM_DoDefrag = 1;
   X2C_COLLECT();
   xrMM_DoDefrag = 0;
} /* end CompactHeap() */


extern void oberonRTS_GetInfo(X2C_CARD32 * objects, X2C_CARD32 * busymem)
{
   *objects = X2C_objects;
   *busymem = X2C_busymem;
} /* end GetInfo() */


extern void oberonRTS_gcAnchorTrace(X2C_BOOLEAN on,
                X2C_CARD32 weightThreshold)
{
   xrMM_anchorTracing = on;
   xrMM_anchorWeightThreshold = weightThreshold;
} /* end gcAnchorTrace() */


extern void oberonRTS_gcHeapTrace(X2C_BOOLEAN on,
                X2C_CARD32 heapTracingThreshold)
{
   xrMM_heapTracing = on;
   xrMM_heapTracingThreshold = heapTracingThreshold;
} /* end gcHeapTrace() */


extern void oberonRTS_ReduceGCConservatism(X2C_ADDRESS obj)
{
   xrMM_stampAsNonConservative(obj);
} /* end ReduceGCConservatism() */


extern void oberonRTS_InstallFinalizer(oberonRTS_Finalizer f,
                X2C_ADDRESS obj)
{
   X2C_DESTRUCTOR(obj, (X2C_DPROC)f);
} /* end InstallFinalizer() */


extern oberonRTS_Module oberonRTS_Search(X2C_CHAR name[],
                X2C_CARD32 name_len)
{
   X2C_MD m;
   Name pname;
   m = X2C_MODULES;
   while (m) {
      pname = (Name)m->name;
      if (X2C_STRCMP(name,name_len,pname,128u)==0) {
         return (oberonRTS_Module)m;
      }
      m = m->next;
   }
   return 0;
} /* end Search() */


extern void oberonRTS_NameOfModule(oberonRTS_Module m, X2C_CHAR name[],
                X2C_CARD32 name_len)
{
   Name pname;
   pname = (Name)((X2C_MD)m)->name;
   X2C_COPY(pname,128u,name,name_len);
} /* end NameOfModule() */


extern X2C_PROC oberonRTS_ThisCommand(oberonRTS_Module m, X2C_CHAR name[],
                X2C_CARD32 name_len)
{
   CMDs cmds;
   CNMs cnms;
   X2C_CARD32 i;
   Name pname;
   cmds = (CMDs)((X2C_MD)m)->cmds;
   cnms = (CNMs)((X2C_MD)m)->cnms;
   i = 0UL;
   for (;;) {
      pname = (Name)cnms[i];
      if (pname==0) return 0;
      if (X2C_STRCMP(pname,128u,name,name_len)==0) return cmds[i];
      ++i;
   }
   return 0;
} /* end ThisCommand() */


extern oberonRTS_Type oberonRTS_ThisType(oberonRTS_Module m, X2C_CHAR name[],
                 X2C_CARD32 name_len)
{
   Name pname;
   X2C_TD type;
   type = ((X2C_MD)m)->types;
   while (type) {
      pname = (Name)type->name;
      if (X2C_STRCMP(pname,128u,name,name_len)==0) {
         return (oberonRTS_Type)type;
      }
      type = type->next;
   }
   return 0;
} /* end ThisType() */


extern X2C_INT32 oberonRTS_SizeOf(oberonRTS_Type t)
{
   return (X2C_INT32)((X2C_TD)t)->size;
} /* end SizeOf() */


extern oberonRTS_Type oberonRTS_BaseOf(oberonRTS_Type t, X2C_INT32 level)
{
   return (oberonRTS_Type)((X2C_TD)t)->base[level];
} /* end BaseOf() */


extern X2C_INT32 oberonRTS_LevelOf(oberonRTS_Type t)
{
   return (X2C_INT32)((X2C_TD)t)->level;
} /* end LevelOf() */


extern oberonRTS_Module oberonRTS_ModuleOf(oberonRTS_Type t)
{
   return (oberonRTS_Module)((X2C_TD)t)->module;
} /* end ModuleOf() */


extern void oberonRTS_NameOfType(oberonRTS_Type t, X2C_CHAR name[],
                X2C_CARD32 name_len)
{
   Name pname;
   pname = (Name)((X2C_TD)t)->name;
   X2C_COPY(pname,128u,name,name_len);
} /* end NameOfType() */


extern oberonRTS_Type oberonRTS_TypeOf(X2C_ADDRESS obj)
{
   if (obj==0) return 0;
   return (oberonRTS_Type)X2C_GET_TD(obj);
} /* end TypeOf() */


extern X2C_ADDRESS oberonRTS_NewObj(oberonRTS_Type type)
{
   X2C_ADDRESS a;
   X2C_NEW((X2C_TD)type, &a, ((X2C_TD)type)->size, 0);
   return a;
} /* end NewObj() */


extern void oberonRTS_IterModules(X2C_ADDRESS session,
                oberonRTS_NameIterator iter)
{
   X2C_MD m;
   Name pname;
   m = X2C_MODULES;
   while (m) {
      pname = (Name)m->name;
      if (!iter(session, pname, 128ul)) return;
      m = m->next;
   }
} /* end IterModules() */


extern void oberonRTS_IterCommands(oberonRTS_Module mod, X2C_ADDRESS session,
                 oberonRTS_NameIterator iter)
{
   CNMs cnms;
   X2C_CARD32 i;
   Name pname;
   cnms = (CNMs)((X2C_MD)mod)->cnms;
   i = 0UL;
   for (;;) {
      pname = (Name)cnms[i];
      if (pname==0 || !iter(session, pname, 128ul)) return;
      ++i;
   }
} /* end IterCommands() */


extern void oberonRTS_IterTypes(oberonRTS_Module mod, X2C_ADDRESS session,
                oberonRTS_NameIterator iter)
{
   Name pname;
   X2C_TD type;
   type = ((X2C_MD)mod)->types;
   while (type) {
      pname = (Name)type->name;
      if (!iter(session, pname, 128ul)) return;
      type = type->next;
   }
} /* end IterTypes() */


extern X2C_BOOLEAN oberonRTS_SetStackSize(X2C_CARD32 newSize)
{
   return 1;
} /* end SetStackSize() */


extern void oberonRTS_BEGIN(void)
{
   static int oberonRTS_init = 0;
   if (oberonRTS_init) return;
   oberonRTS_init = 1;
   xrBlockManager_BEGIN();
   xrMM_BEGIN();
   oberonRTS_nullModule = 0;
   oberonRTS_nullType = 0;
}

