/* XDS v2.60: Copyright (c) 1999-2011 Excelsior, LLC. All Rights Reserved. */
/* "@(#)ProgEnv.c Feb  3 14:30:28 2012" */
/* Generated by XDS Modula-2 to ANSI C v4.20 translator */

#define X2C_int32
#define X2C_index32
#ifndef ProgEnv_H_
#include "ProgEnv.h"
#endif
#define ProgEnv_C_
#include "X2C.h"
#ifndef xmRTS_H_
#include "xmRTS.h"
#endif
#ifndef xlibOS_H_
#include "xlibOS.h"
#endif

typedef X2C_CHAR * * ARGV;


static X2C_CARD32 getNumber(void)
{
   if (X2C_argc==0) return 0UL;
   else return (X2C_CARD32)(X2C_argc-1);
   return 0;
} /* end getNumber() */


static ARGV GetArgs(void)
{
   return (ARGV)X2C_argv;
} /* end GetArgs() */


extern X2C_CARD32 ProgEnv_ArgNumber(void)
{
   return getNumber();
} /* end ArgNumber() */


extern void ProgEnv_GetArg(X2C_CARD32 n, X2C_CHAR arg[], X2C_CARD32 arg_len)
{
   X2C_CARD32 number;
   ARGV args;
   number = getNumber();
   if (n>=number) arg[0UL] = 0;
   else {
      args = GetArgs();
      X2C_COPY(args[n+1UL],4096u,arg,arg_len);
   }
} /* end GetArg() */


extern X2C_CARD32 ProgEnv_ArgLength(X2C_CARD32 n)
{
   X2C_CARD32 number;
   ARGV args;
   number = getNumber();
   if (n>=number) return 0UL;
   else {
      args = GetArgs();
      return X2C_LENGTH(args[n+1UL],4096ul);
   }
   return 0;
} /* end ArgLength() */


extern void ProgEnv_ProgramName(X2C_CHAR name[], X2C_CARD32 name_len)
{
   ARGV args;
   if (X2C_argc==0) name[0UL] = 0;
   else {
      args = GetArgs();
      X2C_COPY(args[0U],4096u,name,name_len);
   }
} /* end ProgramName() */


extern X2C_CARD32 ProgEnv_ProgramNameLength(void)
{
   ARGV args;
   if (X2C_argc==0) return 0UL;
   else {
      args = GetArgs();
      return X2C_LENGTH(args[0U],4096ul);
   }
   return 0;
} /* end ProgramNameLength() */


extern void ProgEnv_String(X2C_CHAR name[], X2C_CARD32 name_len,
                X2C_CHAR str[], X2C_CARD32 str_len)
{
   X2C_EnvString((X2C_pCHAR)name, (X2C_pCHAR)str, (str_len-1)+1UL);
} /* end String() */


extern X2C_CARD32 ProgEnv_StringLength(X2C_CHAR name[], X2C_CARD32 name_len)
{
   return X2C_EnvStringLength((X2C_pCHAR)name);
} /* end StringLength() */


extern void ProgEnv_BEGIN(void)
{
   static int ProgEnv_init = 0;
   if (ProgEnv_init) return;
   ProgEnv_init = 1;
}

