/* XDS v2.60: Copyright (c) 1999-2011 Excelsior, LLC. All Rights Reserved. */
/* "@(#)RealInOut.c Feb  3 14:30:28 2012" */
/* Generated by XDS Modula-2 to ANSI C v4.20 translator */

#define X2C_int32
#define X2C_index32
#ifndef RealInOut_H_
#include "RealInOut.h"
#endif
#define RealInOut_C_
#ifndef SRealIO_H_
#include "SRealIO.h"
#endif
#ifndef RealStr_H_
#include "RealStr.h"
#endif
#ifndef ConvTypes_H_
#include "ConvTypes.h"
#endif
#ifndef InOut_H_
#include "InOut.h"
#endif

X2C_BOOLEAN RealInOut_Done;

extern void RealInOut_ReadReal(X2C_REAL * v)
{
   X2C_CHAR s[64];
   X2C_CARD8 r;
   InOut_ReadString(s, 64ul);
   RealInOut_Done = InOut_Done;
   if (RealInOut_Done) {
      RealStr_StrToReal(s, 64ul, v, &r);
      RealInOut_Done = r==ConvTypes_strAllRight;
   }
} /* end ReadReal() */


extern void RealInOut_WriteReal(X2C_REAL r, X2C_CARD32 w)
{
   SRealIO_WriteReal(r, w);
} /* end WriteReal() */


extern void RealInOut_BEGIN(void)
{
   static int RealInOut_init = 0;
   if (RealInOut_init) return;
   RealInOut_init = 1;
   InOut_BEGIN();
   RealStr_BEGIN();
   SRealIO_BEGIN();
}

