/* XDS v2.60: Copyright (c) 1999-2011 Excelsior, LLC. All Rights Reserved. */
/* "@(#)xrFName.c Feb  3 14:30:28 2012" */
/* Generated by XDS Modula-2 to ANSI C v4.20 translator */

#define X2C_int32
#define X2C_index32
#ifndef xrFName_H_
#include "xrFName.h"
#endif
#define xrFName_C_
#ifndef platform_H_
#include "platform.h"
#endif




static void Extract(X2C_CHAR s[], X2C_CARD32 s_len, X2C_CARD32 p,
                X2C_CARD32 len, X2C_CHAR d[], X2C_CARD32 d_len)
{
   X2C_CARD32 i;
   X2C_PCOPY((void **)&s,s_len);
   i = 0UL;
   while (((len>0UL && i<=d_len-1) && p<=s_len-1) && s[p]) {
      d[i] = s[p];
      --len;
      ++i;
      ++p;
   }
   if (i<=d_len-1) d[i] = 0;
   X2C_PFREE(s);
} /* end Extract() */


extern void xrFName_X2C_ParseFileName(X2C_CHAR s[], X2C_CARD32 s_len,
                struct xrFName_Format * f)
{
   X2C_CARD32 i;
   X2C_CARD32 len;
   X2C_BOOLEAN checkDrvSep;
   f->ok0 = 0;
   f->dirPos = 0UL;
   f->dirLen = 0UL;
   f->namePos = 0UL;
   f->nameLen = 0UL;
   f->extPos = 0UL;
   f->extLen = 0UL;
   len = X2C_LENGTH(s,s_len);
   if (len==0UL) return;
   i = len;
   checkDrvSep = (pl_msdos || pl_vms) || pl_amiga;
   do {
      --i;
   } while (!(((i==0UL || s[i]==extSep) || s[i]==pathEnd) || checkDrvSep && s[i]==drvSep));
   if (s[i]==extSep) {
      f->extPos = i+1UL;
      f->extLen = (len-i)-1UL;
      len = i;
   }
   while ((i>0UL && s[i]!=pathEnd) && !(checkDrvSep && s[i]==drvSep)) --i;
   if (s[i]==pathEnd) {
      f->namePos = i+1UL;
      f->nameLen = (len-i)-1UL;
      f->dirLen = i;
      if (i==0UL) f->dirLen = 1UL;
      else if (pl_vms || (pl_msdos && i==2UL) && s[1UL]==drvSep) ++f->dirLen;
   }
   else if (checkDrvSep && s[i]==drvSep) {
      if (pl_msdos && i!=1UL) return;
      f->namePos = i+1UL;
      f->nameLen = (len-i)-1UL;
      f->dirLen = i+1UL;
   }
   else f->nameLen = len;
   f->ok0 = f->nameLen+f->extLen>0UL;
} /* end X2C_ParseFileName() */


extern void xrFName_X2C_SplitFileName(X2C_CHAR fname[], X2C_CARD32 fname_len,
                 X2C_CHAR path[], X2C_CARD32 path_len, X2C_CHAR name[],
                X2C_CARD32 name_len, X2C_CHAR ext[], X2C_CARD32 ext_len)
{
   struct xrFName_Format f;
   X2C_PCOPY((void **)&fname,fname_len);
   xrFName_X2C_ParseFileName(fname, fname_len, &f);
   if (f.ok0) {
      Extract(fname, fname_len, f.dirPos, f.dirLen, path, path_len);
      Extract(fname, fname_len, f.namePos, f.nameLen, name, name_len);
      Extract(fname, fname_len, f.extPos, f.extLen, ext, ext_len);
   }
   else {
      path[0UL] = 0;
      name[0UL] = 0;
      ext[0UL] = 0;
   }
   X2C_PFREE(fname);
} /* end X2C_SplitFileName() */


extern void xrFName_X2C_ExtractPath(X2C_CHAR fname[], X2C_CARD32 fname_len,
                X2C_CHAR path[], X2C_CARD32 path_len)
{
   struct xrFName_Format f;
   X2C_PCOPY((void **)&fname,fname_len);
   xrFName_X2C_ParseFileName(fname, fname_len, &f);
   if (f.ok0) Extract(fname, fname_len, f.dirPos, f.dirLen, path, path_len);
   else path[0UL] = 0;
   X2C_PFREE(fname);
} /* end X2C_ExtractPath() */


extern void xrFName_X2C_ExtractBaseName(X2C_CHAR fname[],
                X2C_CARD32 fname_len, X2C_CHAR n[], X2C_CARD32 n_len)
{
   struct xrFName_Format f;
   X2C_PCOPY((void **)&fname,fname_len);
   xrFName_X2C_ParseFileName(fname, fname_len, &f);
   if (f.ok0) Extract(fname, fname_len, f.namePos, f.nameLen, n, n_len);
   else n[0UL] = 0;
   X2C_PFREE(fname);
} /* end X2C_ExtractBaseName() */


extern void xrFName_X2C_ExtractFileExt(X2C_CHAR fname[],
                X2C_CARD32 fname_len, X2C_CHAR ext[], X2C_CARD32 ext_len)
{
   struct xrFName_Format f;
   X2C_PCOPY((void **)&fname,fname_len);
   xrFName_X2C_ParseFileName(fname, fname_len, &f);
   if (f.ok0) Extract(fname, fname_len, f.extPos, f.extLen, ext, ext_len);
   else ext[0UL] = 0;
   X2C_PFREE(fname);
} /* end X2C_ExtractFileExt() */


extern void xrFName_BEGIN(void)
{
   static int xrFName_init = 0;
   if (xrFName_init) return;
   xrFName_init = 1;
}

