/* ArrowBG.h  Oct 15  10:35:49  1996 */
/* Generated by H2D v1.16 */
/* from module ArrowBG and header Xm/ArrowBG.h. */
/* Types which were created during translation */

/* Copyright (c) 1996 XDS Ltd, Russia. All rights reserved. 
 *
 * $RCSfile: ArrowBG.h,v $ $Revision: 1.2 $ $Date: 1998/02/15 00:05:17 $
 */

#include <Xm/ArrowBG.h>
