/* ArrowBP.h  Nov 11  14:25:58  1996 */
/* Generated by H2D v1.18.1 */
/* from module ArrowBP and header Xm/ArrowBP.h. */
/* Types which were created during translation */

/* Copyright (c) 1996 XDS Ltd, Russia. All rights reserved. 
 *
 * $RCSfile: ArrowBP.h,v $ $Revision: 1.2 $ $Date: 1998/02/15 00:05:18 $
 */

#include <Xm/ArrowBP.h>
