/* BulletinB.h  Oct 15  18:28:0  1996 */
/* Generated by H2D v1.16 */
/* from module BulletinB and header Xm/BulletinB.h. */
/* Types which were created during translation */

/* Copyright (c) 1996 XDS Ltd, Russia. All rights reserved. 
 *
 * $RCSfile: BulletinB.h,v $ $Revision: 1.2 $ $Date: 1998/02/15 00:05:20 $
 */

#include <Xm/BulletinB.h>
