/* CascadeBG.h  Oct 15  16:5:29  1996 */
/* Generated by H2D v1.16 */
/* from module CascadeBG and header Xm/CascadeBG.h. */
/* Types which were created during translation */

/* Copyright (c) 1996 XDS Ltd, Russia. All rights reserved. 
 *
 * $RCSfile: CascadeBG.h,v $ $Revision: 1.2 $ $Date: 1998/02/15 00:05:24 $
 */

#include <Xm/CascadeBG.h>
