/* CascadeBGP.h  Nov 11  16:6:42  1996 */
/* Generated by H2D v1.18.1 */
/* from module CascadeBGP and header Xm/CascadeBGP.h. */
/* Types which were created during translation */

/* Copyright (c) 1996 XDS Ltd, Russia. All rights reserved. 
 *
 * $RCSfile: CascadeBGP.h,v $ $Revision: 1.2 $ $Date: 1998/02/15 00:05:25 $
 */

#include <Xm/CascadeBGP.h>

#ifndef CascadeBGP_H_
#define CascadeBGP_H_

typedef XmCascadeButtonGCacheObjPart * PtrXmCascadeButtonGCacheObjPart;

#endif  /* CascadeBGP_H_ */
