/* CascadeBP.h  Nov 11  15:59:59  1996 */
/* Generated by H2D v1.18.1 */
/* from module CascadeBP and header Xm/CascadeBP.h. */
/* Types which were created during translation */

/* Copyright (c) 1996 XDS Ltd, Russia. All rights reserved. 
 *
 * $RCSfile: CascadeBP.h,v $ $Revision: 1.2 $ $Date: 1998/02/15 00:05:26 $
 */

#include <Xm/CascadeBP.h>
