/* DialogSEP.h  Nov 21  14:26:32  1996 */
/* Generated by H2D v1.18.6 */
/* from module DialogSEP and header Xm/DialogSEP.h. */
/* Types which were created during translation */

/* Copyright (c) 1996 XDS Ltd, Russia. All rights reserved. 
 *
 * $RCSfile: DialogSEP.h,v $ $Revision: 1.2 $ $Date: 1998/02/15 00:05:33 $
 */

#include <Xm/DialogSEP.h>
