/* DialogS.h  Oct 15  21:57:14  1996 */
/* Generated by H2D v1.16 */
/* from module DialogS and header Xm/DialogS.h. */
/* Types which were created during translation */

/* Copyright (c) 1996 XDS Ltd, Russia. All rights reserved. 
 *
 * $RCSfile: DialogS.h,v $ $Revision: 1.2 $ $Date: 1998/02/15 00:05:31 $
 */

#include <Xm/DialogS.h>
