/* DisplayP.h  Nov 21  0:8:24  1996 */
/* Generated by H2D v1.18.6 */
/* from module DisplayP and header Xm/DisplayP.h. */
/* Types which were created during translation */

/* Copyright (c) 1996 XDS Ltd, Russia. All rights reserved. 
 *
 * $RCSfile: DisplayP.h,v $ $Revision: 1.2 $ $Date: 1998/02/15 00:05:34 $
 */

#include <Xm/DisplayP.h>
