/* DragDropP.h  Nov 20  23:18:1  1996 */
/* Generated by H2D v1.18.6 */
/* from module DragDropP and header Xm/DragDropP.h. */
/* Types which were created during translation */

/* Copyright (c) 1996 XDS Ltd, Russia. All rights reserved. 
 *
 * $RCSfile: DragDropP.h,v $ $Revision: 1.2 $ $Date: 1998/02/15 00:05:35 $
 */

#include <Xm/DragDropP.h>

#ifndef DragDropP_H_
#define DragDropP_H_

typedef struct __XmDropSiteUpdateInfoRec * Ptr__XmDropSiteUpdateInfoRec;

#endif  /* DragDropP_H_ */
