/* DrawingAP.h  Nov 11  16:20:39  1996 */
/* Generated by H2D v1.18.1 */
/* from module DrawingAP and header Xm/DrawingAP.h. */
/* Types which were created during translation */

/* Copyright (c) 1996 XDS Ltd, Russia. All rights reserved. 
 *
 * $RCSfile: DrawingAP.h,v $ $Revision: 1.2 $ $Date: 1998/02/15 00:05:35 $
 */

#include <Xm/DrawingAP.h>
