/* DrawnB.h  Oct 15  17:34:24  1996 */
/* Generated by H2D v1.16 */
/* from module DrawnB and header Xm/DrawnB.h. */
/* Types which were created during translation */

/* Copyright (c) 1996 XDS Ltd, Russia. All rights reserved. 
 *
 * $RCSfile: DrawnB.h,v $ $Revision: 1.2 $ $Date: 1998/02/15 00:05:36 $
 */

#include <Xm/DrawnB.h>

