/* DrawingA.h  Oct 15  17:34:21  1996 */
/* Generated by H2D v1.16 */
/* from module DrawingA and header Xm/DrawingA.h. */
/* Types which were created during translation */

/* Copyright (c) 1996 XDS Ltd, Russia. All rights reserved. 
 *
 * $RCSfile: DrawingA.h,v $ $Revision: 1.2 $ $Date: 1998/02/15 00:05:35 $
 */

#include <Xm/DrawingA.h>
