/* DrawnBP.h  Nov 11  16:22:6  1996 */
/* Generated by H2D v1.18.1 */
/* from module DrawnBP and header Xm/DrawnBP.h. */
/* Types which were created during translation */

/* Copyright (c) 1996 XDS Ltd, Russia. All rights reserved. 
 *
 * $RCSfile: DrawnBP.h,v $ $Revision: 1.2 $ $Date: 1998/02/15 00:05:36 $
 */

#include <Xm/DrawnBP.h>
