/* FileSB.h  Oct 15  17:34:27  1996 */
/* Generated by H2D v1.16 */
/* from module FileSB and header Xm/FileSB.h. */
/* Types which were created during translation */

/* Copyright (c) 1996 XDS Ltd, Russia. All rights reserved. 
 *
 * $RCSfile: FileSB.h,v $ $Revision: 1.2 $ $Date: 1998/02/15 00:05:36 $
 */

#include <Xm/FileSB.h>
