/* FileSBP.h  Nov 11  16:23:52  1996 */
/* Generated by H2D v1.18.1 */
/* from module FileSBP and header Xm/FileSBP.h. */
/* Types which were created during translation */

/* Copyright (c) 1996 XDS Ltd, Russia. All rights reserved. 
 *
 * $RCSfile: FileSBP.h,v $ $Revision: 1.2 $ $Date: 1998/02/15 00:05:36 $
 */

#include <Xm/FileSBP.h>
