/* FrameP.h  Nov 11  16:27:58  1996 */
/* Generated by H2D v1.18.1 */
/* from module FrameP and header Xm/FrameP.h. */
/* Types which were created during translation */

/* Copyright (c) 1996 XDS Ltd, Russia. All rights reserved. 
 *
 * $RCSfile: FrameP.h,v $ $Revision: 1.2 $ $Date: 1998/02/15 00:05:37 $
 */

#include <Xm/FrameP.h>
