/* LabelGP.h  Nov 12  20:49:0  1996 */
/* Generated by H2D v1.18.1 */
/* from module LabelGP and header Xm/LabelGP.h. */
/* Types which were created during translation */

/* Copyright (c) 1996 XDS Ltd, Russia. All rights reserved. 
 *
 * $RCSfile: LabelGP.h,v $ $Revision: 1.2 $ $Date: 1998/02/15 00:05:38 $
 */

#include <Xm/LabelGP.h>

#ifndef LabelGP_H_
#define LabelGP_H_

typedef XmLabelGCacheObjPart * PtrXmLabelGCacheObjPart;

#endif  /* LabelGP_H_ */
