/* LabelP.h  Nov 12  19:47:44  1996 */
/* Generated by H2D v1.18.1 */
/* from module LabelP and header Xm/LabelP.h. */
/* Types which were created during translation */

/* Copyright (c) 1996 XDS Ltd, Russia. All rights reserved. 
 *
 * $RCSfile: LabelP.h,v $ $Revision: 1.2 $ $Date: 1998/02/15 00:05:38 $
 */

#include <Xm/LabelP.h>
