/* List.h  Oct 19  19:36:50  1996 */
/* Generated by H2D v1.16 */
/* from module List and header Xm/List.h. */
/* Types which were created during translation */

/* Copyright (c) 1996 XDS Ltd, Russia. All rights reserved. 
 *
 * $RCSfile: List.h,v $ $Revision: 1.2 $ $Date: 1998/02/15 00:05:38 $
 */

#include <Xm/List.h>

