/* ListP.h  Nov 11  16:36:37  1996 */
/* Generated by H2D v1.18.1 */
/* from module ListP and header Xm/ListP.h. */
/* Types which were created during translation */

/* Copyright (c) 1996 XDS Ltd, Russia. All rights reserved. 
 *
 * $RCSfile: ListP.h,v $ $Revision: 1.3 $ $Date: 1998/07/28 15:54:15 $
 */

#include <Xm/ListP.h>
#include "X.h"

#ifndef ListP_H_
#define ListP_H_

typedef ElementPtr *ElementList;

#endif  /* ListP_H_ */
