/* MainW.h  Oct 15  18:36:16  1996 */
/* Generated by H2D v1.16 */
/* from module MainW and header Xm/MainW.h. */
/* Types which were created during translation */

/* Copyright (c) 1996 XDS Ltd, Russia. All rights reserved. 
 *
 * $RCSfile: MainW.h,v $ $Revision: 1.2 $ $Date: 1998/02/15 00:05:39 $
 */

#include <Xm/MainW.h>
