/* MenuShellP.h  Nov 11  16:41:12  1996 */
/* Generated by H2D v1.18.1 */
/* from module MenuShellP and header Xm/MenuShellP.h. */
/* Types which were created during translation */

/* Copyright (c) 1996 XDS Ltd, Russia. All rights reserved. 
 *
 * $RCSfile: MenuShellP.h,v $ $Revision: 1.2 $ $Date: 1998/02/15 00:05:40 $
 */

#include <Xm/MenuShellP.h>
