/* MessageBP.h  Nov 11  17:0:38  1996 */
/* Generated by H2D v1.18.1 */
/* from module MessageBP and header Xm/MessageBP.h. */
/* Types which were created during translation */

/* Copyright (c) 1996 XDS Ltd, Russia. All rights reserved. 
 *
 * $RCSfile: MessageBP.h,v $ $Revision: 1.2 $ $Date: 1998/02/15 00:05:40 $
 */

#include <Xm/MessageBP.h>
