/* MessageB.h  Oct 15  18:37:42  1996 */
/* Generated by H2D v1.16 */
/* from module MessageB and header Xm/MessageB.h. */
/* Types which were created during translation */

/* Copyright (c) 1996 XDS Ltd, Russia. All rights reserved. 
 *
 * $RCSfile: MessageB.h,v $ $Revision: 1.2 $ $Date: 1998/02/15 00:05:40 $
 */

#include <Xm/MessageB.h>
