/* PanedW.h  Oct 15  18:37:44  1996 */
/* Generated by H2D v1.16 */
/* from module PanedW and header Xm/PanedW.h. */
/* Types which were created during translation */

/* Copyright (c) 1996 XDS Ltd, Russia. All rights reserved. 
 *
 * $RCSfile: PanedW.h,v $ $Revision: 1.2 $ $Date: 1998/02/15 00:05:41 $
 */

#include <Xm/PanedW.h>

