/* Protocols.h  Oct 15  18:37:54  1996 */
/* Generated by H2D v1.16 */
/* from module Protocols and header Xm/Protocols.h. */
/* Types which were created during translation */

/* Copyright (c) 1996 XDS Ltd, Russia. All rights reserved. 
 *
 * $RCSfile: Protocols.h,v $ $Revision: 1.2 $ $Date: 1998/02/15 00:05:42 $
 */

#include <Xm/Protocols.h>

