/* ProtocolsP.h  Nov 12  16:1:55  1996 */
/* Generated by H2D v1.18.1 */
/* from module ProtocolsP and header Xm/ProtocolsP.h. */
/* Types which were created during translation */

/* Copyright (c) 1996 XDS Ltd, Russia. All rights reserved. 
 *
 * $RCSfile: ProtocolsP.h,v $ $Revision: 1.2 $ $Date: 1998/02/15 00:05:43 $
 */

#include <Xm/ProtocolsP.h>
