/* PushB.h  Oct 15  19:19:1  1996 */
/* Generated by H2D v1.16 */
/* from module PushB and header Xm/PushB.h. */
/* Types which were created during translation */

/* Copyright (c) 1996 XDS Ltd, Russia. All rights reserved. 
 *
 * $RCSfile: PushB.h,v $ $Revision: 1.2 $ $Date: 1998/02/15 00:05:43 $
 */

#include <Xm/PushB.h>
