/* PushBP.h  Nov 12  19:48:48  1996 */
/* Generated by H2D v1.18.1 */
/* from module PushBP and header Xm/PushBP.h. */
/* Types which were created during translation */

/* Copyright (c) 1996 XDS Ltd, Russia. All rights reserved. 
 *
 * $RCSfile: PushBP.h,v $ $Revision: 1.2 $ $Date: 1998/02/15 00:05:44 $
 */

#include <Xm/PushBP.h>
