/* PushBGP.h  Nov 12  16:8:23  1996 */
/* Generated by H2D v1.18.1 */
/* from module PushBGP and header Xm/PushBGP.h. */
/* Types which were created during translation */

/* Copyright (c) 1996 XDS Ltd, Russia. All rights reserved. 
 *
 * $RCSfile: PushBGP.h,v $ $Revision: 1.2 $ $Date: 1998/02/15 00:05:44 $
 */

#include <Xm/PushBGP.h>

#ifndef PushBGP_H_
#define PushBGP_H_

typedef XmPushButtonGCacheObjPart * PtrXmPushButtonGCacheObjPart;

#endif  /* PushBGP_H_ */
