/* RepType.h  Oct 15  19:19:7  1996 */
/* Generated by H2D v1.16 */
/* from module RepType and header Xm/RepType.h. */
/* Types which were created during translation */

/* Copyright (c) 1996 XDS Ltd, Russia. All rights reserved. 
 *
 * $RCSfile: RepType.h,v $ $Revision: 1.2 $ $Date: 1998/02/15 00:05:45 $
 */

#include <Xm/RepType.h>

#ifndef RepType_H_
#define RepType_H_

typedef unsigned char * PUChar;

#endif  /* RepType_H_ */
