/* SashP.h  Nov 12  16:18:0  1996 */
/* Generated by H2D v1.18.1 */
/* from module SashP and header Xm/SashP.h. */
/* Types which were created during translation */

/* Copyright (c) 1996 XDS Ltd, Russia. All rights reserved. 
 *
 * $RCSfile: SashP.h,v $ $Revision: 1.2 $ $Date: 1998/02/15 00:05:47 $
 */

#include <Xm/SashP.h>
