/* Scale.h  Oct 15  19:19:15  1996 */
/* Generated by H2D v1.16 */
/* from module Scale and header Xm/Scale.h. */
/* Types which were created during translation */

/* Copyright (c) 1996 XDS Ltd, Russia. All rights reserved. 
 *
 * $RCSfile: Scale.h,v $ $Revision: 1.2 $ $Date: 1998/02/15 00:05:47 $
 */

#include <Xm/Scale.h>

