/* ScaleP.h  Nov 12  16:19:8  1996 */
/* Generated by H2D v1.18.1 */
/* from module ScaleP and header Xm/ScaleP.h. */
/* Types which were created during translation */

/* Copyright (c) 1996 XDS Ltd, Russia. All rights reserved. 
 *
 * $RCSfile: ScaleP.h,v $ $Revision: 1.2 $ $Date: 1998/02/15 00:05:48 $
 */

#include <Xm/ScaleP.h>
