/* Screen.h  Oct 15  19:21:38  1996 */
/* Generated by H2D v1.16 */
/* from module Screen and header Xm/Screen.h. */
/* Types which were created during translation */

/* Copyright (c) 1996 XDS Ltd, Russia. All rights reserved. 
 *
 * $RCSfile: Screen.h,v $ $Revision: 1.2 $ $Date: 1998/02/15 00:05:48 $
 */

#include <Xm/Screen.h>
