/* ScrolledWP.h  Nov 11  16:38:38  1996 */
/* Generated by H2D v1.18.1 */
/* from module ScrolledWP and header Xm/ScrolledWP.h. */
/* Types which were created during translation */

/* Copyright (c) 1996 XDS Ltd, Russia. All rights reserved. 
 *
 * $RCSfile: ScrolledWP.h,v $ $Revision: 1.2 $ $Date: 1998/02/15 00:05:50 $
 */

#include <Xm/ScrolledWP.h>
