/* SelectioB.h  Oct 15  19:21:28  1996 */
/* Generated by H2D v1.16 */
/* from module SelectioB and header Xm/SelectioB.h. */
/* Types which were created during translation */

/* Copyright (c) 1996 XDS Ltd, Russia. All rights reserved. 
 *
 * $RCSfile: SelectioB.h,v $ $Revision: 1.2 $ $Date: 1998/02/15 00:05:51 $
 */

#include <Xm/SelectioB.h>
