/* SeparatorP.h  Nov 12  16:23:41  1996 */
/* Generated by H2D v1.18.1 */
/* from module SeparatorP and header Xm/SeparatorP.h. */
/* Types which were created during translation */

/* Copyright (c) 1996 XDS Ltd, Russia. All rights reserved. 
 *
 * $RCSfile: SeparatorP.h,v $ $Revision: 1.2 $ $Date: 1998/02/15 00:05:52 $
 */

#include <Xm/SeparatorP.h>
