/* SeparatoGP.h  Nov 12  16:22:34  1996 */
/* Generated by H2D v1.18.1 */
/* from module SeparatoGP and header Xm/SeparatoGP.h. */
/* Types which were created during translation */

/* Copyright (c) 1996 XDS Ltd, Russia. All rights reserved. 
 *
 * $RCSfile: SeparatoGP.h,v $ $Revision: 1.2 $ $Date: 1998/02/15 00:05:51 $
 */

#include <Xm/SeparatoGP.h>

#ifndef SeparatoGP_H_
#define SeparatoGP_H_

typedef XmSeparatorGCacheObjPart * PtrXmSeparatorGCacheObjPart;

#endif  /* SeparatoGP_H_ */
