/* TearOffBP.h  Nov 12  19:50:7  1996 */
/* Generated by H2D v1.18.1 */
/* from module TearOffBP and header Xm/TearOffBP.h. */
/* Types which were created during translation */

/* Copyright (c) 1996 XDS Ltd, Russia. All rights reserved. 
 *
 * $RCSfile: TearOffBP.h,v $ $Revision: 1.2 $ $Date: 1998/02/15 00:05:52 $
 */

#include <Xm/TearOffBP.h>
