/* TextP.h  Nov 12  19:19:51  1996 */
/* Generated by H2D v1.18.1 */
/* from module TextP and header Xm/TextP.h. */
/* Types which were created during translation */

/* Copyright (c) 1996 XDS Ltd, Russia. All rights reserved. 
 *
 * $RCSfile: TextP.h,v $ $Revision: 1.2 $ $Date: 1998/02/15 00:05:54 $
 */

#include <Xm/TextP.h>

#ifndef TextP_H_
#define TextP_H_

typedef struct _XmSourceDataRec * Ptr_XmSourceDataRec;
typedef RangeRec * PtrRangeRec;
typedef struct _OutputDataRec * Ptr_OutputDataRec;
typedef struct _InputDataRec * Ptr_InputDataRec;

#endif  /* TextP_H_ */
