/* ToggleBG.h  Oct 15  20:27:32  1996 */
/* Generated by H2D v1.16 */
/* from module ToggleBG and header Xm/ToggleBG.h. */
/* Types which were created during translation */

/* Copyright (c) 1996 XDS Ltd, Russia. All rights reserved. 
 *
 * $RCSfile: ToggleBG.h,v $ $Revision: 1.2 $ $Date: 1998/02/15 00:05:55 $
 */

#include <Xm/ToggleBG.h>
