/* VendorSEP.h  Nov 21  14:18:42  1996 */
/* Generated by H2D v1.18.6 */
/* from module VendorSEP and header Xm/VendorSEP.h. */
/* Types which were created during translation */

/* Copyright (c) 1996 XDS Ltd, Russia. All rights reserved. 
 *
 * $RCSfile: VendorSEP.h,v $ $Revision: 1.2 $ $Date: 1998/02/15 00:05:57 $
 */

#include <Xm/VendorSEP.h>
