/* VendorS.h  Oct 15  22:36:15  1996 */
/* Generated by H2D v1.16 */
/* from module VendorS and header Xm/VendorS.h. */
/* Types which were created during translation */

/* Copyright (c) 1996 XDS Ltd, Russia. All rights reserved. 
 *
 * $RCSfile: VendorS.h,v $ $Revision: 1.2 $ $Date: 1998/02/15 00:05:57 $
 */

#include <Xm/VendorS.h>
