/* VirtKeys.h  Oct 19  19:27:34  1996 */
/* Generated by H2D v1.16 */
/* from module VirtKeys and header Xm/VirtKeys.h. */
/* Types which were created during translation */

/* Copyright (c) 1996 XDS Ltd, Russia. All rights reserved. 
 *
 * $RCSfile: VirtKeys.h,v $ $Revision: 1.2 $ $Date: 1998/02/15 00:05:57 $
 */

#include <Xm/VirtKeys.h>
