/* WorldP.h  Nov 21  14:31:31  1996 */
/* Generated by H2D v1.18.6 */
/* from module WorldP and header Xm/WorldP.h. */
/* Types which were created during translation */

/* Copyright (c) 1996 XDS Ltd, Russia. All rights reserved. 
 *
 * $RCSfile: WorldP.h,v $ $Revision: 1.2 $ $Date: 1998/02/15 00:05:58 $
 */

#include <Xm/WorldP.h>
