/* XmAll.h  Oct 20  20:20:31  1996 */
/* Generated by H2D v1.16 */
/* from module XmAll and header Xm/XmAll.h. */
/* Types which were created during translation */

/* Copyright (c) 1996 XDS Ltd, Russia. All rights reserved. 
 *
 * $RCSfile: XmAll.h,v $ $Revision: 1.3 $ $Date: 1998/02/15 00:05:58 $
 */

#include "Xm.h"
#include <Xm/XmAll.h>
