/* XmAllP.h  Nov 27  0:11:41  1996 */
/* Generated by H2D v1.18.6a */
/* from module XmAllP and header Xm/XmAllP.h. */
/* Types which were created during translation */

/* Copyright (c) 1996,1997 XDS Ltd, Russia. All rights reserved. 
 *
 * $RCSfile: XmAllP.h,v $ $Revision: 1.3 $ $Date: 1998/07/28 15:54:16 $
 */

#include <Xm/XmP.h>
#include <Xm/ArrowBP.h>
#include <Xm/ArrowBGP.h>
#include <Xm/AtomMgr.h>
#include <Xm/BulletinBP.h>
#include <Xm/CascadeBP.h>
#include <Xm/CascadeBGP.h>
#include <Xm/CacheP.h>
#include <Xm/CommandP.h>
#include <Xm/CutPasteP.h>
#include <Xm/DialogSP.h>
#include <Xm/DialogSEP.h>
#include <Xm/DisplayP.h>
#include <Xm/DragCP.h>
#include <Xm/DragIconP.h>
#include <Xm/DragOverSP.h>
#include <Xm/DropSMgrP.h>
#include <Xm/DropTransP.h>
#include <Xm/DrawP.h>
#include <Xm/DrawingAP.h>
#include <Xm/DrawnBP.h>
#include <Xm/FileSBP.h>
#include <Xm/FormP.h>
#include <Xm/FrameP.h>
#include <Xm/LabelP.h>
#include <Xm/LabelGP.h>
#include <Xm/ListP.h>
#include <Xm/MainWP.h>
#include <Xm/MenuShellP.h>
#include <Xm/MenuUtilP.h>
#include <Xm/MessageBP.h>
#include <Xm/MwmUtil.h>
#include <Xm/PanedWP.h>
#include <Xm/ProtocolsP.h>
#include <Xm/PushBP.h>
#include <Xm/PushBGP.h>
#include <Xm/RepType.h>
#include <Xm/RowColumnP.h>
#include <Xm/RCUtilsP.h>
#include <Xm/SashP.h>
#include <Xm/ScaleP.h>
#include <Xm/ScreenP.h>
#include <Xm/ScrollBarP.h>
#include <Xm/ScrolledWP.h>
#include <Xm/SelectioBP.h>
#include <Xm/SeparatoGP.h>
#include <Xm/SeparatorP.h>
#include <Xm/TextP.h>
#include <Xm/TextFP.h>
#include <Xm/TearOffP.h>
#include <Xm/TearOffBP.h>
#include <Xm/ToggleBP.h>
#include <Xm/ToggleBGP.h>
#include <Xm/TransltnsP.h>
#include <Xm/VaSimpleP.h>
#include <Xm/VendorSEP.h>
#include <Xm/VirtKeysP.h>
#include <Xm/WorldP.h>

#include "X.h"

#ifndef __XDS_XmAllP_H_
#define __XDS_XmAllP_H_

typedef XmSyntheticResource *XmSyntheticResourcesList;

typedef XmKeyboardData *XmKeyboardDataList;

typedef XmSecondaryResourceData *XmSecondaryResourceDataPtr;

typedef XmStringDirection *XmStringDirectionTable;

typedef XmBaselineMargins *XmBaselineMarginsPtr;

typedef _XmHighlightRec *_XmHighlightList;

typedef XmRegionBox *XmRegionBoxPtr;
typedef XmRegionBox *XmRegionBoxList;

typedef XmColorData *XmColorDataPtr;
typedef XmColorData *XmColorDataList;

typedef XmGeoMatrix *XmGeoMatrixPtr;
typedef XmGeoMatrix *XmGeoMatrixList;

typedef struct _XmGadgetCache *_XmGadgetCachePtr;

typedef struct _XmWrapperDataRec *XmWrapperDataPtr;

typedef XmBaseClassExt *XmBaseClassExtPtr;

typedef XmGenericClassExt *XmGenericClassExtPtr;

typedef XmLabelGCacheObjPart *XmLabelGCache;

typedef XmCascadeButtonGCacheObjPart *XmCascadeButtonGCache;

typedef XmDragReceiverInfoStruct *XmDragReceiverInfo;

typedef XmKeyBindingRec *XmKeyBindingsList;

typedef XmDragCursorRec *XmDragCursorPtr;

typedef XmDragCursorCache *XmDragCursorCachePtr;

typedef ElementPtr *ElementList;

typedef _XmBuildVirtualKeyStruct *_XmBuildVirtualKeyList;

typedef XmSeparatorGCacheObjPart *XmSeparatorGCache;

typedef struct _XmTranslRec *XmTranslPtr;

typedef struct _XmProtocolRec *XmProtocolList;

typedef struct _XmProtocolMgrRec *XmProtocolMgrList;

typedef XmPushButtonGCacheObjPart *XmPushButtonGCache;

typedef struct _XmSourceDataRec *XmSourceData;

typedef RangeRec *Range;

typedef LineTableExtraRec *LineTableExtrasList;

typedef struct _OutputDataRec *OutputData;

typedef XmTextWidget *XmTextWidget;

typedef XmTextScanType *XmTextScanTypeList;

typedef struct _InputDataRec *InputData;

typedef XmToggleButtonGCacheObjPart *XmToggleButtonGCache;

#endif  /* h2d_XmAllP_H_ */
