/* XDS v2.60: Copyright (c) 1999-2011 Excelsior, LLC. All Rights Reserved. */
/* "@(#)FileSys.c Feb  3 14:31:18 2012" */
/* Generated by XDS Modula-2 to ANSI C v4.20 translator */

#define X2C_int32
#define X2C_index32
#ifndef FileSys_H_
#include "FileSys.h"
#endif
#define FileSys_C_
#ifndef SysClock_H_
#include "SysClock.h"
#endif
#ifndef xlibOS_H_
#include "xlibOS.h"
#endif
#ifndef xmRTS_H_
#include "xmRTS.h"
#endif
#ifndef TimeConv_H_
#include "TimeConv.h"
#endif




struct _0 {
   X2C_CHAR * Adr;
   X2C_INDEX Len0;
};

typedef struct _0 * NMBUF;


static X2C_ADDRESS ztname(NMBUF * nmbuf, const X2C_CHAR nm[],
                X2C_CARD32 nm_len)
{
   X2C_CARD32 i;
   X2C_INDEX tmp[1];
   *nmbuf = 0;
   i = 0UL;
   while (i<=nm_len-1 && nm[i]) ++i;
   if (i<=nm_len-1) return (X2C_ADDRESS)nm;
   if (*nmbuf) {
      if (i>(*nmbuf)->Len0-1) {
         X2C_DYNDEALLOCATE((X2C_ADDRESS*)nmbuf);
         X2C_DYNALLOCATE((X2C_ADDRESS*)nmbuf,1u,(tmp[0] = i+1UL,tmp),1u);
      }
   }
   else X2C_DYNALLOCATE((X2C_ADDRESS*)nmbuf,1u,(tmp[0] = i+1UL,tmp),1u);
   X2C_COPY(nm,nm_len,(*nmbuf)->Adr,(*nmbuf)->Len0);
   return (X2C_ADDRESS)(*nmbuf)->Adr;
} /* end ztname() */

static NMBUF buf0;

static NMBUF buf1;


extern X2C_BOOLEAN FileSys_Exists(X2C_CHAR fname[], X2C_CARD32 fname_len)
{
   return X2C_Exists((X2C_pCHAR)ztname(&buf0, fname, fname_len));
} /* end Exists() */


extern void FileSys_ModifyTime(X2C_CHAR fname[], X2C_CARD32 fname_len,
                X2C_CARD32 * time0, X2C_BOOLEAN * exist)
{
   X2C_ModifyTime((X2C_pCHAR)ztname(&buf0, fname, fname_len), time0, exist);
} /* end ModifyTime() */


extern void FileSys_SetFileTime(X2C_CHAR fname[], X2C_CARD32 fname_len,
                X2C_CARD32 time0)
{
   X2C_SetFileTime((X2C_pCHAR)ztname(&buf0, fname, fname_len), time0);
} /* end SetFileTime() */


static X2C_BOOLEAN EqualIgnoreCase(X2C_CHAR fname[], X2C_CARD32 fname_len,
                X2C_CHAR newname[], X2C_CARD32 newname_len)
{
   X2C_INT32 i;
   X2C_INT32 tmp;
   X2C_BOOLEAN EqualIgnoreCase_ret;
   X2C_PCOPY((void **)&fname,fname_len);
   X2C_PCOPY((void **)&newname,newname_len);
   tmp = fname_len-1L;
   i = 0L;
   if (i<=tmp) for (;; i++) {
      fname[i] = X2C_CAP(fname[i]);
      if (i==tmp) break;
   } /* end for */
   tmp = newname_len-1L;
   i = 0L;
   if (i<=tmp) for (;; i++) {
      newname[i] = X2C_CAP(newname[i]);
      if (i==tmp) break;
   } /* end for */
   EqualIgnoreCase_ret = X2C_STRCMP_PROC((X2C_pVOID)fname, fname_len,
                (X2C_pVOID)newname, newname_len)==0;
   X2C_PFREE(fname);
   X2C_PFREE(newname);
   return EqualIgnoreCase_ret;
} /* end EqualIgnoreCase() */


extern void FileSys_Rename(X2C_CHAR fname[], X2C_CARD32 fname_len,
                X2C_CHAR newname[], X2C_CARD32 newname_len,
                X2C_BOOLEAN * done)
{
   X2C_pCHAR newnm;
   newnm = (X2C_pCHAR)ztname(&buf0, newname, newname_len);
   if (EqualIgnoreCase(fname, fname_len, newname, newname_len)) {
      *done = FileSys_Exists(fname, fname_len);
      return;
   }
   *done = X2C_Remove(newnm)==0;
   *done = X2C_Rename((X2C_pCHAR)ztname(&buf1, fname, fname_len), newnm)==0;
} /* end Rename() */


extern void FileSys_Remove(X2C_CHAR fname[], X2C_CARD32 fname_len,
                X2C_BOOLEAN * done)
{
   *done = X2C_Remove((X2C_pCHAR)ztname(&buf0, fname, fname_len))==0;
} /* end Remove() */


extern void FileSys_FullName(X2C_CHAR full[], X2C_CARD32 full_len,
                X2C_CHAR name[], X2C_CARD32 name_len)
{
   X2C_PCOPY((void **)&name,name_len);
   X2C_FullName((X2C_pCHAR)full, full_len, (X2C_pCHAR)ztname(&buf0, name,
                name_len));
   X2C_PFREE(name);
} /* end FullName() */


extern X2C_CARD32 FileSys_GetCDNameLength(void)
{
   return X2C_GetCDNameLength();
} /* end GetCDNameLength() */


extern void FileSys_GetCDName(X2C_CHAR s[], X2C_CARD32 s_len)
{
   X2C_GetCDName((X2C_pCHAR)s, s_len);
} /* end GetCDName() */


extern X2C_BOOLEAN FileSys_SetCD(X2C_CHAR name[], X2C_CARD32 name_len)
{
   X2C_BOOLEAN FileSys_SetCD_ret;
   X2C_PCOPY((void **)&name,name_len);
   FileSys_SetCD_ret = X2C_SetCD((X2C_pCHAR)ztname(&buf0, name, name_len));
   X2C_PFREE(name);
   return FileSys_SetCD_ret;
} /* end SetCD() */


static void copy(struct SysClock_DateTime * t, struct X2C_TimeStruct f)
{
   if (f.month<1UL) f.month = 1UL;
   if (f.month>12UL) f.month = 12UL;
   if (f.day<1UL) f.day = 1UL;
   if (f.day>31UL) f.day = 31UL;
   if (f.hour>23UL) f.hour = 23UL;
   if (f.min0>59UL) f.min0 = 59UL;
   if (f.sec>59UL) f.sec = 59UL;
   if (f.fracs>99UL) f.fracs = 99UL;
   if (f.zone<-780L) f.zone = -780L;
   if (f.zone>720L) f.zone = 720L;
   t->year = f.year;
   t->month = f.month;
   t->day = f.day;
   t->hour = f.hour;
   t->minute = f.min0;
   t->second = f.sec;
   t->fractions = f.fracs;
   t->zone = f.zone;
   t->SummerTimeFlag = f.stf;
} /* end copy() */


static void copyEntry(struct FileSys_Entry * e, struct X2C_Dir * d)
{
   e->fileSize = d->size;
   e->nameSize = d->namelen;
   e->isDir = d->is_dir;
   copy(&e->creaTime, d->cretime);
   copy(&e->modfTime, d->mdftime);
} /* end copyEntry() */


extern void FileSys_OpenDir(FileSys_Directory * dir, X2C_CHAR name[],
                X2C_CARD32 name_len, struct FileSys_Entry * entry)
{
   X2C_PCOPY((void **)&name,name_len);
   entry->done = 0;
   X2C_ALLOCATE((X2C_ADDRESS*)dir,sizeof(struct X2C_Dir));
   if ((struct X2C_Dir *)*dir==0) goto label;
   X2C_DirOpen((struct X2C_Dir *)*dir, (X2C_pCHAR)ztname(&buf0, name,
                name_len));
   entry->done = ((struct X2C_Dir *)*dir)->done;
   if (entry->done) copyEntry(entry, (struct X2C_Dir *)*dir);
   label:;
   X2C_PFREE(name);
} /* end OpenDir() */


extern void FileSys_NextDirEntry(FileSys_Directory dir,
                struct FileSys_Entry * entry)
{
   if ((struct X2C_Dir *)dir==0) {
      entry->done = 0;
      return;
   }
   X2C_DirNext((struct X2C_Dir *)dir);
   entry->done = ((struct X2C_Dir *)dir)->done;
   if (entry->done) copyEntry(entry, (struct X2C_Dir *)dir);
} /* end NextDirEntry() */


extern void FileSys_CloseDir(FileSys_Directory * dir)
{
   if ((struct X2C_Dir *)*dir==0) return;
   X2C_DirClose((struct X2C_Dir *)*dir);
   if (((struct X2C_Dir *)*dir)->done) {
      X2C_DEALLOCATE((X2C_ADDRESS*)dir);
      *dir = 0;
   }
} /* end CloseDir() */


extern void FileSys_GetName(FileSys_Directory dir, X2C_CHAR name[],
                X2C_CARD32 name_len)
{
   X2C_DirGetName((struct X2C_Dir *)dir, (X2C_pCHAR)name, name_len);
} /* end GetName() */


extern X2C_BOOLEAN FileSys_CreateDirectory(X2C_CHAR name[],
                X2C_CARD32 name_len)
{
   return X2C_CreateDirectory((X2C_pCHAR)ztname(&buf0, name, name_len));
} /* end CreateDirectory() */


extern X2C_BOOLEAN FileSys_RemoveDirectory(X2C_CHAR name[],
                X2C_CARD32 name_len)
{
   return X2C_RemoveDirectory((X2C_pCHAR)ztname(&buf0, name, name_len));
} /* end RemoveDirectory() */


extern X2C_BOOLEAN FileSys_GetDrive(X2C_CHAR * drive)
{
   return X2C_GetDrive(drive)==0L;
} /* end GetDrive() */


extern X2C_BOOLEAN FileSys_SetDrive(X2C_CHAR drive)
{
   return X2C_SetDrive(drive)==0L;
} /* end SetDrive() */


extern X2C_BOOLEAN FileSys_GetDriveCDNameLength(X2C_CHAR drive,
                X2C_CARD32 * len)
{
   return X2C_GetDriveCDNameLength(drive, len)==0L;
} /* end GetDriveCDNameLength() */


extern X2C_BOOLEAN FileSys_GetDriveCDName(X2C_CHAR drive, X2C_CHAR dir[],
                X2C_CARD32 dir_len)
{
   return X2C_GetDriveCDName(drive, (X2C_pCHAR)dir, (dir_len-1)+1UL)==0L;
} /* end GetDriveCDName() */


extern X2C_BOOLEAN FileSys_GetLabel(X2C_CHAR drive, X2C_CHAR label[],
                X2C_CARD32 label_len)
{
   return X2C_GetLabel(drive, (X2C_pCHAR)label, (label_len-1)+1UL)==0L;
} /* end GetLabel() */


extern void FileSys_BEGIN(void)
{
   static int FileSys_init = 0;
   if (FileSys_init) return;
   FileSys_init = 1;
   TimeConv_BEGIN();
   SysClock_BEGIN();
   buf0 = 0;
   buf1 = 0;
}

