/* XDS v2.60: Copyright (c) 1999-2011 Excelsior, LLC. All Rights Reserved. */
/* "@(#)ProgExec.c Feb  3 14:31:18 2012" */
/* Generated by XDS Modula-2 to ANSI C v4.20 translator */

#define X2C_int32
#define X2C_index32
#ifndef ProgExec_H_
#include "ProgExec.h"
#endif
#define ProgExec_C_
#ifndef xosExec_H_
#include "xosExec.h"
#endif
#ifndef xmRTS_H_
#include "xmRTS.h"
#endif
#ifndef IOChan_H_
#include "IOChan.h"
#endif
#ifndef StdChans_H_
#include "StdChans.h"
#endif
#include "X2C.h"


static void execPrologue(void)
{
   IOChan_Flush(StdChans_OutChan());
   IOChan_Flush(StdChans_ErrChan());
} /* end execPrologue() */


static void execEpilogue(void)
{
   StdChans_Synchronize();
} /* end execEpilogue() */


extern X2C_BOOLEAN ProgExec_Execute(X2C_CHAR program[],
                X2C_CARD32 program_len, X2C_CHAR args[], X2C_CARD32 args_len,
                 X2C_CARD32 * exit0)
{
   X2C_BOOLEAN res;
   X2C_BOOLEAN ProgExec_Execute_ret;
   X2C_PCOPY((void **)&program,program_len);
   X2C_PCOPY((void **)&args,args_len);
   execPrologue();
   res = X2C_Execute((X2C_pCHAR)program, (X2C_pCHAR)args, 0, exit0)==0L;
   execEpilogue();
   ProgExec_Execute_ret = res;
   X2C_PFREE(program);
   X2C_PFREE(args);
   return ProgExec_Execute_ret;
} /* end Execute() */


extern X2C_BOOLEAN ProgExec_ExecuteNoWindow(X2C_CHAR program[],
                X2C_CARD32 program_len, X2C_CHAR args[], X2C_CARD32 args_len,
                 X2C_CARD32 * exit0)
{
   X2C_BOOLEAN res;
   X2C_BOOLEAN ProgExec_ExecuteNoWindow_ret;
   X2C_PCOPY((void **)&program,program_len);
   X2C_PCOPY((void **)&args,args_len);
   execPrologue();
   res = X2C_ExecuteNoWindow((X2C_pCHAR)program, (X2C_pCHAR)args, 0,
                exit0)==0L;
   execEpilogue();
   ProgExec_ExecuteNoWindow_ret = res;
   X2C_PFREE(program);
   X2C_PFREE(args);
   return ProgExec_ExecuteNoWindow_ret;
} /* end ExecuteNoWindow() */


extern X2C_BOOLEAN ProgExec_Command(X2C_CHAR command[],
                X2C_CARD32 command_len, X2C_CARD32 * exit0)
{
   X2C_BOOLEAN res;
   X2C_BOOLEAN ProgExec_Command_ret;
   X2C_PCOPY((void **)&command,command_len);
   execPrologue();
   res = X2C_Command((X2C_pCHAR)command, exit0)==0L;
   execEpilogue();
   ProgExec_Command_ret = res;
   X2C_PFREE(command);
   return ProgExec_Command_ret;
} /* end Command() */


extern void ProgExec_BEGIN(void)
{
   static int ProgExec_init = 0;
   if (ProgExec_init) return;
   ProgExec_init = 1;
   StdChans_BEGIN();
   IOChan_BEGIN();
}

