/* XDS v2.60: Copyright (c) 1999-2011 Excelsior, LLC. All Rights Reserved. */
/* "@(#)RealIO.c Feb  3 14:31:18 2012" */
/* Generated by XDS Modula-2 to ANSI C v4.20 translator */

#define X2C_int32
#define X2C_index32
#ifndef RealIO_H_
#include "RealIO.h"
#endif
#define RealIO_C_
#ifndef IOChan_H_
#include "IOChan.h"
#endif
#ifndef IOConsts_H_
#include "IOConsts.h"
#endif
#ifndef TextIO_H_
#include "TextIO.h"
#endif
#ifndef RealStr_H_
#include "RealStr.h"
#endif
#ifndef ConvTypes_H_
#include "ConvTypes.h"
#endif
#ifndef CharClass_H_
#include "CharClass.h"
#endif
#ifndef RealConv_H_
#include "RealConv.h"
#endif

#define RealIO_ok IOConsts_allRight

#define RealIO_strHigh 127

typedef X2C_CHAR string[128];


extern void RealIO_ReadReal(IOChan_ChanId cid, X2C_REAL * real)
{
   ConvTypes_ScanState state;
   X2C_CARD8 class0;
   X2C_CARD8 res;
   X2C_CARD8 conv;
   string str;
   X2C_CHAR ch;
   X2C_CARD32 n;
   X2C_BOOLEAN read0;
   X2C_BOOLEAN fit;
   n = 0UL;
   fit = 1;
   read0 = 0;
   state = (ConvTypes_ScanState)RealConv_ScanReal;
   for (;;) {
      IOChan_Look(cid, &ch, &res);
      if (res!=IOConsts_allRight) ch = 0;
      state(ch, &class0, (X2C_PROC *) &state);
      switch ((unsigned)class0) {
      case ConvTypes_padding:
         IOChan_Skip(cid);
         read0 = 1;
         break;
      case ConvTypes_valid:
         IOChan_Skip(cid);
         read0 = 1;
         if (n<127UL) {
            str[n] = ch;
            ++n;
         }
         else fit = 0;
         break;
      case ConvTypes_invalid:
         if (res==IOConsts_allRight || read0) {
            IOChan_SetReadResult(cid, IOConsts_wrongFormat);
         }
         return;
      case ConvTypes_terminator:
         goto loop_exit;
      default:
         X2C_TRAP(X2C_CASE_TRAP);
      } /* end switch */
   }
   loop_exit:;
   if (!fit) res = IOConsts_wrongFormat;
   else {
      str[n] = 0;
      RealStr_StrToReal(str, 128ul, real, &conv);
      switch ((unsigned)conv) {
      case ConvTypes_strAllRight:
         res = IOConsts_allRight;
         break;
      case ConvTypes_strOutOfRange:
         res = IOConsts_outOfRange;
         break;
      case ConvTypes_strWrongFormat:
         res = IOConsts_wrongFormat;
         break;
      default:
         X2C_TRAP(X2C_CASE_TRAP);
      } /* end switch */
   }
   IOChan_SetReadResult(cid, res);
} /* end ReadReal() */


static void write0(IOChan_ChanId cid, string str, X2C_CARD32 w)
{
   string fill;
   X2C_CARD32 n;
   n = X2C_LENGTH(str,128ul);
   if (w==0UL) w = 1UL;
   else if (n>=w) w = 0UL;
   else w -= n;
   if (w) {
      n = w;
      if (n>127UL) n = 127UL;
      do {
         --n;
         fill[n] = ' ';
      } while (n);
      n = w;
      if (n>=127UL) n = 126UL;
      do {
         if (n>w) n = w;
         w -= n;
         fill[n] = 0;
         TextIO_WriteString(cid, fill, 128ul);
      } while (w);
   }
   TextIO_WriteString(cid, str, 128ul);
} /* end write() */


extern void RealIO_WriteFloat(IOChan_ChanId cid, X2C_REAL real,
                X2C_CARD32 sigFigs, X2C_CARD32 width)
{
   string str;
   RealStr_RealToFloat(real, sigFigs, str, 128ul);
   write0(cid, str, width);
} /* end WriteFloat() */


extern void RealIO_WriteEng(IOChan_ChanId cid, X2C_REAL real,
                X2C_CARD32 sigFigs, X2C_CARD32 width)
{
   string str;
   RealStr_RealToEng(real, sigFigs, str, 128ul);
   write0(cid, str, width);
} /* end WriteEng() */


extern void RealIO_WriteFixed(IOChan_ChanId cid, X2C_REAL real,
                X2C_INT32 place, X2C_CARD32 width)
{
   string str;
   RealStr_RealToFixed(real, place, str, 128ul);
   write0(cid, str, width);
} /* end WriteFixed() */


static X2C_CARD32 digsFix(X2C_CHAR s[], X2C_CARD32 s_len)
{
   X2C_CARD32 c;
   X2C_CARD32 i;
   i = 0UL;
   c = 0UL;
   if (s[0UL]=='-') ++i;
   while (i<s_len-1 && (s[i]=='0' || s[i]=='.')) ++i;
   while (i<s_len-1 && s[i]) {
      if (s[i]!='.') ++c;
      ++i;
   }
   return c;
} /* end digsFix() */


static X2C_CARD32 digsFlt(X2C_CHAR s[], X2C_CARD32 s_len)
{
   X2C_CARD32 c;
   X2C_CARD32 i;
   i = 0UL;
   c = 0UL;
   if (s[0UL]=='-') ++i;
   while ((i<s_len-1 && s[i]) && s[i]!='E') {
      if (s[i]!='.') ++c;
      ++i;
   }
   return c;
} /* end digsFlt() */

#define RealIO_sigFigs 3


extern void RealIO_WriteReal(IOChan_ChanId cid, X2C_REAL real,
                X2C_CARD32 width)
{
   string fix;
   string str;
   X2C_CARD32 w;
   if ((X2C_REAL)fabs(real)>1.0f) {
      if (RealConv_LengthFixedReal(real, 3L)<=width) {
         RealStr_RealToFixed(real, 3L, str, 128ul);
      }
      else RealStr_RealToFloat(real, 3UL, str, 128ul);
      write0(cid, str, width);
   }
   else {
      w = width;
      if (real<0.0f) --w;
      RealStr_RealToFixed(real, (X2C_INT32)(w-2UL), fix, 128ul);
      RealStr_RealToFloat(real, w-2UL, str, 128ul);
      if (digsFix(fix, 128ul)>=digsFlt(str, 128ul)) write0(cid, fix, width);
      else write0(cid, str, width);
   }
} /* end WriteReal() */


extern void RealIO_BEGIN(void)
{
   static int RealIO_init = 0;
   if (RealIO_init) return;
   RealIO_init = 1;
   if (sizeof(string)!=128) X2C_ASSERT(0);
   RealConv_BEGIN();
   ConvTypes_BEGIN();
   CharClass_BEGIN();
   RealStr_BEGIN();
   IOConsts_BEGIN();
   TextIO_BEGIN();
   IOChan_BEGIN();
}

