#!/bin/bash
LIB=libpng-1.6.3.tgz

SRC_TARBALL=../../$LIB
BUILDDIR=`mktemp -d`
DESTPATH=`pwd`

HOSTARCH=$(uname -m | \
	sed -e s/arm64/aarch64/ \
	    -e s/armv8.*/aarch64/ \
	    -e s/armv9.*/aarch64/)

# if we are building on the host for the host and not cross-compiling
if [ "aarch64" = $HOSTARCH ] ; then
export CC=gcc
else
export CC=/opt/gcc-linaro-7.5.0-2019.12-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-gcc
fi

cp $SRC_TARBALL $BUILDDIR
pushd $BUILDDIR
tar -xf $LIB --strip-components=1
./configure --prefix=$BUILDDIR --host=arm-none-linux-gnueabi --with-zlib-prefix=$DESTPATH
make -j16
make install
popd
cp $BUILDDIR/lib/*.a .
cp $BUILDDIR/include/*.h .
echo $CFLAGS
rm -r -f $BUILDDIR
