#!/bin/bash
LIB=jpegsrc.v9.tar.gz

SRC_TARBALL=../../$LIB
BUILDDIR=`mktemp -d`

HOSTARCH=$(uname -m | \
	sed -e s/arm64/aarch64/ \
	    -e s/armv8.*/aarch64/ \
	    -e s/armv9.*/aarch64/)

# if we are building on the host for the host and not cross-compiling
if [ "aarch64" = $HOSTARCH ] ; then
export CC=gcc
export CFLAGS=""
else
export CC=/opt/gcc-linaro-7.5.0-2019.12-x86_64_arm-linux-gnueabihf/bin/arm-linux-gnueabihf-gcc
export CFLAGS="-march=armv7-a -mfpu=neon -mfloat-abi=hard"
fi

cp $SRC_TARBALL $BUILDDIR
pushd $BUILDDIR
tar -xf $LIB --strip-components=1
./configure --prefix=$BUILDDIR --host=arm-none-linux-gnueabi
make -j16
make install
popd
cp $BUILDDIR/lib/*.a .
cp $BUILDDIR/include/*.h .
rm -r -f $BUILDDIR
