#!/bin/bash
SRC_TARBALL=../../libpng-1.6.3.tgz
BUILDDIR=`mktemp -d`
DESTPATH=`pwd`

HOSTARCH=$(uname -m | \
	sed -e s/i.86/x86/ \
	    -e s/sun4u/sparc64/ \
	    -e s/arm.*/arm/ \
	    -e s/sa110/arm/ \
	    -e s/ppc64/powerpc/ \
	    -e s/ppc/powerpc/ \
	    -e s/macppc/powerpc/\
	    -e s/sh.*/sh/)

# if we are building on the host for the host and not cross-compiling
if [ "aarch64" = $HOSTARCH ] ; then
export CC=gcc
else
export CC=/opt/gcc-linaro-7.5.0-2019.12-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-gcc
fi

cp $SRC_TARBALL $BUILDDIR
pushd $BUILDDIR
tar -xf libpng-1.6.3.tgz
cd libpng-1.6.3
./configure --prefix=$BUILDDIR --host=arm-none-linux-gnueabi --with-zlib-prefix=$DESTPATH
make -j16
make install
popd
cp $BUILDDIR/lib/*.a .
cp $BUILDDIR/include/*.h .
echo $CFLAGS
rm -r -f $BUILDDIR

