#!/bin/bash
SRC_TARBALL=../../zlib-1.2.8.tar.gz
BUILDDIR=`mktemp -d`

HOSTARCH=$(uname -m | \
	sed -e s/i.86/x86/ \
	    -e s/sun4u/sparc64/ \
	    -e s/arm.*/arm/ \
	    -e s/sa110/arm/ \
	    -e s/ppc64/powerpc/ \
	    -e s/ppc/powerpc/ \
	    -e s/macppc/powerpc/\
	    -e s/sh.*/sh/)

# if we are building on the host for the host and not cross-compiling
if [ "aarch64" = $HOSTARCH ] ; then
export CC=gcc
else
export CC=/opt/gcc-linaro-7.5.0-2019.12-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-gcc
fi

export CFLAGS=""

cp $SRC_TARBALL $BUILDDIR
pushd $BUILDDIR
tar -xf zlib-1.2.8.tar.gz
cd zlib-1.2.8
./configure --prefix=$BUILDDIR
make -j16
make install
popd
cp $BUILDDIR/lib/*.a .
cp $BUILDDIR/include/*.h .
rm -r -f $BUILDDIR

