/* XDS v2.60: Copyright (c) 1999-2011 Excelsior, LLC. All Rights Reserved. */
/* "@(#)DStrings.c Feb  3 14:31:17 2012" */
/* Generated by XDS Oberon-2 to ANSI C v4.20 translator */

#define X2C_int32
#define X2C_index32
#ifndef DStrings_H_
#include "DStrings.h"
#endif
#define DStrings_C_

extern struct X2C_MD_STR DStrings_desc;

extern void DStrings_Assign(X2C_CHAR s[], X2C_CARD32 s_len,
                DStrings_String * d)
{
   X2C_INDEX tmp[1];
   X2C_NEW_OPEN(x2c_td_null,(X2C_ADDRESS*)d,1u,
                (tmp[0] = (size_t)(X2C_LENGTH(s,s_len)+1L),tmp),1u,0);
   X2C_COPY(s,s_len,(*d)->Adr,(*d)->Len0);
} /* end Assign() */


extern void DStrings_Append(X2C_CHAR s[], X2C_CARD32 s_len,
                DStrings_String * d)
{
   X2C_INT32 dlen;
   X2C_INT32 slen;
   X2C_INT32 i;
   DStrings_String n = 0;
   X2C_INDEX tmp[1];
   X2C_INT32 tmp0;
   if (*d==0) dlen = 0L;
   else dlen = X2C_LENGTH((*d)->Adr,(*d)->Len0);
   slen = X2C_LENGTH(s,s_len);
   if (dlen==0L) {
      X2C_NEW_OPEN(x2c_td_null,(X2C_ADDRESS*)d,1u,
                (tmp[0] = (size_t)(slen+1L),tmp),1u,0);
      X2C_COPY(s,s_len,(*d)->Adr,(*d)->Len0);
   }
   else {
      if (dlen+slen>=(*d)->Len0) {
         X2C_NEW_OPEN(x2c_td_null,(X2C_ADDRESS*) &n,1u,
                (tmp[0] = (size_t)(dlen+slen+1L),tmp),1u,0);
         X2C_COPY((*d)->Adr,(*d)->Len0,n->Adr,n->Len0);
         *d = n;
      }
      tmp0 = slen-1L;
      i = 0L;
      if (i<=tmp0) for (;; i++) {
         (*d)->Adr[dlen] = s[i];
         ++dlen;
         if (i==tmp0) break;
      } /* end for */
      (*d)->Adr[dlen] = 0x0U ;
   }
} /* end Append() */


static void * DStrings_offs[] = {
   X2C_OFS_END
};
static X2C_PROC DStrings_cmds[] = { 0 };
static X2C_CHAR * DStrings_cnms[] = { 0 };
struct X2C_MD_STR DStrings_desc = {
  0, 0, "DStrings",DStrings_offs,DStrings_cmds,DStrings_cnms,0
};

extern void DStrings_BEGIN(void)
{
   static int DStrings_init = 0;
   if (DStrings_init) return;
   DStrings_init = 1;
   X2C_MODULE(&DStrings_desc);
}

