/* XDS v2.60: Copyright (c) 1999-2011 Excelsior, LLC. All Rights Reserved. */
/* "@(#)POSIXIOChan.c Feb  3 14:31:19 2012" */
/* Generated by XDS Modula-2 to ANSI C v4.20 translator */

#define X2C_int32
#define X2C_index32
#ifndef POSIXIOChan_H_
#include "POSIXIOChan.h"
#endif
#define POSIXIOChan_C_
#ifndef IOChan_H_
#include "IOChan.h"
#endif
#ifndef ChanConsts_H_
#include "ChanConsts.h"
#endif
#ifndef xDevData_H_
#include "xDevData.h"
#endif
#ifndef IOLink_H_
#include "IOLink.h"
#endif
#ifndef xlibOS_H_
#include "xlibOS.h"
#endif

X2C_CARD8 POSIXIOChan_read = 0x1U;
X2C_CARD8 POSIXIOChan_write = 0x2U;
X2C_CARD8 POSIXIOChan_text = 0x8U;
X2C_CARD8 POSIXIOChan_raw = 0x10U;
static IOLink_DeviceId did;


extern X2C_ADDRESS POSIXIOChan_GetFilePtr(IOChan_ChanId cid)
{
   IOLink_DeviceTablePtr x;
   xDevData_DevData d;
   x = IOLink_DeviceTablePtrValue(cid, did, IOChan_notAvailable, "POSIXIOChan\
.GetFilePtr", 23ul);
   d = (xDevData_DevData)x->cd;
   return (X2C_ADDRESS)d->cf;
} /* end GetFilePtr() */


extern xDevData_FileName POSIXIOChan_GetFileName(IOChan_ChanId cid)
{
   IOLink_DeviceTablePtr x;
   xDevData_DevData d;
   x = IOLink_DeviceTablePtrValue(cid, did, IOChan_notAvailable, "POSIXIOChan\
.GetFileName", 24ul);
   d = (xDevData_DevData)x->cd;
   return d->name;
} /* end GetFileName() */


extern void POSIXIOChan_MakeChannel(IOChan_ChanId * cid, X2C_ADDRESS file,
                X2C_CHAR name[], X2C_CARD32 name_len, X2C_CARD8 flags,
                X2C_CARD8 * res)
{
   xDevData_FileName fn;
   X2C_PCOPY((void **)&name,name_len);
   IOLink_MakeChan(did, cid);
   if (*cid==IOChan_InvalidChan()) {
      *res = ChanConsts_outOfChans;
      goto label;
   }
   xDevData_MakeName(&fn, name, name_len, res);
   if (*res) {
      IOLink_UnMakeChan(did, cid);
      goto label;
   }
   xDevData_Open(IOLink_DeviceTablePtrValue(*cid, did, IOChan_notAvailable, "\
", 1ul), (X2C_OSFHANDLE)file, fn, flags, xDevData_bmDefault, res);
   if (*res) {
      IOLink_UnMakeChan(did, cid);
      xDevData_UnMakeName(&fn);
   }
   label:;
   X2C_PFREE(name);
} /* end MakeChannel() */


extern void POSIXIOChan_BEGIN(void)
{
   static int POSIXIOChan_init = 0;
   if (POSIXIOChan_init) return;
   POSIXIOChan_init = 1;
   IOLink_BEGIN();
   IOChan_BEGIN();
   ChanConsts_BEGIN();
   xDevData_BEGIN();
   xDevData_GetDID(&did);
}

