/* XDS v2.60: Copyright (c) 1999-2011 Excelsior, LLC. All Rights Reserved. */
/* "@(#)ProgramArgs.c Feb  3 14:31:18 2012" */
/* Generated by XDS Modula-2 to ANSI C v4.20 translator */

#define X2C_int32
#define X2C_index32
#ifndef ProgramArgs_H_
#include "ProgramArgs.h"
#endif
#define ProgramArgs_C_
#ifndef IOChan_H_
#include "IOChan.h"
#endif
#ifndef ChanConsts_H_
#include "ChanConsts.h"
#endif
#ifndef IOConsts_H_
#include "IOConsts.h"
#endif
#ifndef IOLink_H_
#include "IOLink.h"
#endif
#ifndef CharClass_H_
#include "CharClass.h"
#endif
#include "X2C.h"

typedef X2C_CHAR * StrPtr;

static IOLink_DeviceId did;

static IOChan_ChanId cid;

static X2C_CARD32 arg;

static X2C_CARD32 pos;

static X2C_CARD32 len;

static StrPtr ptr;

static StrPtr * args;

static X2C_CARD32 argc;

static X2C_BOOLEAN init;

static void Look(IOLink_DeviceTablePtr, X2C_CHAR *, X2C_CARD8 *);


static void Look(IOLink_DeviceTablePtr x, X2C_CHAR * ch, X2C_CARD8 * res)
{
   *res = IOConsts_allRight;
   if (pos>len) {
      if (arg>=argc-1UL) *res = IOConsts_endOfInput;
      else {
         ++arg;
         ptr = args[arg];
         pos = 0UL;
         len = X2C_LENGTH(ptr,4096ul);
         *ch = ptr[pos];
      }
   }
   else if (pos==len) *ch = ' ';
   else *ch = ptr[pos];
} /* end Look() */


static void Read(IOLink_DeviceTablePtr x, X2C_CHAR * ch, X2C_CARD8 * res)
{
   Look(x, ch, res);
   if (*res==IOConsts_allRight) ++pos;
} /* end Read() */

static void Skip(IOLink_DeviceTablePtr);


static void Skip(IOLink_DeviceTablePtr x)
{
   X2C_CHAR ch;
   X2C_CARD8 res;
   Read(x, &ch, &res);
   if (res==IOConsts_allRight) x->result = IOConsts_allRight;
   else {
      IOLink_RAISEdevException(cid, did, IOChan_skipAtEnd,
                "ProgramArgs.Skip", 17ul);
   }
} /* end Skip() */

static void SkipLook(IOLink_DeviceTablePtr, X2C_CHAR *, X2C_CARD8 *);


static void SkipLook(IOLink_DeviceTablePtr x, X2C_CHAR * ch,
                X2C_CARD8 * res)
{
   Skip(x);
   Look(x, ch, res);
} /* end SkipLook() */

static void TextRead(IOLink_DeviceTablePtr, X2C_ADDRESS, X2C_CARD32,
                X2C_CARD32 *);


static void TextRead(IOLink_DeviceTablePtr x, X2C_ADDRESS a, X2C_CARD32 n,
                X2C_CARD32 * locs)
{
   StrPtr p;
   X2C_CARD32 i;
   X2C_CARD8 res;
   p = (StrPtr)a;
   i = 0UL;
   for (;;) {
      if (i>=n) break;
      Read(x, &p[i], &res);
      if (res!=IOConsts_allRight) break;
      ++i;
   }
   *locs = i;
   if (n>0UL && i==0UL) x->result = IOConsts_endOfInput;
   else x->result = IOConsts_allRight;
} /* end TextRead() */

static void look(IOLink_DeviceTablePtr, X2C_CHAR *, X2C_CARD8 *);


static void look(IOLink_DeviceTablePtr x, X2C_CHAR * c, X2C_CARD8 * r)
{
   IOLink_RAISEdevException(x->cid, x->did, IOChan_notAvailable, "ProgramArgs\
.Look", 17ul);
} /* end look() */

static void skip(IOLink_DeviceTablePtr);


static void skip(IOLink_DeviceTablePtr x)
{
   IOLink_RAISEdevException(x->cid, x->did, IOChan_notAvailable, "ProgramArgs\
.Skip", 17ul);
} /* end skip() */

static void read0(IOLink_DeviceTablePtr, X2C_ADDRESS, X2C_CARD32,
                X2C_CARD32 *);


static void read0(IOLink_DeviceTablePtr x, X2C_ADDRESS a, X2C_CARD32 max0,
                X2C_CARD32 * n)
{
   IOLink_RAISEdevException(x->cid, x->did, IOChan_notAvailable, "ProgramArgs\
.Read", 17ul);
} /* end read() */


static void Ini(void)
{
   IOLink_DeviceTablePtr x;
   args = (StrPtr *)X2C_argv;
   argc = (X2C_CARD32)X2C_argc;
   x = IOLink_DeviceTablePtrValue(cid, did, IOChan_notAvailable, "", 1ul);
   arg = 1UL;
   if (arg<argc) {
      x->flags = 0x9U;
      x->doLook = Look;
      x->doSkip = Skip;
      x->doSkipLook = SkipLook;
      x->doTextRead = TextRead;
      ptr = args[arg];
      pos = 0UL;
      len = X2C_LENGTH(ptr,4096ul);
   }
} /* end Ini() */


extern IOChan_ChanId ProgramArgs_ArgChan(void)
{
   if (init) {
      Ini();
      init = 0;
   }
   return cid;
} /* end ArgChan() */


extern X2C_BOOLEAN ProgramArgs_IsArgPresent(void)
{
   IOLink_DeviceTablePtr x;
   X2C_CHAR ch;
   X2C_CARD8 res;
   if (init) {
      Ini();
      init = 0;
   }
   x = IOLink_DeviceTablePtrValue(cid, did, IOChan_notAvailable, "", 1ul);
   Look(x, &ch, &res);
   while (res==IOConsts_allRight && CharClass_IsWhiteSpace(ch)) {
      Skip(x);
      Look(x, &ch, &res);
   }
   return res==IOConsts_allRight;
} /* end IsArgPresent() */


extern void ProgramArgs_NextArg(void)
{
   IOLink_DeviceTablePtr x;
   if (init) {
      Ini();
      init = 0;
   }
   if (arg>=argc-1UL) {
      x = IOLink_DeviceTablePtrValue(cid, did, IOChan_notAvailable, "", 1ul);
      x->flags &= ~0x1U;
      x->result = IOConsts_endOfInput;
      x->doLook = look;
      x->doSkip = skip;
      x->doSkipLook = look;
      x->doTextRead = read0;
   }
   else {
      ++arg;
      ptr = args[arg];
      pos = 0UL;
      len = X2C_LENGTH(ptr,4096ul);
   }
} /* end NextArg() */


extern void ProgramArgs_BEGIN(void)
{
   static int ProgramArgs_init = 0;
   if (ProgramArgs_init) return;
   ProgramArgs_init = 1;
   CharClass_BEGIN();
   ChanConsts_BEGIN();
   IOConsts_BEGIN();
   IOLink_BEGIN();
   IOChan_BEGIN();
   init = 1;
   arg = 0UL;
   pos = 0UL;
   len = 0UL;
   IOLink_AllocateDeviceId(&did);
   IOLink_MakeChan(did, &cid);
}

