/* XDS v2.60: Copyright (c) 1999-2011 Excelsior, LLC. All Rights Reserved. */
/* "@(#)SLongIO.c Feb  3 14:31:18 2012" */
/* Generated by XDS Modula-2 to ANSI C v4.20 translator */

#define X2C_int32
#define X2C_index32
#ifndef SLongIO_H_
#include "SLongIO.h"
#endif
#define SLongIO_C_
#ifndef LongIO_H_
#include "LongIO.h"
#endif
#ifndef StdChans_H_
#include "StdChans.h"
#endif


extern void SLongIO_ReadReal(X2C_LONGREAL * real)
{
   LongIO_ReadReal(StdChans_InChan(), real);
} /* end ReadReal() */


extern void SLongIO_WriteFloat(X2C_LONGREAL real, X2C_CARD32 sigFigs,
                X2C_CARD32 width)
{
   LongIO_WriteFloat(StdChans_OutChan(), real, sigFigs, width);
} /* end WriteFloat() */


extern void SLongIO_WriteEng(X2C_LONGREAL real, X2C_CARD32 sigFigs,
                X2C_CARD32 width)
{
   LongIO_WriteEng(StdChans_OutChan(), real, sigFigs, width);
} /* end WriteEng() */


extern void SLongIO_WriteFixed(X2C_LONGREAL real, X2C_INT32 place,
                X2C_CARD32 width)
{
   LongIO_WriteFixed(StdChans_OutChan(), real, place, width);
} /* end WriteFixed() */


extern void SLongIO_WriteReal(X2C_LONGREAL real, X2C_CARD32 width)
{
   LongIO_WriteReal(StdChans_OutChan(), real, width);
} /* end WriteReal() */


extern void SLongIO_BEGIN(void)
{
   static int SLongIO_init = 0;
   if (SLongIO_init) return;
   SLongIO_init = 1;
   StdChans_BEGIN();
   LongIO_BEGIN();
}

