/* XDS v2.60: Copyright (c) 1999-2011 Excelsior, LLC. All Rights Reserved. */
/* "@(#)TimeConv.c Feb  3 14:31:18 2012" */
/* Generated by XDS Modula-2 to ANSI C v4.20 translator */

#define X2C_int32
#define X2C_index32
#ifndef TimeConv_H_
#include "TimeConv.h"
#endif
#define TimeConv_C_
#ifndef SysClock_H_
#include "SysClock.h"
#endif

#define TimeConv_y001days 365

#define TimeConv_y004days 1461

#define TimeConv_y100days 36524

#define TimeConv_y400days 146097

static X2C_CARD32 TimeConv_monthAdd[12] = {0UL,3UL,3UL,6UL,8UL,11UL,13UL,
                16UL,19UL,21UL,24UL,26UL};

static X2C_CARD32 TimeConv_monthLast[12] = {31UL,59UL,90UL,120UL,151UL,181UL,
                212UL,243UL,273UL,304UL,334UL,365UL};

static X2C_CARD32 FirstValidYear;


static X2C_BOOLEAN is_leap(X2C_CARD32 y)
{
   return (y&3UL)==0UL && y%100UL || y%400UL==0UL;
} /* end is_leap() */

static X2C_CARD32 _cnst[12] = {0UL,3UL,3UL,6UL,8UL,11UL,13UL,16UL,19UL,21UL,
                24UL,26UL};

static X2C_CARD32 day_of_year(X2C_CARD32 y, X2C_CARD32 m, X2C_CARD32 d)
{
   X2C_CARD32 x;
   --m;
   x = d+m*28UL+_cnst[m];
   if (m>=2UL && is_leap(y)) ++x;
   return x;
} /* end day_of_year() */


static X2C_CARD32 the_day(X2C_CARD32 y, X2C_CARD32 m, X2C_CARD32 d)
{
   X2C_CARD32 year;
   X2C_CARD32 day;
   year = y;
   y -= FirstValidYear;
   day = (y/400UL)*146097UL;
   y = y%400UL;
   day += (y/100UL)*36524UL;
   y = y%100UL;
   day += (y/4UL)*1461UL;
   day += (y&3UL)*365UL;
   day += day_of_year(year, m, d);
   return day;
} /* end the_day() */


static X2C_CARD32 sub_days(struct SysClock_DateTime g,
                struct SysClock_DateTime l)
{
   X2C_CARD32 c;
   c = ((l.year-FirstValidYear)/400UL)*400UL;
   g.year = g.year-c;
   l.year = l.year-c;
   return the_day(g.year, g.month, g.day)-the_day(l.year, l.month, l.day);
} /* end sub_days() */


static X2C_CARD32 day_sec(X2C_CARD32 h, X2C_CARD32 m, X2C_CARD32 s)
{
   return s+m*60UL+h*3600UL;
} /* end day_sec() */


static X2C_CARD32 sub_secs(const struct SysClock_DateTime g,
                const struct SysClock_DateTime l)
{
   X2C_CARD32 days;
   days = sub_days(g, l);
   return (days*86400UL+day_sec(g.hour, g.minute, g.second))-day_sec(l.hour,
                l.minute, l.second);
} /* end sub_secs() */

static X2C_CARD32 _cnst0[12] = {31UL,59UL,90UL,120UL,151UL,181UL,212UL,243UL,
                273UL,304UL,334UL,365UL};

static void unpack_day(X2C_CARD32 day, X2C_CARD32 * y, X2C_CARD32 * m,
                X2C_CARD32 * d)
{
   X2C_CARD32 i;
   X2C_BOOLEAN leap;
   --day;
   *y = 400UL*(day/146097UL);
   day = day%146097UL;
   i = day/36524UL;
   if (i==4UL) i = 3UL;
   *y += i*100UL;
   day -= i*36524UL;
   i = day/1461UL;
   day -= i*1461UL;
   *y += i*4UL;
   i = day/365UL;
   if (i==4UL) i = 3UL;
   *y += i;
   day -= i*365UL;
   leap = is_leap(*y+FirstValidYear);
   ++day;
   *m = day/32UL;
   day -= (X2C_CARD32)(leap && day>31UL);
   while (*m<=11UL && day>_cnst0[*m]) ++*m;
   *d = day;
   if (*m>0UL) *d -= _cnst0[*m-1UL];
   ++*m;
   *d += (X2C_CARD32)(leap && *m==2UL);
} /* end unpack_day() */


static void add_days(X2C_CARD32 * y, X2C_CARD32 * m, X2C_CARD32 * d,
                X2C_CARD32 days)
{
   X2C_CARD32 cy400s;
   cy400s = (*y-FirstValidYear)/400UL;
   *y -= cy400s*400UL;
   cy400s += days/146097UL;
   days = days%146097UL;
   unpack_day(days+the_day(*y, *m, *d), y, m, d);
   *y = *y+cy400s*400UL+FirstValidYear;
} /* end add_days() */


static void add_secs(X2C_CARD32 * y, X2C_CARD32 * m, X2C_CARD32 * d,
                X2C_CARD32 * h, X2C_CARD32 * mi, X2C_CARD32 * s,
                X2C_CARD32 secs)
{
   X2C_CARD32 days;
   secs += day_sec(*h, *mi, *s);
   days = secs/86400UL;
   secs = secs%86400UL;
   add_days(y, m, d, days);
   *h = secs/3600UL;
   secs = secs%3600UL;
   *mi = secs/60UL;
   *s = secs%60UL;
} /* end add_secs() */


extern X2C_INT32 TimeConv_Compare(struct SysClock_DateTime dl,
                struct SysClock_DateTime dr)
{
   X2C_INT32 r;
   if (!(SysClock_IsValidDateTime(dl) && SysClock_IsValidDateTime(dr))) {
      return 0L;
   }
   r = (X2C_INT32)dl.year-(X2C_INT32)dr.year;
   if (r) return r;
   r = (X2C_INT32)dl.month-(X2C_INT32)dr.month;
   if (r) return r;
   r = (X2C_INT32)dl.day-(X2C_INT32)dr.day;
   if (r) return r;
   r = (X2C_INT32)dl.hour-(X2C_INT32)dr.hour;
   if (r) return r;
   r = (X2C_INT32)dl.minute-(X2C_INT32)dr.minute;
   if (r) return r;
   r = (X2C_INT32)dl.second-(X2C_INT32)dr.second;
   if (r) return r;
   return (X2C_INT32)dl.fractions-(X2C_INT32)dr.fractions;
} /* end Compare() */


extern X2C_CARD32 TimeConv_SubDateDays(struct SysClock_DateTime dl,
                struct SysClock_DateTime dr)
{
   X2C_INT32 r;
   if (!(SysClock_IsValidDateTime(dl) && SysClock_IsValidDateTime(dr))) {
      return 0UL;
   }
   r = TimeConv_Compare(dl, dr);
   if (r<=0L) return 0UL;
   return sub_days(dl, dr);
} /* end SubDateDays() */


extern X2C_CARD32 TimeConv_SubDateSecs(struct SysClock_DateTime dl,
                struct SysClock_DateTime dr)
{
   X2C_INT32 r;
   if (!(SysClock_IsValidDateTime(dl) && SysClock_IsValidDateTime(dr))) {
      return 0UL;
   }
   r = TimeConv_Compare(dl, dr);
   if (r<=0L) return 0UL;
   return sub_secs(dl, dr);
} /* end SubDateSecs() */

static struct SysClock_DateTime FirstDate;

static struct SysClock_DateTime SysFirstDate;


extern void TimeConv_AddDateDays(struct SysClock_DateTime D, X2C_CARD32 days,
                 struct SysClock_DateTime * res)
{
   X2C_CARD32 d0;
   X2C_CARD32 m;
   X2C_CARD32 y;
   *res = FirstDate;
   if (!SysClock_IsValidDateTime(D)) return;
   y = D.year;
   m = D.month;
   d0 = D.day;
   add_days(&y, &m, &d0, days);
   *res = D;
   res->year = y;
   res->month = m;
   res->day = d0;
} /* end AddDateDays() */


extern void TimeConv_AddDateSecs(struct SysClock_DateTime D, X2C_CARD32 secs,
                 struct SysClock_DateTime * res)
{
   X2C_CARD32 s;
   X2C_CARD32 mi;
   X2C_CARD32 h;
   X2C_CARD32 d0;
   X2C_CARD32 m;
   X2C_CARD32 y;
   *res = FirstDate;
   if (!SysClock_IsValidDateTime(D)) return;
   y = D.year;
   m = D.month;
   d0 = D.day;
   h = D.hour;
   mi = D.minute;
   s = D.second;
   add_secs(&y, &m, &d0, &h, &mi, &s, secs);
   res->year = y;
   res->month = m;
   res->day = d0;
   res->hour = h;
   res->minute = mi;
   res->second = s;
   res->fractions = D.fractions;
   res->zone = D.zone;
   res->SummerTimeFlag = D.SummerTimeFlag;
} /* end AddDateSecs() */


extern X2C_CARD32 TimeConv_TheDayNumber(struct SysClock_DateTime d)
{
   if (!SysClock_IsValidDateTime(d)) return 0UL;
   return the_day(d.year, d.month, d.day);
} /* end TheDayNumber() */


extern X2C_CARD32 TimeConv_WeekDay(struct SysClock_DateTime d)
{
   return TimeConv_TheDayNumber(d)%7UL;
} /* end WeekDay() */


extern X2C_CARD32 TimeConv_TheFractionNumber(struct SysClock_DateTime d)
{
   X2C_CARD32 r;
   if (!SysClock_IsValidDateTime(d)) return 0UL;
   r = d.hour*3600UL+d.minute*60UL+d.second;
   return r*100UL+d.fractions;
} /* end TheFractionNumber() */


extern X2C_CARD32 TimeConv_time(void)
{
   struct SysClock_DateTime c;
   if (!SysClock_CanGetClock()) return 0UL;
   SysClock_GetClock(&c);
   return TimeConv_SubDateSecs(c, SysFirstDate);
} /* end time() */


extern X2C_CARD32 TimeConv_millisecs(void)
{
   struct SysClock_DateTime c;
   X2C_CARD32 r;
   if (!SysClock_CanGetClock()) return 0UL;
   SysClock_GetClock(&c);
   r = c.hour*3600UL+c.minute*60UL+c.second;
   return (r*100UL+c.fractions)*10UL;
} /* end millisecs() */


extern void TimeConv_unpack(struct SysClock_DateTime * d, X2C_CARD32 secs)
{
   TimeConv_AddDateSecs(SysFirstDate, secs, d);
} /* end unpack() */


extern void TimeConv_pack(struct SysClock_DateTime d, X2C_CARD32 * secs)
{
   X2C_INT32 r;
   *secs = 0UL;
   if (!SysClock_IsValidDateTime(d)) return;
   r = TimeConv_Compare(d, SysFirstDate);
   if (r<=0L) return;
   d.zone = 0L;
   d.fractions = 0UL;
   d.SummerTimeFlag = 0;
   *secs = TimeConv_SubDateSecs(d, SysFirstDate);
} /* end pack() */


extern X2C_CARD32 TimeConv_weekday0(X2C_CARD32 time0)
{
   struct SysClock_DateTime d;
   TimeConv_unpack(&d, time0);
   return TimeConv_WeekDay(d);
} /* end weekday() */


extern void TimeConv_BEGIN(void)
{
   static int TimeConv_init = 0;
   if (TimeConv_init) return;
   TimeConv_init = 1;
   SysClock_BEGIN();
   FirstDate.month = 1UL;
   FirstDate.day = 1UL;
   FirstDate.hour = 0UL;
   FirstDate.minute = 0UL;
   FirstDate.second = 0UL;
   FirstDate.fractions = 0UL;
   FirstDate.zone = 0L;
   FirstDate.SummerTimeFlag = 0;
   FirstValidYear = 0UL;
   FirstDate.year = FirstValidYear;
   if (!SysClock_IsValidDateTime(FirstDate)) {
      FirstValidYear = 1UL;
      FirstDate.year = FirstValidYear;
   }
   SysFirstDate.year = 1970UL;
   SysFirstDate.month = 1UL;
   SysFirstDate.day = 1UL;
   SysFirstDate.hour = 0UL;
   SysFirstDate.minute = 0UL;
   SysFirstDate.second = 0UL;
   SysFirstDate.fractions = 0UL;
   SysFirstDate.zone = 0L;
   SysFirstDate.SummerTimeFlag = 0;
}

