/* XDS v2.60: Copyright (c) 1999-2011 Excelsior, LLC. All Rights Reserved. */
/* "@(#)WholeIO.c Feb  3 14:31:18 2012" */
/* Generated by XDS Modula-2 to ANSI C v4.20 translator */

#define X2C_int32
#define X2C_index32
#ifndef WholeIO_H_
#include "WholeIO.h"
#endif
#define WholeIO_C_
#ifndef IOChan_H_
#include "IOChan.h"
#endif
#ifndef IOConsts_H_
#include "IOConsts.h"
#endif
#ifndef TextIO_H_
#include "TextIO.h"
#endif
#ifndef WholeStr_H_
#include "WholeStr.h"
#endif
#ifndef ConvTypes_H_
#include "ConvTypes.h"
#endif
#ifndef WholeConv_H_
#include "WholeConv.h"
#endif

#define WholeIO_ok IOConsts_allRight


extern void WholeIO_ReadInt(IOChan_ChanId cid, X2C_INT32 * int0)
{
   ConvTypes_ScanState state;
   X2C_CARD8 class0;
   X2C_CARD8 res;
   X2C_CHAR ch;
   X2C_BOOLEAN read0;
   X2C_BOOLEAN ovfl;
   X2C_BOOLEAN neg;
   X2C_CARD32 ord;
   X2C_CARD32 n;
   neg = 0;
   ovfl = 0;
   read0 = 0;
   n = 0UL;
   state = (ConvTypes_ScanState)WholeConv_ScanInt;
   for (;;) {
      IOChan_Look(cid, &ch, &res);
      if (res!=IOConsts_allRight) ch = 0;
      state(ch, &class0, (X2C_PROC *) &state);
      switch ((unsigned)class0) {
      case ConvTypes_padding:
         IOChan_Skip(cid);
         read0 = 1;
         break;
      case ConvTypes_valid:
         IOChan_Skip(cid);
         read0 = 1;
         if (ch=='-' || ch=='+') neg = ch=='-';
         else if (!ovfl) {
            ord = (X2C_CARD32)(X2C_CARD8)ch-48UL;
            if (n>(X2C_max_longcard-ord)/10UL) {
               ovfl = 1;
               if (neg) *int0 = X2C_min_longint;
               else *int0 = X2C_max_longint;
            }
            else n = n*10UL+ord;
         }
         break;
      case ConvTypes_invalid:
         if (read0 || res==IOConsts_allRight) {
            IOChan_SetReadResult(cid, IOConsts_wrongFormat);
         }
         return;
      case ConvTypes_terminator:
         goto loop_exit;
      default:
         X2C_TRAP(X2C_CASE_TRAP);
      } /* end switch */
   }
   loop_exit:;
   res = IOConsts_allRight;
   if (ovfl) res = IOConsts_outOfRange;
   else if (neg) {
      if (n>0x080000000UL) res = IOConsts_outOfRange;
      else if (n==0x080000000UL) *int0 = X2C_min_longint;
      else *int0 = -(X2C_INT32)n;
   }
   else if (n>2147483647UL) res = IOConsts_outOfRange;
   else *int0 = (X2C_INT32)n;
   IOChan_SetReadResult(cid, res);
} /* end ReadInt() */


extern void WholeIO_ReadCard(IOChan_ChanId cid, X2C_CARD32 * card)
{
   ConvTypes_ScanState state;
   X2C_CARD8 class0;
   X2C_CARD8 res;
   X2C_CHAR ch;
   X2C_BOOLEAN read0;
   X2C_BOOLEAN ovfl;
   X2C_CARD32 ord;
   X2C_CARD32 n;
   ovfl = 0;
   read0 = 0;
   n = 0UL;
   state = (ConvTypes_ScanState)WholeConv_ScanCard;
   for (;;) {
      IOChan_Look(cid, &ch, &res);
      if (res!=IOConsts_allRight) ch = 0;
      state(ch, &class0, (X2C_PROC *) &state);
      switch ((unsigned)class0) {
      case ConvTypes_padding:
         IOChan_Skip(cid);
         read0 = 1;
         break;
      case ConvTypes_valid:
         IOChan_Skip(cid);
         read0 = 1;
         if (!ovfl) {
            ord = (X2C_CARD32)(X2C_CARD8)ch-48UL;
            if (n>(X2C_max_longcard-ord)/10UL) {
               ovfl = 1;
               *card = X2C_max_longcard;
            }
            else n = n*10UL+ord;
         }
         break;
      case ConvTypes_invalid:
         if (read0 || res==IOConsts_allRight) {
            IOChan_SetReadResult(cid, IOConsts_wrongFormat);
         }
         return;
      case ConvTypes_terminator:
         goto loop_exit;
      default:
         X2C_TRAP(X2C_CASE_TRAP);
      } /* end switch */
   }
   loop_exit:;
   res = IOConsts_allRight;
   if (ovfl) res = IOConsts_outOfRange;
   else {
      *card = n;
      res = IOConsts_allRight;
   }
   IOChan_SetReadResult(cid, res);
} /* end ReadCard() */


extern void WholeIO_WriteInt(IOChan_ChanId cid, X2C_INT32 int0,
                X2C_CARD32 width)
{
   X2C_CHAR a[32];
   X2C_CARD32 len;
   WholeStr_IntToStr(int0, a, 32ul);
   len = X2C_LENGTH(a,32ul);
   if (width==0UL) TextIO_WriteChar(cid, ' ');
   else {
      while (width>len) {
         TextIO_WriteChar(cid, ' ');
         --width;
      }
   }
   TextIO_WriteString(cid, a, 32ul);
} /* end WriteInt() */


extern void WholeIO_WriteCard(IOChan_ChanId cid, X2C_CARD32 card,
                X2C_CARD32 width)
{
   X2C_CHAR a[32];
   X2C_CARD32 len;
   WholeStr_CardToStr(card, a, 32ul);
   len = X2C_LENGTH(a,32ul);
   if (width==0UL) TextIO_WriteChar(cid, ' ');
   else {
      while (width>len) {
         TextIO_WriteChar(cid, ' ');
         --width;
      }
   }
   TextIO_WriteString(cid, a, 32ul);
} /* end WriteCard() */


extern void WholeIO_BEGIN(void)
{
   static int WholeIO_init = 0;
   if (WholeIO_init) return;
   WholeIO_init = 1;
   ConvTypes_BEGIN();
   WholeConv_BEGIN();
   IOConsts_BEGIN();
   WholeStr_BEGIN();
   TextIO_BEGIN();
   IOChan_BEGIN();
}

