/* XDS v2.60: Copyright (c) 1999-2011 Excelsior, LLC. All Rights Reserved. */
/* "@(#)xDevData.c Feb  3 14:31:19 2012" */
/* Generated by XDS Modula-2 to ANSI C v4.20 translator */

#define X2C_int32
#define X2C_index32
#ifndef xDevData_H_
#include "xDevData.h"
#endif
#define xDevData_C_
#ifndef IOLink_H_
#include "IOLink.h"
#endif
#ifndef IOChan_H_
#include "IOChan.h"
#endif
#ifndef IOConsts_H_
#include "IOConsts.h"
#endif
#ifndef ChanConsts_H_
#include "ChanConsts.h"
#endif
#ifndef xrInt64_H_
#include "xrInt64.h"
#endif
#ifndef xlibOS_H_
#include "xlibOS.h"
#endif
#ifndef xmRTS_H_
#include "xmRTS.h"
#endif
#ifndef platform_H_
#include "platform.h"
#endif
#ifndef M2EXCEPTION_H_
#include "M2EXCEPTION.h"
#endif



static X2C_CHAR xDevData_LF = '\012';

#define xDevData_SEP0 "\012"

#define xDevData_SEP1 ""

#define xDevData_tag_modf 0

#define xDevData_tag_rnd 1

#define xDevData_tag_lbuf 2

typedef X2C_CHAR Str10[10];


static void word2str(Str10 s, X2C_WORD v)
{
   X2C_CARD32 ch;
   X2C_CARD32 p;
   X2C_CARD32 x;
   X2C_WORD tmp;
   v = (X2C_LOC *)memcpy(tmp,v,4u);
   x = *(X2C_CARD32 *)v;
   s[9U] = 0;
   s[8U] = 'H';
   for (p = 7UL;; p--) {
      ch = x&15UL;
      x = x/16UL;
      if (ch>9UL) s[p] = (X2C_CHAR)((ch-10UL)+65UL);
      else s[p] = (X2C_CHAR)(ch+48UL);
      if (p==0UL) break;
   } /* end for */
} /* end word2str() */


extern void xDevData_HardError(IOLink_DeviceTablePtr x, X2C_WORD res)
{
   Str10 msg;
   X2C_WORD tmp;
   res = (X2C_LOC *)memcpy(tmp,res,4u);
   x->errNum = *(X2C_INT32 *)res;
   word2str(msg, res);
   IOLink_RAISEdevException(x->cid, x->did, IOChan_hardDeviceError, msg,
                10ul);
} /* end HardError() */


extern void xDevData_SoftError(IOLink_DeviceTablePtr x, X2C_WORD res)
{
   Str10 msg;
   X2C_WORD tmp;
   res = (X2C_LOC *)memcpy(tmp,res,4u);
   x->errNum = *(X2C_INT32 *)res;
   word2str(msg, res);
   IOLink_RAISEdevException(x->cid, x->did, IOChan_softDeviceError, msg,
                10ul);
} /* end SoftError() */


extern void xDevData_MakeName(xDevData_FileName * fn, X2C_CHAR name[],
                X2C_CARD32 name_len, X2C_CARD8 * res)
{
   X2C_INDEX tmp[1];
   X2C_DYNALLOCATE((X2C_ADDRESS*)fn,1u,(tmp[0] = X2C_LENGTH(name,
                name_len)+1UL,tmp),1u);
   if (*fn==0) *res = ChanConsts_outOfChans;
   else {
      X2C_COPY(name,name_len,(*fn)->Adr,(*fn)->Len0);
      *res = ChanConsts_opened;
   }
} /* end MakeName() */


extern void xDevData_UnMakeName(xDevData_FileName * fn)
{
   if (*fn) {
      X2C_DYNDEALLOCATE((X2C_ADDRESS*)fn);
      *fn = 0;
   }
} /* end UnMakeName() */


static void lock0(xDevData_DevData f)
{
} /* end lock() */


static void unlock0(xDevData_DevData f)
{
} /* end unlock() */

static X2C_INT32 dWrite(xDevData_DevData, X2C_ADDRESS, X2C_CARD32,
                X2C_CARD32 *);


static X2C_INT32 dWrite(xDevData_DevData x, X2C_ADDRESS a, X2C_CARD32 size,
                X2C_CARD32 * wr)
{
   return X2C_fWrite(x->cf, a, size, wr);
} /* end dWrite() */

static X2C_INT32 dRead(xDevData_DevData, X2C_ADDRESS, X2C_CARD32,
                X2C_CARD32 *);


static X2C_INT32 dRead(xDevData_DevData x, X2C_ADDRESS a, X2C_CARD32 size,
                X2C_CARD32 * rd)
{
   return X2C_fRead(x->cf, a, size, rd);
} /* end dRead() */

static X2C_INT32 dFlush(xDevData_DevData);


static X2C_INT32 dFlush(xDevData_DevData x)
{
   return 0L;
} /* end dFlush() */

static X2C_INT32 bWrite(xDevData_DevData, X2C_ADDRESS, X2C_CARD32,
                X2C_CARD32 *);


static X2C_INT32 bWrite(xDevData_DevData f, X2C_ADDRESS a, X2C_CARD32 size,
                X2C_CARD32 * wr)
{
   X2C_CHAR ch;
   X2C_INT32 res;
   X2C_CARD32 l;
   *wr = size;
   if (size==0UL) return 0L;
   if (f->bpos<256UL) {
      do {
         ch = *(X2C_CHAR *)a;
         f->buf[f->bpos] = (X2C_LOC)(X2C_CARD8)ch;
         ++f->bpos;
         --size;
         a = (X2C_ADDRESS)((X2C_ADDRESS)a+(X2C_INT32)1UL);
      } while (!(size==0UL || f->bpos>=256UL));
      f->tags |= 0x1UL;
      if (f->blen<f->bpos) f->blen = f->bpos;
   }
   if (size==0UL) return 0L;
   res = f->flush(f);
   if (res) {
      *wr = 0UL;
      return res;
   }
   while (size>256UL) {
      res = X2C_fWrite(f->cf, a, 256UL, &l);
      a = (X2C_ADDRESS)((X2C_ADDRESS)a+(X2C_INT32)l);
      size -= l;
      if (res) {
         *wr -= size;
         return res;
      }
   }
   if ((0x2UL & f->tags)) {
      res = X2C_fTell(f->cf, &f->spos);
      if (res) return res;
   }
   l = 0UL;
   do {
      ch = *(X2C_CHAR *)a;
      f->buf[l] = (X2C_LOC)(X2C_CARD8)ch;
      ++l;
      --size;
      a = (X2C_ADDRESS)((X2C_ADDRESS)a+(X2C_INT32)1UL);
   } while (size);
   f->tags |= 0x1UL;
   f->bpos = l;
   f->blen = l;
   return 0L;
} /* end bWrite() */

static X2C_INT32 bRead(xDevData_DevData, X2C_ADDRESS, X2C_CARD32,
                X2C_CARD32 *);


static X2C_INT32 bRead(xDevData_DevData f, X2C_ADDRESS a, X2C_CARD32 size,
                X2C_CARD32 * rd)
{
   X2C_CARD32 sz;
   X2C_CARD32 rr;
   X2C_INT32 res;
   *rd = size;
   if (size==0UL) return 0L;
   while (size>0UL && f->bpos<f->blen) {
      *(X2C_LOC *)a = f->buf[f->bpos];
      a = (X2C_ADDRESS)((X2C_ADDRESS)a+(X2C_INT32)1UL);
      ++f->bpos;
      --size;
   }
   if (size==0UL) return 0L;
   res = f->flush(f);
   if (res) return res;
   if (size>256UL) {
      sz = size-(size&255UL);
      res = X2C_fRead(f->cf, a, sz, &rr);
      a = (X2C_ADDRESS)((X2C_ADDRESS)a+(X2C_INT32)rr);
      size -= rr;
      if (res || rr!=sz) {
         *rd -= size;
         return res;
      }
   }
   if ((0x2UL & f->tags)) {
      res = X2C_fTell(f->cf, &f->spos);
      if (res) {
         *rd -= size;
         return res;
      }
   }
   res = X2C_fRead(f->cf, (X2C_ADDRESS)f->buf, 256UL, &f->blen);
   if (res==0L) {
      f->bpos = 0UL;
      while (size>0UL && f->bpos<f->blen) {
         *(X2C_LOC *)a = f->buf[f->bpos];
         a = (X2C_ADDRESS)((X2C_ADDRESS)a+(X2C_INT32)1UL);
         --size;
         ++f->bpos;
      }
   }
   *rd -= size;
   return res;
} /* end bRead() */

static X2C_INT32 bFlush(xDevData_DevData);


static X2C_INT32 bFlush(xDevData_DevData x)
{
   X2C_INT32 res;
   X2C_CARD32 wr;
   if ((0x1UL & x->tags)) {
      if ((0x2UL & x->tags)) {
         res = X2C_fSeek(x->cf, &x->spos, 0);
         if (res) return res;
      }
      res = X2C_fWrite(x->cf, (X2C_ADDRESS)x->buf, x->blen, &wr);
      if (res) return res;
      if ((0x2UL & x->tags)) {
         res = X2C_fTell(x->cf, &x->spos);
         if (res) return res;
      }
      x->tags &= ~0x1UL;
   }
   x->blen = 0UL;
   x->bpos = 0UL;
   return 0L;
} /* end bFlush() */

static X2C_INT32 rawread(xDevData_DevData, X2C_ADDRESS, X2C_CARD32,
                X2C_CARD32 *);


static X2C_INT32 rawread(xDevData_DevData f, X2C_ADDRESS a, X2C_CARD32 size,
                X2C_CARD32 * rd)
{
   X2C_INT32 res;
   res = 0L;
   if ((0x4UL & f->tags)) {
      res = f->flush(f);
      if (res) return res;
   }
   *rd = size;
   if (size>0UL) {
      if (f->ucnt>0UL) {
         do {
            --f->ucnt;
            *(X2C_CHAR *)a = f->ubuf[f->ucnt];
            --size;
            a = (X2C_ADDRESS)((X2C_ADDRESS)a+(X2C_INT32)1UL);
         } while (!(size==0UL || f->ucnt==0UL));
      }
      if (size>0UL) res = f->bread(f, a, size, rd);
   }
   return res;
} /* end rawread() */

static X2C_INT32 rawwrite(xDevData_DevData, X2C_ADDRESS, X2C_CARD32,
                X2C_CARD32 *);


static X2C_INT32 rawwrite(xDevData_DevData f, X2C_ADDRESS buf,
                X2C_CARD32 size, X2C_CARD32 * wr)
{
   f->ucnt = 0UL;
   return f->bwrite(f, buf, size, wr);
} /* end rawwrite() */

static void rawungetc(xDevData_DevData, X2C_CHAR);


static void rawungetc(xDevData_DevData f, X2C_CHAR ch)
{
   f->ubuf[f->ucnt] = ch;
   ++f->ucnt;
} /* end rawungetc() */

static X2C_INT32 textread(xDevData_DevData, X2C_ADDRESS, X2C_CARD32,
                X2C_CARD32 *);


static X2C_INT32 textread(xDevData_DevData f, X2C_ADDRESS a, X2C_CARD32 size,
                 X2C_CARD32 * rd)
{
   X2C_INT32 res;
   X2C_ADDRESS p;
   X2C_CARD32 i;
   X2C_CARD32 c;
   X2C_BOOLEAN flag;
   if ((0x4UL & f->tags)) {
      res = f->flush(f);
      if (res) return res;
   }
   if (size==0UL) return 0L;
   res = 0L;
   flag = 1;
   p = a;
   c = 0UL;
   if (f->ucnt>0UL) {
      do {
         --f->ucnt;
         *(X2C_CHAR *)p = f->ubuf[f->ucnt];
         ++c;
         p = (X2C_ADDRESS)((X2C_ADDRESS)p+(X2C_INT32)1UL);
      } while (!(c>=size || f->ucnt==0UL));
   }
   if (c<size) {
      res = f->bread(f, p, size-c, &i);
      if (res) return res;
      flag = i==size-c;
      c += i;
   }
   *rd = c;
   return 0L;
} /* end textread() */

static X2C_INT32 textwrite(xDevData_DevData, X2C_ADDRESS, X2C_CARD32,
                X2C_CARD32 *);


static X2C_INT32 textwrite(xDevData_DevData f, X2C_ADDRESS a,
                X2C_CARD32 size, X2C_CARD32 * wr)
{
   X2C_INT32 res;
   X2C_CHAR s[256];
   X2C_CARD32 i;
   X2C_CHAR ch;
   X2C_BOOLEAN flag;
   res = 0L;
   f->ucnt = 0UL;
   i = 0UL;
   *wr = 0UL;
   flag = 0;
   while (size>0UL) {
      ch = *(X2C_CHAR *)a;
      a = (X2C_ADDRESS)((X2C_ADDRESS)a+(X2C_INT32)1UL);
      ++*wr;
      --size;
      flag = flag || ch=='\012';
      if (i>=256UL) {
         res = f->bwrite(f, (X2C_ADDRESS)s, i, &i);
         if (res) return res;
         i = 0UL;
      }
      s[i] = ch;
      ++i;
   }
   if (i>0UL) res = f->bwrite(f, (X2C_ADDRESS)s, i, &i);
   if (((0x4UL & f->tags) && flag) && res==0L) res = f->flush(f);
   return res;
} /* end textwrite() */

static void textungetc(xDevData_DevData, X2C_CHAR);


static void textungetc(xDevData_DevData f, X2C_CHAR ch)
{
   f->ubuf[f->ucnt] = ch;
   ++f->ucnt;
} /* end textungetc() */

static xDevData_DevData ring;


static void TieFile(xDevData_DevData f)
{
   if (ring==0) {
      f->fwd = f;
      f->bck = f;
      ring = f;
   }
   else {
      f->fwd = ring;
      f->bck = ring->bck;
      f->bck->fwd = f;
      f->fwd->bck = f;
   }
} /* end TieFile() */


static void UntieFile(xDevData_DevData f)
{
   if (ring==f) ring = ring->fwd;
   if (ring==f) {
      ring = 0;
      return;
   }
   f->fwd->bck = f->bck;
   f->bck->fwd = f->fwd;
} /* end UntieFile() */

static void GetName(IOLink_DeviceTablePtr, X2C_CHAR [], X2C_CARD32);


static void GetName(IOLink_DeviceTablePtr x, X2C_CHAR s[], X2C_CARD32 s_len)
{
   xDevData_DevData f;
   xDevData_FileName anonym;
   f = (xDevData_DevData)x->cd;
   if (f->name==0) s[0UL] = 0;
   else {
      anonym = f->name;
      X2C_COPY(anonym->Adr,anonym->Len0,s,s_len);
   }
} /* end GetName() */

static void RawRead(IOLink_DeviceTablePtr, X2C_ADDRESS, X2C_CARD32,
                X2C_CARD32 *);


static void RawRead(IOLink_DeviceTablePtr x, X2C_ADDRESS a, X2C_CARD32 n,
                X2C_CARD32 * locs)
{
   xDevData_DevData f;
   X2C_INT32 res;
   if (n==0UL) {
      *locs = 0UL;
      return;
   }
   f = (xDevData_DevData)x->cd;
   lock0(f);
   res = f->read0(f, a, n, locs);
   unlock0(f);
   if (res) xDevData_HardError(x, *(X2C_WORD *) &res);
   if (*locs==0UL) x->result = IOConsts_endOfInput;
   else x->result = IOConsts_allRight;
} /* end RawRead() */

static void Flush(IOLink_DeviceTablePtr);


static void Flush(IOLink_DeviceTablePtr x)
{
   xDevData_DevData f;
   X2C_INT32 res;
   f = (xDevData_DevData)x->cd;
   lock0(f);
   res = f->flush(f);
   f->ucnt = 0UL;
   if (res==0L && (0x2U & f->flags)) res = X2C_fFlush(f->cf);
   unlock0(f);
   if (res) xDevData_HardError(x, *(X2C_WORD *) &res);
} /* end Flush() */

static void TextWrite(IOLink_DeviceTablePtr, X2C_ADDRESS, X2C_CARD32);


static void TextWrite(IOLink_DeviceTablePtr x, X2C_ADDRESS a, X2C_CARD32 n)
{
   X2C_CARD32 num;
   X2C_INT32 res;
   xDevData_DevData f;
   f = (xDevData_DevData)x->cd;
   lock0(f);
   res = f->write0(f, a, n, &num);
   unlock0(f);
   if (res || num!=n) xDevData_HardError(x, *(X2C_WORD *) &res);
} /* end TextWrite() */

static void WriteLn(IOLink_DeviceTablePtr);


static void WriteLn(IOLink_DeviceTablePtr x)
{
   X2C_CARD32 n;
   X2C_INT32 res;
   xDevData_DevData f;
   X2C_CHAR ch;
   f = (xDevData_DevData)x->cd;
   ch = '\012';
   lock0(f);
   res = f->write0(f, (X2C_ADDRESS) &ch, 1UL, &n);
   unlock0(f);
   if (res) xDevData_HardError(x, *(X2C_WORD *) &res);
} /* end WriteLn() */

static void Look(IOLink_DeviceTablePtr, X2C_CHAR *, X2C_CARD8 *);


static void Look(IOLink_DeviceTablePtr x, X2C_CHAR * ch, X2C_CARD8 * res)
{
   xDevData_DevData f;
   X2C_CARD32 l;
   X2C_INT32 r;
   f = (xDevData_DevData)x->cd;
   lock0(f);
   r = f->read0(f, (X2C_ADDRESS)ch, 1UL, &l);
   if (r==0L) {
      if (l==0UL) *res = IOConsts_endOfInput;
      else {
         if (*ch=='\012') *res = IOConsts_endOfLine;
         else *res = IOConsts_allRight;
         f->ungetc0(f, *ch);
      }
   }
   else *res = IOConsts_endOfInput;
   unlock0(f);
   x->result = *res;
} /* end Look() */

static void Skip(IOLink_DeviceTablePtr);


static void Skip(IOLink_DeviceTablePtr x)
{
   xDevData_DevData f;
   X2C_CHAR ch;
   X2C_CARD32 l;
   X2C_INT32 res;
   f = (xDevData_DevData)x->cd;
   lock0(f);
   res = f->read0(f, (X2C_ADDRESS) &ch, 1UL, &l);
   unlock0(f);
   if (res) xDevData_HardError(x, *(X2C_WORD *) &res);
   else if (l==0UL) {
      IOLink_RAISEdevException(x->cid, x->did, IOChan_skipAtEnd, "", 1ul);
   }
   x->result = IOConsts_allRight;
} /* end Skip() */

static void SkipLook(IOLink_DeviceTablePtr, X2C_CHAR *, X2C_CARD8 *);


static void SkipLook(IOLink_DeviceTablePtr x, X2C_CHAR * ch,
                X2C_CARD8 * res)
{
   Skip(x);
   Look(x, ch, res);
} /* end SkipLook() */

static void TextRead(IOLink_DeviceTablePtr, X2C_ADDRESS, X2C_CARD32,
                X2C_CARD32 *);


static void TextRead(IOLink_DeviceTablePtr x, X2C_ADDRESS a, X2C_CARD32 n,
                X2C_CARD32 * locs)
{
   xDevData_DevData f;
   X2C_CHAR ch;
   X2C_CARD32 l;
   X2C_INT32 res;
   f = (xDevData_DevData)x->cd;
   lock0(f);
   *locs = 0UL;
   while (*locs<n) {
      res = f->read0(f, (X2C_ADDRESS) &ch, 1UL, &l);
      if (res) {
         unlock0(f);
         xDevData_HardError(x, *(X2C_WORD *) &res);
      }
      else if (l==0UL) {
         if (*locs>0UL) x->result = IOConsts_allRight;
         else x->result = IOConsts_endOfInput;
         unlock0(f);
         return;
      }
      if (ch=='\012') {
         f->ungetc0(f, ch);
         if (*locs>0UL) x->result = IOConsts_allRight;
         else x->result = IOConsts_endOfLine;
         unlock0(f);
         return;
      }
      *(X2C_CHAR *)a = ch;
      a = (X2C_ADDRESS)((X2C_ADDRESS)a+(X2C_INT32)1UL);
      ++*locs;
   }
   unlock0(f);
   x->result = IOConsts_allRight;
} /* end TextRead() */


static void IniRead(IOLink_DeviceTablePtr x)
{
   if ((0x10U & x->flags)) x->doRawRead = RawRead;
   if ((0x8U & x->flags)) {
      x->doLook = Look;
      x->doSkip = Skip;
      x->doSkipLook = SkipLook;
      x->doTextRead = TextRead;
   }
} /* end IniRead() */


static void IniWrite(IOLink_DeviceTablePtr x)
{
   if ((0x10U & x->flags)) x->doRawWrite = TextWrite;
   if ((0x8U & x->flags)) {
      x->doTextWrite = TextWrite;
      x->doLnWrite = WriteLn;
   }
} /* end IniWrite() */

static X2C_CARD8 xDevData_mix = 0x18U;


extern void xDevData_Open(IOLink_DeviceTablePtr x, X2C_OSFHANDLE file,
                xDevData_FileName name, X2C_CARD8 flags, X2C_CARD8 bmode,
                X2C_CARD8 * res)
{
   xDevData_DevData f;
   int type;
   if ((0x18U&flags)==0x18U && !X2C_IsMixAllowed()) {
      *res = ChanConsts_noMixedOperations;
      return;
   }
   if (name==0) {
      *res = ChanConsts_outOfChans;
      return;
   }
   X2C_ALLOCATE((X2C_ADDRESS*) &f,sizeof(struct xDevData_DevDataRec));
   if (f==0) {
      *res = ChanConsts_outOfChans;
      return;
   }
   f->name = name;
   f->tags = 0UL;
   f->buf = 0;
   type = X2C_fGetFileType(file);
   switch ((unsigned)bmode) {
   case xDevData_bmFull:
   case xDevData_bmLine:
      if (type) bmode = xDevData_bmNone;
      break;
   case xDevData_bmDefault:
      if (type==0) bmode = xDevData_bmFull;
      else bmode = xDevData_bmNone;
      break;
   } /* end switch */
   if (f->buf) {
      if (bmode==xDevData_bmLine) f->bread = dRead;
      else f->bread = bRead;
      f->bwrite = bWrite;
      f->flush = bFlush;
   }
   else {
      f->bread = dRead;
      f->bwrite = dWrite;
      f->flush = dFlush;
   }
   if ((flags&0x8U)!=0U) {
      f->read0 = textread;
      f->write0 = textwrite;
      f->ungetc0 = textungetc;
   }
   else {
      f->read0 = rawread;
      f->write0 = rawwrite;
      f->ungetc0 = rawungetc;
   }
   f->cf = file;
   f->flags = flags;
   f->bpos = 0UL;
   f->blen = 0UL;
   f->tags |= 0x2UL;
   if (bmode==xDevData_bmLine) f->tags |= 0x4UL;
   f->ucnt = 0UL;
   x->flags = flags;
   x->cd = (X2C_ADDRESS)f;
   if ((0x2U & flags)) IniWrite(x);
   if ((0x1U & flags)) IniRead(x);
   x->doGetName = (IOLink_GetNameProc)GetName;
   x->doFlush = Flush;
   TieFile(f);
   *res = ChanConsts_opened;
} /* end Open() */

static IOLink_DeviceId did;


extern void xDevData_GetDID(IOLink_DeviceId * d)
{
   *d = did;
} /* end GetDID() */


extern xDevData_DevData xDevData_GetDevData(IOLink_DeviceTablePtr x)
{
   return (xDevData_DevData)x->cd;
} /* end GetDevData() */

static void dlook(IOLink_DeviceTablePtr, X2C_CHAR *, X2C_CARD8 *);


static void dlook(IOLink_DeviceTablePtr x, X2C_CHAR * c, X2C_CARD8 * r)
{
   IOLink_RAISEdevException(x->cid, x->did, IOChan_notAvailable, "", 1ul);
} /* end dlook() */

static void dskip(IOLink_DeviceTablePtr);


static void dskip(IOLink_DeviceTablePtr x)
{
   IOLink_RAISEdevException(x->cid, x->did, IOChan_notAvailable, "", 1ul);
} /* end dskip() */

static void dread(IOLink_DeviceTablePtr, X2C_ADDRESS, X2C_CARD32,
                X2C_CARD32 *);


static void dread(IOLink_DeviceTablePtr x, X2C_ADDRESS a, X2C_CARD32 max0,
                X2C_CARD32 * n)
{
   IOLink_RAISEdevException(x->cid, x->did, IOChan_notAvailable, "", 1ul);
} /* end dread() */

static void dwrite(IOLink_DeviceTablePtr, X2C_ADDRESS, X2C_CARD32);


static void dwrite(IOLink_DeviceTablePtr x, X2C_ADDRESS a, X2C_CARD32 max0)
{
   IOLink_RAISEdevException(x->cid, x->did, IOChan_notAvailable, "", 1ul);
} /* end dwrite() */


extern void xDevData_ForbidAll(IOLink_DeviceTablePtr x)
{
   x->doLook = dlook;
   x->doSkip = dskip;
   x->doSkipLook = dlook;
   x->doTextRead = dread;
   x->doRawRead = dread;
   x->doLnWrite = dskip;
   x->doTextWrite = dwrite;
   x->doRawWrite = dwrite;
} /* end ForbidAll() */


extern void xDevData_SetMode(IOLink_DeviceTablePtr x, X2C_BOOLEAN input)
{
   xDevData_DevData f;
   f = (xDevData_DevData)x->cd;
   lock0(f);
   xDevData_ForbidAll(x);
   x->flags = x->flags&~0x1U&~0x2U;
   if (input) {
      if ((0x1U & f->flags)) {
         IniRead(x);
         x->flags = x->flags|0x1U;
      }
   }
   else if ((0x2U & f->flags)) {
      IniWrite(x);
      x->flags = x->flags|0x2U;
   }
   unlock0(f);
} /* end SetMode() */


extern void xDevData_Close(IOLink_DeviceTablePtr x)
{
   xDevData_DevData f;
   X2C_INT32 res;
   f = (xDevData_DevData)x->cd;
   lock0(f);
   res = f->flush(f);
   if (res) {
      unlock0(f);
      xDevData_HardError(x, *(X2C_WORD *) &res);
   }
   if (f->buf) X2C_DEALLOCATE((X2C_ADDRESS*) &f->buf);
   X2C_DYNDEALLOCATE((X2C_ADDRESS*) &f->name);
   unlock0(f);
   UntieFile(f);
   X2C_DEALLOCATE((X2C_ADDRESS*) &f);
} /* end Close() */


extern void xDevData_CurrentPos(IOLink_DeviceTablePtr x,
                struct X2C_int64 * pos)
{
   xDevData_DevData f;
   X2C_INT32 res;
   f = (xDevData_DevData)x->cd;
   lock0(f);
   if (f->buf) {
      X2C_CARDTO64(pos, f->bpos);
      if (X2C_ADD64(pos, f->spos, *pos)) {
         unlock0(f);
         X2C_TRAP_F(5L);
      }
   }
   else {
      res = X2C_fTell(f->cf, pos);
      if (res) {
         unlock0(f);
         xDevData_SoftError(x, *(X2C_WORD *) &res);
      }
   }
   unlock0(f);
} /* end CurrentPos() */


extern void xDevData_Length(IOLink_DeviceTablePtr x, struct X2C_int64 * pos)
{
   xDevData_DevData f;
   X2C_INT32 res;
   struct X2C_int64 l;
   f = (xDevData_DevData)x->cd;
   lock0(f);
   if (f->buf==0) {
      res = X2C_fSize(f->cf, pos);
      if (res) {
         unlock0(f);
         xDevData_SoftError(x, *(X2C_WORD *) &res);
      }
   }
   else {
      res = X2C_fSize(f->cf, &l);
      if (res) {
         unlock0(f);
         xDevData_SoftError(x, *(X2C_WORD *) &res);
      }
      X2C_CARDTO64(pos, f->blen);
      if (X2C_ADD64(pos, f->spos, *pos)) {
         unlock0(f);
         X2C_TRAP_F(5L);
      }
      if (X2C_CMP64(l, *pos)>0) *pos = l;
   }
   unlock0(f);
} /* end Length() */


extern void xDevData_SetPos(IOLink_DeviceTablePtr x, struct X2C_int64 pos)
{
   xDevData_DevData f;
   X2C_INT32 res;
   struct X2C_int64 l;
   X2C_CARD32 q;
   f = (xDevData_DevData)x->cd;
   lock0(f);
   if (f->buf==0) {
      res = X2C_fSeek(f->cf, &pos, 0);
      if (res) {
         unlock0(f);
         xDevData_SoftError(x, *(X2C_WORD *) &res);
      }
   }
   else {
      X2C_CARDTO64(&l, f->blen);
      if (X2C_ADD64(&l, f->spos, l)) {
         unlock0(f);
         X2C_TRAP_F(5L);
      }
      if (X2C_CMP64(pos, f->spos)>=0 && X2C_CMP64(pos, l)<0) {
         if ((X2C_UnMinus64(&l, f->spos) || X2C_ADD64(&l, pos,
                l)) || X2C_64TOCARD(&q, l)) unlock0(f);
         if (q!=f->bpos) f->ucnt = 0UL;
         f->bpos = q;
      }
      else {
         f->ucnt = 0UL;
         res = f->flush(f);
         if (res) {
            unlock0(f);
            xDevData_HardError(x, *(X2C_WORD *) &res);
         }
         res = X2C_fSeek(f->cf, &pos, 0);
         if (res) {
            unlock0(f);
            xDevData_SoftError(x, *(X2C_WORD *) &res);
         }
         f->spos = pos;
      }
   }
   unlock0(f);
} /* end SetPos() */


static void FlushAll(void)
{
   xDevData_DevData f;
   X2C_INT32 res;
   if (ring==0) return;
   f = ring;
   do {
      if (f->buf) {
         res = f->flush(f);
         f->ucnt = 0UL;
      }
      f = f->fwd;
   } while (f!=ring);
} /* end FlushAll() */


extern X2C_BOOLEAN xDevData_SynchronizePos(IOLink_DeviceTablePtr x)
{
   X2C_INT32 res;
   xDevData_DevData f;
   f = (xDevData_DevData)x->cd;
   if (f->bpos) return 0;
   res = X2C_fTell(f->cf, &f->spos);
   if (res) return 0;
   return 1;
} /* end SynchronizePos() */

static void xDevData_FINALLY(void);


extern void xDevData_BEGIN(void)
{
   static int xDevData_init = 0;
   if (xDevData_init) return;
   xDevData_init = 1;
   if (sizeof(Str10)!=10) X2C_ASSERT(0);
   IOChan_BEGIN();
   IOConsts_BEGIN();
   M2EXCEPTION_BEGIN();
   IOLink_BEGIN();
   ChanConsts_BEGIN();
   X2C_FINALLY(xDevData_FINALLY);
   IOLink_AllocateDeviceId(&did);
   ring = 0;
}


static void xDevData_FINALLY(void)
{
   FlushAll();
} /* end xDevData_FINALLY() */

