/* XDS v2.60: Copyright (c) 1999-2011 Excelsior, LLC. All Rights Reserved. */
/* "@(#)xFilePos.c Feb  3 14:31:18 2012" */
/* Generated by XDS Modula-2 to ANSI C v4.20 translator */

#define X2C_int32
#define X2C_index32
#ifndef xFilePos_H_
#include "xFilePos.h"
#endif
#define xFilePos_C_
#ifndef RndFile_H_
#include "RndFile.h"
#endif
#ifndef xrInt64_H_
#include "xrInt64.h"
#endif

union FPOS;


union FPOS {
   struct X2C_int64 rec;
   RndFile_FilePos arr;
};


extern void xFilePos_CardToPos(RndFile_FilePos P, X2C_CARD32 c)
{
   union FPOS p0;
   X2C_CARDTO64(&p0.rec, c);
   memcpy(P,p0.arr,8u);
} /* end CardToPos() */


extern void xFilePos_IntToPos(RndFile_FilePos P, X2C_INT32 i)
{
   union FPOS p0;
   X2C_INTTO64(&p0.rec, i);
   memcpy(P,p0.arr,8u);
} /* end IntToPos() */


extern X2C_BOOLEAN xFilePos_PosToInt(X2C_INT32 * i, RndFile_FilePos P)
{
   union FPOS p0;
   RndFile_FilePos tmp;
   P = (X2C_LOC *)memcpy(tmp,P,8u);
   memcpy(p0.arr,P,8u);
   return !X2C_64TOINT(i, p0.rec);
} /* end PosToInt() */


extern X2C_BOOLEAN xFilePos_PosToCard(X2C_CARD32 * c, RndFile_FilePos P)
{
   union FPOS p0;
   RndFile_FilePos tmp;
   P = (X2C_LOC *)memcpy(tmp,P,8u);
   memcpy(p0.arr,P,8u);
   return !X2C_64TOCARD(c, p0.rec);
} /* end PosToCard() */


extern void xFilePos_BEGIN(void)
{
   static int xFilePos_init = 0;
   if (xFilePos_init) return;
   xFilePos_init = 1;
   RndFile_BEGIN();
}

