/* XDS v2.60: Copyright (c) 1999-2011 Excelsior, LLC. All Rights Reserved. */
/* "@(#)XReal.c Feb  3 14:31:18 2012" */
/* Generated by XDS Modula-2 to ANSI C v4.20 translator */

#define X2C_int32
#define X2C_index32
#ifndef XReal_H_
#include "XReal.h"
#endif
#define XReal_C_

#define XReal_MAXPOW 30

static X2C_LONGREAL pow0[30];

static X2C_CARD32 pow_max;

static X2C_CARD32 pow20;

static X2C_BOOLEAN pow_done;


static void pow_init(void)
{
   X2C_INT32 i;
   if (pow_done) return;
   pow_done = 1;
   i = 1L;
   pow0[0U] = 10.0;
   pow20 = 1UL;
   while (i<30L && X2C_DIVL(X2C_max_longreal,pow0[i-1L])>pow0[i-1L]) {
      pow0[i] = pow0[i-1L]*pow0[i-1L];
      pow20 += pow20;
      ++i;
   }
   pow_max = (X2C_CARD32)(i-1L);
   while (i<30L) {
      pow0[i] = (-1.0);
      ++i;
   }
} /* end pow_init() */


extern X2C_LONGREAL XReal_power10(X2C_CARD32 e, X2C_BOOLEAN * oo)
{
   X2C_CARD32 i;
   X2C_LONGREAL t;
   X2C_BOOLEAN ovf;
   i = 0UL;
   t = 1.0;
   ovf = *oo;
   while (e && !ovf) {
      pow_init();
      if ((e&1)) {
         ovf = (ovf || i>pow_max) || X2C_DIVL(X2C_max_longreal,pow0[i])<=t;
         if (!ovf) t = t*pow0[i];
      }
      ++i;
      e = e/2UL;
   }
   *oo = ovf;
   if (ovf) t = X2C_max_longreal;
   return t;
} /* end power10() */


static X2C_INT32 exponent(X2C_LONGREAL * rr)
{
   X2C_LONGREAL x;
   X2C_INT32 i;
   X2C_INT32 n;
   X2C_INT32 e;
   pow_init();
   n = (X2C_INT32)pow20;
   i = (X2C_INT32)pow_max;
   e = 0L;
   if (*rr>=1.0) {
      if (X2C_DIVL(*rr,2.0)==*rr) *rr = X2C_max_longreal;
      for (;;) {
         x = X2C_DIVL(*rr,pow0[i]);
         if (x<0.1) {
            if (i==0L) break;
            --i;
            n = X2C_DIV(n,2L);
         }
         else {
            *rr = x;
            e += n;
         }
      }
   }
   else if (*rr<0.1 &&  *rr*2.0!=*rr) {
      for (;;) {
         x =  *rr*pow0[i];
         if (x>=1.0) {
            if (i==0L) break;
            --i;
            n = X2C_DIV(n,2L);
         }
         else {
            *rr = x;
            e -= n;
         }
      }
   }
   if (*rr>=1.0) {
      *rr = X2C_DIVL(*rr,10.0);
      ++e;
   }
   return e;
} /* end exponent() */


static X2C_CHAR get_digit(X2C_LONGREAL * r)
{
   X2C_CARD32 d;
   *r =  *r*10.0;
   d = (X2C_CARD32)X2C_TRUNCC(*r,0UL,X2C_max_longcard);
   *r = *r-(X2C_LONGREAL)d;
   return (X2C_CHAR)(d+48UL);
} /* end get_digit() */


static void ch0(XReal_STR str, X2C_CARD32 * ps, X2C_CHAR c)
{
   if (*ps<=63UL) str[*ps] = c;
   ++*ps;
} /* end ch() */

static void cnum(X2C_CARD32 *, XReal_STR, X2C_CARD32);


static void cnum(X2C_CARD32 * ps, XReal_STR str, X2C_CARD32 n)
{
   if (n<10UL) ch0(str, ps, (X2C_CHAR)(n+48UL));
   else {
      cnum(ps, str, n/10UL);
      ch0(str, ps, (X2C_CHAR)(n%10UL+48UL));
   }
} /* end cnum() */


extern void XReal_to_float(X2C_LONGREAL r, X2C_INT32 digs, X2C_INT32 round,
                X2C_INT32 max0, X2C_CHAR exp0, X2C_BOOLEAN tail,
                X2C_BOOLEAN esig, XReal_STR str)
{
   X2C_CARD32 ps;
   X2C_INT32 len;
   X2C_INT32 e;
   X2C_INT32 pt;
   X2C_INT32 d;
   X2C_INT32 l;
   X2C_INT32 k;
   X2C_CHAR c;
   X2C_BOOLEAN nz;
   X2C_BOOLEAN ovr;
   X2C_INT32 tmp;
   ps = 0UL;
   len = 0L;
   ovr = 0;
   nz = 0;
   if (r<0.0) {
      ch0(str, &ps, '-');
      r = -r;
   }
   e = exponent(&r);
   d = max0;
   if (digs>0L && digs<d) d = digs;
   if (r>0.0) {
      r = r+X2C_DIVL(0.5,XReal_power10((X2C_CARD32)d, &ovr));
      if (r>=1.0) {
         r = X2C_DIVL(r,10.0);
         ++e;
      }
   }
   pt = 1L;
   --e;
   k = X2C_MOD(e,round);
   if (k) {
      pt = k+1L;
      e -= k;
   }
   tmp = pt;
   k = 1L;
   if (k<=tmp) for (;; k++) {
      if (len<d) {
         c = get_digit(&r);
         ++len;
      }
      else c = '0';
      if (nz) ch0(str, &ps, c);
      else if (c!='0') {
         ch0(str, &ps, c);
         nz = 1;
      }
      else if (k==pt) ch0(str, &ps, c);
      if (k==tmp) break;
   } /* end for */
   if (d>pt) {
      k = (X2C_INT32)ps;
      ch0(str, &ps, '.');
      tmp = d-pt;
      l = 1L;
      if (l<=tmp) for (;; l++) {
         c = get_digit(&r);
         ch0(str, &ps, c);
         if (c!='0') {
            k = (X2C_INT32)ps;
            nz = 1;
         }
         if (l==tmp) break;
      } /* end for */
      if (!tail) ps = (X2C_CARD32)k;
   }
   if (nz && e) {
      ch0(str, &ps, exp0);
      if (e<0L) {
         ch0(str, &ps, '-');
         e = -e;
      }
      else if (esig) ch0(str, &ps, '+');
      cnum(&ps, str, (X2C_CARD32)e);
   }
   if (ps<=63UL) str[ps] = 0;
} /* end to_float() */


static void ch(XReal_STR str, X2C_CARD32 * ps, X2C_CHAR c)
{
   if (*ps<=63UL) str[*ps] = c;
   ++*ps;
} /* end ch() */


extern void XReal_to_fixed(X2C_LONGREAL r, X2C_INT32 place, X2C_INT32 max0,
                XReal_STR str)
{
   X2C_CARD32 ps;
   X2C_INT32 len;
   X2C_INT32 d;
   X2C_INT32 n;
   X2C_INT32 e;
   X2C_BOOLEAN ovr;
   ps = 0UL;
   len = 0L;
   ovr = 0;
   if (r<0.0) {
      ch(str, &ps, '-');
      r = -r;
   }
   if (r>0.0) {
      e = exponent(&r);
      if (place>=0L) n = e+place;
      else n = e+place+1L;
      if (n>max0) r = r+X2C_DIVL(0.5,XReal_power10((X2C_CARD32)max0, &ovr));
      else if (n>=0L) r = r+X2C_DIVL(0.5,XReal_power10((X2C_CARD32)n, &ovr));
      if (r>=1.0) {
         r = X2C_DIVL(r,10.0);
         ++e;
      }
   }
   else e = 0L;
   d = max0;
   if (e<=0L) {
      ch(str, &ps, '0');
      if (place>-1L) {
         ch(str, &ps, '.');
         n = 0L;
         while (n<place && ps<64UL) {
            if (n<-e || len>=d) ch(str, &ps, '0');
            else {
               ch(str, &ps, get_digit(&r));
               ++len;
            }
            ++n;
         }
      }
   }
   else if (-place-1L>=e) ch(str, &ps, '0');
   else {
      n = 0L;
      while (n<e && ps<65UL) {
         if (n<e+place+1L && len<d) {
            ch(str, &ps, get_digit(&r));
            ++len;
         }
         else ch(str, &ps, '0');
         ++n;
      }
      if (place>-1L) {
         ch(str, &ps, '.');
         n = 0L;
         while (n<place && ps<64UL) {
            if (len<d) {
               ch(str, &ps, get_digit(&r));
               ++len;
            }
            else ch(str, &ps, '0');
            ++n;
         }
      }
   }
   if (ps<=63UL) str[ps] = 0;
} /* end to_fixed() */


extern void XReal_to_any(X2C_LONGREAL r, X2C_INT32 max0, XReal_STR s,
                X2C_INT32 len)
{
   X2C_INT32 e;
   X2C_INT32 d;
   X2C_INT32 sg;
   X2C_LONGREAL f;
   X2C_INT32 tmp;
   if (len<=0L) return;
   f = r;
   sg = 0L;
   if (f<0.0) {
      f = -f;
      sg = 1L;
   }
   e = exponent(&f);
   if (max0>len-sg) max0 = len-sg;
   if (max0==len-sg && e+1L<max0) max0 = (len-sg)-1L;
   tmp = max0;
   d = 0L;
   if (d<=tmp) for (;; d++) {
      s[d] = get_digit(&f);
      if (d==tmp) break;
   } /* end for */
   while ((max0>1L && s[max0-1L]=='0') && (X2C_CARD8)s[max0]<'5') --max0;
   if (e>=max0 && sg+e<=len) {
      XReal_to_fixed(r, ((len-e)-sg)-1L, max0, s);
      if ((X2C_INT32)X2C_LENGTH(s,64ul)<=len) return;
   }
   if ((e>=0L && e<max0) && sg+1L+max0<=len) {
      XReal_to_fixed(r, ((len-e)-sg)-1L, max0, s);
   }
   else if (e<0L && sg+2L+labs(e)+max0<=len) {
      XReal_to_fixed(r, (len-sg)-2L, max0, s);
   }
   else {
      d = len;
      for (;;) {
         XReal_to_float(r, d, 1L, max0, 'E', 0, 0, s);
         if (d<=1L || (X2C_INT32)X2C_LENGTH(s,64ul)<=len) break;
         --d;
      }
   }
} /* end to_any() */


extern void XReal_strcpy(XReal_STR fr, X2C_CHAR to[], X2C_CARD32 to_len)
{
   X2C_INT32 i;
   i = 0L;
   while ((i<64L && i<to_len) && fr[i]) {
      to[i] = fr[i];
      ++i;
   }
   if (i<=(X2C_INT32)(to_len-1)) to[i] = 0;
} /* end strcpy() */


extern void XReal_BEGIN(void)
{
   static int XReal_init = 0;
   if (XReal_init) return;
   XReal_init = 1;
   if (sizeof(XReal_STR)!=64) X2C_ASSERT(0);
   pow_done = 0;
}

