/* XDS v2.60: Copyright (c) 1999-2011 Excelsior, LLC. All Rights Reserved. */
/* Generated by XDS Modula-2 to ANSI C v4.20 translator */

#ifndef CharClass_H_
#define CharClass_H_
#ifndef X2C_H_
#include "X2C.h"
#endif

extern X2C_BOOLEAN CharClass_IsNumeric(X2C_CHAR);

extern X2C_BOOLEAN CharClass_IsLetter(X2C_CHAR);

extern X2C_BOOLEAN CharClass_IsUpper(X2C_CHAR);

extern X2C_BOOLEAN CharClass_IsLower(X2C_CHAR);

extern X2C_BOOLEAN CharClass_IsControl(X2C_CHAR);

extern X2C_BOOLEAN CharClass_IsWhiteSpace(X2C_CHAR);


extern void CharClass_BEGIN(void);


#endif /* CharClass_H_ */
