/* XDS v2.60: Copyright (c) 1999-2011 Excelsior, LLC. All Rights Reserved. */
/* Generated by XDS Modula-2 to ANSI C v4.20 translator */

#ifndef ConvTypes_H_
#define ConvTypes_H_
#ifndef X2C_H_
#include "X2C.h"
#endif

enum ConvTypes_ConvResults {ConvTypes_strAllRight, 
   ConvTypes_strOutOfRange, 
   ConvTypes_strWrongFormat, 
   ConvTypes_strEmpty};


enum ConvTypes_ScanClass {ConvTypes_padding, 
   ConvTypes_valid, 
   ConvTypes_invalid, 
   ConvTypes_terminator};


typedef void ( *ConvTypes_ScanState)(X2C_CHAR, X2C_CARD8 *, X2C_PROC *);


extern void ConvTypes_BEGIN(void);


#endif /* ConvTypes_H_ */
