/* XDS v2.60: Copyright (c) 1999-2011 Excelsior, LLC. All Rights Reserved. */
/* Generated by XDS Modula-2 to ANSI C v4.20 translator */

#ifndef FIOR_H_
#define FIOR_H_
#ifndef X2C_H_
#include "X2C.h"
#endif

extern void FIOR_AddExtension(X2C_CHAR [], X2C_CARD32, X2C_CHAR [],
                X2C_CARD32);

extern void FIOR_ChangeExtension(X2C_CHAR [], X2C_CARD32, X2C_CHAR [],
                X2C_CARD32);

extern void FIOR_RemoveExtension(X2C_CHAR [], X2C_CARD32);

extern X2C_BOOLEAN FIOR_IsExtension(X2C_CHAR [], X2C_CARD32, X2C_CHAR [],
                X2C_CARD32);

extern void FIOR_ExpandPath(X2C_CHAR [], X2C_CARD32, X2C_CHAR [],
                X2C_CARD32);

extern void FIOR_MakePath(X2C_CHAR [], X2C_CARD32, X2C_CHAR [], X2C_CARD32,
                X2C_CHAR [], X2C_CARD32);

extern void FIOR_SplitPath(X2C_CHAR [], X2C_CARD32, X2C_CHAR [], X2C_CARD32,
                X2C_CHAR [], X2C_CARD32);


extern void FIOR_BEGIN(void);


#endif /* FIOR_H_ */
