/* XDS v2.60: Copyright (c) 1999-2011 Excelsior, LLC. All Rights Reserved. */
/* Generated by XDS Modula-2 to ANSI C v4.20 translator */

#ifndef FormStr_H_
#define FormStr_H_
#ifndef X2C_H_
#include "X2C.h"
#endif

extern void FormStr_print(X2C_CHAR [], X2C_CARD32, X2C_CHAR [], X2C_CARD32,
                X2C_LOC [], X2C_CARD32);

extern void FormStr_append(X2C_CHAR [], X2C_CARD32, X2C_CHAR [], X2C_CARD32,
                X2C_LOC [], X2C_CARD32);

extern void FormStr_image(X2C_CHAR [], X2C_CARD32, X2C_CARD32 *, X2C_CHAR [],
                 X2C_CARD32, X2C_LOC [], X2C_CARD32);

extern void FormStr_iscan(X2C_INT32 *, X2C_CHAR [], X2C_CARD32, X2C_CARD32 *,
                 X2C_BOOLEAN *);


extern void FormStr_BEGIN(void);


#endif /* FormStr_H_ */
