/* XDS v2.60: Copyright (c) 1999-2011 Excelsior, LLC. All Rights Reserved. */
/* Generated by XDS Modula-2 to ANSI C v4.20 translator */

#ifndef IOConsts_H_
#define IOConsts_H_
#ifndef X2C_H_
#include "X2C.h"
#endif

enum IOConsts_ReadResults {IOConsts_notKnown, 
   IOConsts_allRight, 
   IOConsts_outOfRange, 
   IOConsts_wrongFormat, 
   IOConsts_endOfLine, 
   IOConsts_endOfInput};



extern void IOConsts_BEGIN(void);


#endif /* IOConsts_H_ */
