/* XDS v2.60: Copyright (c) 1999-2011 Excelsior, LLC. All Rights Reserved. */
/* Generated by XDS Oberon-2 to ANSI C v4.20 translator */

#ifndef MathC_H_
#define MathC_H_
#ifndef X2C_H_
#include "X2C.h"
#endif

extern X2C_REAL MathC_abs(X2C_COMPLEX);

extern X2C_COMPLEX MathC_conj(X2C_COMPLEX);

extern X2C_COMPLEX MathC_power(X2C_COMPLEX, X2C_REAL);

extern X2C_COMPLEX MathC_sqrt(X2C_COMPLEX);

extern X2C_COMPLEX MathC_exp(X2C_COMPLEX);

extern X2C_COMPLEX MathC_ln(X2C_COMPLEX);

extern X2C_COMPLEX MathC_log(X2C_COMPLEX, X2C_REAL);

extern X2C_COMPLEX MathC_sin(X2C_COMPLEX);

extern X2C_COMPLEX MathC_cos(X2C_COMPLEX);

extern X2C_COMPLEX MathC_tan(X2C_COMPLEX);

extern X2C_COMPLEX MathC_arcsin(X2C_COMPLEX);

extern X2C_COMPLEX MathC_arccos(X2C_COMPLEX);

extern X2C_COMPLEX MathC_arctan(X2C_COMPLEX);

extern X2C_COMPLEX MathC_arctan2(X2C_COMPLEX, X2C_COMPLEX);

extern X2C_COMPLEX MathC_sinh(X2C_COMPLEX);

extern X2C_COMPLEX MathC_cosh(X2C_COMPLEX);

extern X2C_COMPLEX MathC_tanh(X2C_COMPLEX);

extern X2C_COMPLEX MathC_arcsinh(X2C_COMPLEX);

extern X2C_COMPLEX MathC_arccosh(X2C_COMPLEX);

extern X2C_COMPLEX MathC_arctanh(X2C_COMPLEX);


extern void MathC_BEGIN(void);


#endif /* MathC_H_ */
