/* XDS v2.60: Copyright (c) 1999-2011 Excelsior, LLC. All Rights Reserved. */
/* Generated by XDS Oberon-2 to ANSI C v4.20 translator */

#ifndef MathL_H_
#define MathL_H_
#ifndef X2C_H_
#include "X2C.h"
#endif

#define MathL_pi 3.1415926535898

#define MathL_e 2.718281828459

extern X2C_LONGREAL MathL_sqrt(X2C_LONGREAL);

extern X2C_LONGREAL MathL_exp(X2C_LONGREAL);

extern X2C_LONGREAL MathL_ln(X2C_LONGREAL);

extern X2C_LONGREAL MathL_sin(X2C_LONGREAL);

extern X2C_LONGREAL MathL_cos(X2C_LONGREAL);

extern X2C_LONGREAL MathL_tan(X2C_LONGREAL);

extern X2C_LONGREAL MathL_arcsin(X2C_LONGREAL);

extern X2C_LONGREAL MathL_arccos(X2C_LONGREAL);

extern X2C_LONGREAL MathL_arctan(X2C_LONGREAL);

extern X2C_LONGREAL MathL_power(X2C_LONGREAL, X2C_LONGREAL);

extern X2C_LONGREAL MathL_round(X2C_LONGREAL);

extern X2C_LONGREAL MathL_log(X2C_LONGREAL, X2C_LONGREAL);

extern X2C_LONGREAL MathL_arctan2(X2C_LONGREAL, X2C_LONGREAL);

extern X2C_LONGREAL MathL_sinh(X2C_LONGREAL);

extern X2C_LONGREAL MathL_cosh(X2C_LONGREAL);

extern X2C_LONGREAL MathL_tanh(X2C_LONGREAL);

extern X2C_LONGREAL MathL_arcsinh(X2C_LONGREAL);

extern X2C_LONGREAL MathL_arccosh(X2C_LONGREAL);

extern X2C_LONGREAL MathL_arctanh(X2C_LONGREAL);


extern void MathL_BEGIN(void);


#endif /* MathL_H_ */
