/* XDS v2.60: Copyright (c) 1999-2011 Excelsior, LLC. All Rights Reserved. */
/* Generated by XDS Oberon-2 to ANSI C v4.20 translator */

#ifndef MathR_H_
#define MathR_H_
#ifndef X2C_H_
#include "X2C.h"
#endif

#define MathR_pi 3.1415926535898

#define MathR_e 2.718281828459

extern X2C_REAL MathR_sqrt(X2C_REAL);

extern X2C_REAL MathR_exp(X2C_REAL);

extern X2C_REAL MathR_ln(X2C_REAL);

extern X2C_REAL MathR_sin(X2C_REAL);

extern X2C_REAL MathR_cos(X2C_REAL);

extern X2C_REAL MathR_tan(X2C_REAL);

extern X2C_REAL MathR_arcsin(X2C_REAL);

extern X2C_REAL MathR_arccos(X2C_REAL);

extern X2C_REAL MathR_arctan(X2C_REAL);

extern X2C_REAL MathR_power(X2C_REAL, X2C_REAL);

extern X2C_REAL MathR_round(X2C_REAL);

extern X2C_REAL MathR_log(X2C_REAL, X2C_REAL);

extern X2C_REAL MathR_arctan2(X2C_REAL, X2C_REAL);

extern X2C_REAL MathR_sinh(X2C_REAL);

extern X2C_REAL MathR_cosh(X2C_REAL);

extern X2C_REAL MathR_tanh(X2C_REAL);

extern X2C_REAL MathR_arcsinh(X2C_REAL);

extern X2C_REAL MathR_arccosh(X2C_REAL);

extern X2C_REAL MathR_arctanh(X2C_REAL);


extern void MathR_BEGIN(void);


#endif /* MathR_H_ */
