/* XDS v2.60: Copyright (c) 1999-2011 Excelsior, LLC. All Rights Reserved. */
/* Generated by XDS Modula-2 to ANSI C v4.20 translator */

#ifndef POSIXIOChan_H_
#define POSIXIOChan_H_
#ifndef X2C_H_
#include "X2C.h"
#endif
#ifndef IOChan_H_
#include "IOChan.h"
#endif
#ifndef ChanConsts_H_
#include "ChanConsts.h"
#endif
#ifndef xDevData_H_
#include "xDevData.h"
#endif

typedef IOChan_ChanId POSIXIOChan_ChanId;

typedef X2C_CARD8 POSIXIOChan_FlagSet;

typedef enum ChanConsts_OpenResults POSIXIOChan_OpenResults;

extern X2C_CARD8 POSIXIOChan_read;

extern X2C_CARD8 POSIXIOChan_write;

extern X2C_CARD8 POSIXIOChan_text;

extern X2C_CARD8 POSIXIOChan_raw;

extern X2C_ADDRESS POSIXIOChan_GetFilePtr(IOChan_ChanId);

extern xDevData_FileName POSIXIOChan_GetFileName(IOChan_ChanId);

extern void POSIXIOChan_MakeChannel(IOChan_ChanId *, X2C_ADDRESS,
                X2C_CHAR [], X2C_CARD32, X2C_CARD8, X2C_CARD8 *);


extern void POSIXIOChan_BEGIN(void);


#endif /* POSIXIOChan_H_ */
