/* XDS v2.60: Copyright (c) 1999-2011 Excelsior, LLC. All Rights Reserved. */
/* Generated by XDS Modula-2 to ANSI C v4.20 translator */

#ifndef Storage_H_
#define Storage_H_
#ifndef X2C_H_
#include "X2C.h"
#endif

extern void Storage_ALLOCATE(X2C_ADDRESS *, X2C_CARD32);

extern void Storage_DEALLOCATE(X2C_ADDRESS *, X2C_CARD32);

enum Storage_StorageExceptions {Storage_nilDeallocation, 
   Storage_pointerToUnallocatedSt, 
   Storage_wrongStorageToUnalloca};


extern X2C_BOOLEAN Storage_IsStorageException(void);

extern X2C_CARD8 Storage_StorageException(void);


extern void Storage_BEGIN(void);


#endif /* Storage_H_ */
