/* XDS v2.60: Copyright (c) 1999-2011 Excelsior, LLC. All Rights Reserved. */
/* Generated by XDS Modula-2 to ANSI C v4.20 translator */

#ifndef XReal_H_
#define XReal_H_
#ifndef X2C_H_
#include "X2C.h"
#endif

typedef X2C_CHAR XReal_STR[64];

extern X2C_LONGREAL XReal_power10(X2C_CARD32, X2C_BOOLEAN *);

extern void XReal_to_float(X2C_LONGREAL, X2C_INT32, X2C_INT32, X2C_INT32,
                X2C_CHAR, X2C_BOOLEAN, X2C_BOOLEAN, XReal_STR);

extern void XReal_to_fixed(X2C_LONGREAL, X2C_INT32, X2C_INT32, XReal_STR);

extern void XReal_to_any(X2C_LONGREAL, X2C_INT32, XReal_STR, X2C_INT32);

extern void XReal_strcpy(XReal_STR, X2C_CHAR [], X2C_CARD32);


extern void XReal_BEGIN(void);


#endif /* XReal_H_ */
