/* XDS v2.60: Copyright (c) 1999-2011 Excelsior, LLC. All Rights Reserved. */
/* Generated by XDS Modula-2 to ANSI C v4.20 translator */

#ifndef xrFName_H_
#define xrFName_H_
#ifndef X2C_H_
#include "X2C.h"
#endif

struct xrFName_Format;


struct xrFName_Format {
   X2C_BOOLEAN ok0;
   X2C_CARD32 dirPos;
   X2C_CARD32 dirLen;
   X2C_CARD32 namePos;
   X2C_CARD32 nameLen;
   X2C_CARD32 extPos;
   X2C_CARD32 extLen;
};

extern void xrFName_X2C_ParseFileName(X2C_CHAR [], X2C_CARD32,
                struct xrFName_Format *);

extern void xrFName_X2C_ExtractPath(X2C_CHAR [], X2C_CARD32, X2C_CHAR [],
                X2C_CARD32);

extern void xrFName_X2C_ExtractBaseName(X2C_CHAR [], X2C_CARD32, X2C_CHAR [],
                 X2C_CARD32);

extern void xrFName_X2C_ExtractFileExt(X2C_CHAR [], X2C_CARD32, X2C_CHAR [],
                X2C_CARD32);

extern void xrFName_X2C_SplitFileName(X2C_CHAR [], X2C_CARD32, X2C_CHAR [],
                X2C_CARD32, X2C_CHAR [], X2C_CARD32, X2C_CHAR [],
                X2C_CARD32);


extern void xrFName_BEGIN(void);


#endif /* xrFName_H_ */
