#!/bin/bash
LIB=fftw-3.3.10.tar.gz

SRC_TARBALL=../../$LIB
BUILDDIR=`mktemp -d`

cp $SRC_TARBALL $BUILDDIR
pushd $BUILDDIR
tar -xf $LIB --strip-components=1
./configure --prefix=$BUILDDIR #--enable-float
make -j16
make install
popd
cp $BUILDDIR/lib/*.a .
cp $BUILDDIR/include/*.h .
rm -r -f $BUILDDIR
