/* XDS v2.60: Copyright (c) 1999-2011 Excelsior, LLC. All Rights Reserved. */
/* Generated by XDS Modula-2 to ANSI C v4.20 translator */

#ifndef EXCEPTIONS_H_
#define EXCEPTIONS_H_
#ifndef X2C_H_
#include "X2C.h"
#endif

typedef void *EXCEPTIONS_ExceptionSource;

typedef X2C_CARD32 EXCEPTIONS_ExceptionNumber;

extern void EXCEPTIONS_AllocateSource(EXCEPTIONS_ExceptionSource *);

extern void EXCEPTIONS_RAISE(EXCEPTIONS_ExceptionSource, X2C_CARD32,
                X2C_CHAR [], X2C_CARD32);

extern X2C_CARD32 EXCEPTIONS_CurrentNumber(EXCEPTIONS_ExceptionSource);

extern void EXCEPTIONS_GetMessage(X2C_CHAR [], X2C_CARD32);

extern X2C_BOOLEAN EXCEPTIONS_IsCurrentSource(EXCEPTIONS_ExceptionSource);

extern X2C_BOOLEAN EXCEPTIONS_IsExceptionalExecut(void);


extern void EXCEPTIONS_BEGIN(void);


#endif /* EXCEPTIONS_H_ */
