/* XDS v2.60: Copyright (c) 1999-2011 Excelsior, LLC. All Rights Reserved. */
/* Generated by XDS Oberon-2 to ANSI C v4.20 translator */

#ifndef FilePath_H_
#define FilePath_H_
#ifndef X2C_H_
#include "X2C.h"
#endif
#ifndef DStrings_H_
#include "DStrings.h"
#endif

extern X2C_BOOLEAN FilePath_IsSimpleName(X2C_CHAR [], X2C_CARD32);

extern void FilePath_Lookup(X2C_CHAR [], X2C_CARD32, X2C_CHAR [], X2C_CARD32,
                 DStrings_String *, X2C_INT16 *);

extern void FilePath_UseFirst(X2C_CHAR [], X2C_CARD32, X2C_CHAR [],
                X2C_CARD32, DStrings_String *);


extern void FilePath_BEGIN(void);


#endif /* FilePath_H_ */
