/* h2d_termios.h  Nov 13  19:1:22  2001 */
/* Generated by H2D v1.31.0 */
/* from module h2d_termios and header termios.h. */
/* Types which were created during translation */

#include "termios.h"

#ifndef h2d_termios_H_
#define h2d_termios_H_



#endif  /* h2d_termios_H_ */