/* ncurses\h2d_curses.h  Aug 28  14:46:8  2001 */
/* Generated by H2D v1.31.0 */
/* from module h2d_curses and header ncurses\curses.h. */
/* Types which were created during translation */

#include <curses.h>

#ifndef h2d_curses_H_
#define h2d_curses_H_



#ifndef _H2D_TYPE__H2D_PtrSChar
#define _H2D_TYPE__H2D_PtrSChar

typedef signed char * H2D_PtrSChar;
#endif  /* _H2D_TYPE__H2D_PtrSChar */

#ifndef _H2D_TYPE__H2D_Ptr_IO_marker
#define _H2D_TYPE__H2D_Ptr_IO_marker

typedef struct _IO_marker * H2D_Ptr_IO_marker;
#endif  /* _H2D_TYPE__H2D_Ptr_IO_marker */

#ifndef _H2D_TYPE__H2D_Ptr_IO_FILE
#define _H2D_TYPE__H2D_Ptr_IO_FILE

typedef struct _IO_FILE * H2D_Ptr_IO_FILE;
#endif  /* _H2D_TYPE__H2D_Ptr_IO_FILE */

#ifndef _H2D_TYPE__H2D_PtrPtrSChar
#define _H2D_TYPE__H2D_PtrPtrSChar

typedef signed char * * H2D_PtrPtrSChar;
#endif  /* _H2D_TYPE__H2D_PtrPtrSChar */

#ifndef _H2D_TYPE__H2D_OpenArrayPtrSChar
#define _H2D_TYPE__H2D_OpenArrayPtrSChar

typedef signed char * H2D_OpenArrayPtrSChar[];
#endif  /* _H2D_TYPE__H2D_OpenArrayPtrSChar */
#define H2D_Const_TRUE  TRUE
#define H2D_Const_FALSE  FALSE

#ifndef _H2D_TYPE__H2D_Ptrchtype
#define _H2D_TYPE__H2D_Ptrchtype

typedef chtype * H2D_Ptrchtype;
#endif  /* _H2D_TYPE__H2D_Ptrchtype */

#ifndef _H2D_TYPE__H2D_OpenArraychtype
#define _H2D_TYPE__H2D_OpenArraychtype

typedef chtype H2D_OpenArraychtype[];
#endif  /* _H2D_TYPE__H2D_OpenArraychtype */

#ifndef _H2D_TYPE__H2D_Ptrldat
#define _H2D_TYPE__H2D_Ptrldat

typedef struct ldat * H2D_Ptrldat;
#endif  /* _H2D_TYPE__H2D_Ptrldat */

#ifndef _H2D_TYPE__H2D_PtrWINDOW
#define _H2D_TYPE__H2D_PtrWINDOW

typedef WINDOW * H2D_PtrWINDOW;
#endif  /* _H2D_TYPE__H2D_PtrWINDOW */

#ifndef _H2D_TYPE__H2D_OpenArraySChar
#define _H2D_TYPE__H2D_OpenArraySChar

typedef signed char H2D_OpenArraySChar[];
#endif  /* _H2D_TYPE__H2D_OpenArraySChar */

#ifndef _H2D_TYPE__H2D_PtrSShInt
#define _H2D_TYPE__H2D_PtrSShInt

typedef signed short int * H2D_PtrSShInt;
#endif  /* _H2D_TYPE__H2D_PtrSShInt */

#ifndef _H2D_TYPE__H2D_PtrSCREEN
#define _H2D_TYPE__H2D_PtrSCREEN

typedef SCREEN * H2D_PtrSCREEN;
#endif  /* _H2D_TYPE__H2D_PtrSCREEN */

#ifndef _H2D_TYPE__H2D_PtrProc
#define _H2D_TYPE__H2D_PtrProc

typedef signed int( * H2D_PtrProc)( WINDOW *, signed int );
#endif  /* _H2D_TYPE__H2D_PtrProc */

#ifndef _H2D_TYPE__H2D_PtrProc0
#define _H2D_TYPE__H2D_PtrProc0

typedef signed int( * H2D_PtrProc0)( signed int );
#endif  /* _H2D_TYPE__H2D_PtrProc0 */

#ifndef _H2D_TYPE__H2D_PtrSInt
#define _H2D_TYPE__H2D_PtrSInt

typedef signed int * H2D_PtrSInt;
#endif  /* _H2D_TYPE__H2D_PtrSInt */

#ifndef _H2D_TYPE__H2D_PtrMEVENT
#define _H2D_TYPE__H2D_PtrMEVENT

typedef MEVENT * H2D_PtrMEVENT;
#endif  /* _H2D_TYPE__H2D_PtrMEVENT */

#endif  /* h2d_curses_H_ */