/* XDS v2.60: Copyright (c) 1999-2011 Excelsior, LLC. All Rights Reserved. */
/* Generated by XDS Modula-2 to ANSI C v4.20 translator */

#ifndef LocalHeap_H_
#define LocalHeap_H_
#ifndef X2C_H_
#include "X2C.h"
#endif

typedef void *LocalHeap_heapID;

extern void LocalHeap_Create(LocalHeap_heapID *);

extern void LocalHeap_Destroy(LocalHeap_heapID);

extern void LocalHeap_ALLOCATE(LocalHeap_heapID, X2C_ADDRESS *, X2C_INT32);

extern void LocalHeap_DEALLOCATE(LocalHeap_heapID, X2C_ADDRESS *, X2C_INT32);

extern void LocalHeap_DEALLOCATE_ALL(LocalHeap_heapID);


extern void LocalHeap_BEGIN(void);


#endif /* LocalHeap_H_ */
