/* XDS v2.60: Copyright (c) 1999-2011 Excelsior, LLC. All Rights Reserved. */
/* Generated by XDS Modula-2 to ANSI C v4.20 translator */

#ifndef LongMath_H_
#define LongMath_H_
#ifndef X2C_H_
#include "X2C.h"
#endif

#define LongMath_pi 3.1415926535898

#define LongMath_exp1 2.718281828459

extern X2C_LONGREAL LongMath_sqrt(X2C_LONGREAL);

extern X2C_LONGREAL LongMath_exp(X2C_LONGREAL);

extern X2C_LONGREAL LongMath_ln(X2C_LONGREAL);

extern X2C_LONGREAL LongMath_sin(X2C_LONGREAL);

extern X2C_LONGREAL LongMath_cos(X2C_LONGREAL);

extern X2C_LONGREAL LongMath_tan(X2C_LONGREAL);

extern X2C_LONGREAL LongMath_arcsin(X2C_LONGREAL);

extern X2C_LONGREAL LongMath_arccos(X2C_LONGREAL);

extern X2C_LONGREAL LongMath_arctan(X2C_LONGREAL);

extern X2C_LONGREAL LongMath_power(X2C_LONGREAL, X2C_LONGREAL);

extern X2C_INT32 LongMath_round(X2C_LONGREAL);

extern X2C_BOOLEAN LongMath_IsRMathException(void);


extern void LongMath_BEGIN(void);


#endif /* LongMath_H_ */
