/* XDS v2.60: Copyright (c) 1999-2011 Excelsior, LLC. All Rights Reserved. */
/* Generated by XDS Modula-2 to ANSI C v4.20 translator */

#ifndef MathLib0_H_
#define MathLib0_H_
#ifndef X2C_H_
#include "X2C.h"
#endif

extern X2C_REAL MathLib0_sqrt(X2C_REAL);

extern X2C_REAL MathLib0_exp(X2C_REAL);

extern X2C_REAL MathLib0_ln(X2C_REAL);

extern X2C_REAL MathLib0_sin(X2C_REAL);

extern X2C_REAL MathLib0_cos(X2C_REAL);

extern X2C_REAL MathLib0_arctan(X2C_REAL);

extern X2C_INT32 MathLib0_entier(X2C_REAL);


extern void MathLib0_BEGIN(void);


#endif /* MathLib0_H_ */
