/* XDS v2.60: Copyright (c) 1999-2011 Excelsior, LLC. All Rights Reserved. */
/* Generated by XDS Modula-2 to ANSI C v4.20 translator */

#ifndef SIOResult_H_
#define SIOResult_H_
#ifndef X2C_H_
#include "X2C.h"
#endif
#ifndef IOConsts_H_
#include "IOConsts.h"
#endif

typedef enum IOConsts_ReadResults SIOResult_ReadResults;

extern X2C_CARD8 SIOResult_ReadResult(void);


extern void SIOResult_BEGIN(void);


#endif /* SIOResult_H_ */
