/* XDS v2.60: Copyright (c) 1999-2011 Excelsior, LLC. All Rights Reserved. */
/* Generated by XDS Modula-2 to ANSI C v4.20 translator */

#ifndef XIOChan_H_
#define XIOChan_H_
#ifndef X2C_H_
#include "X2C.h"
#endif
#ifndef IOChan_H_
#include "IOChan.h"
#endif

typedef IOChan_ChanId XIOChan_ChanId;

extern void XIOChan_Truncate(IOChan_ChanId);


extern void XIOChan_BEGIN(void);


#endif /* XIOChan_H_ */
