/* XDS v2.60: Copyright (c) 1999-2011 Excelsior, LLC. All Rights Reserved. */
#ifndef xrcACMPLX_H_
#define xrcACMPLX_H_
#include "X2C.h"

extern int CPLX_CMP(X2C_COMPLEX, X2C_COMPLEX);

extern X2C_COMPLEX CPLX_ADD(X2C_COMPLEX, X2C_COMPLEX);

extern X2C_COMPLEX CPLX_SUB(X2C_COMPLEX, X2C_COMPLEX);

extern X2C_COMPLEX CPLX_MUL(X2C_COMPLEX, X2C_COMPLEX);

extern X2C_COMPLEX CPLX_DIV(X2C_COMPLEX, X2C_COMPLEX);

extern X2C_COMPLEX CPLX_NEG(X2C_COMPLEX);

extern int CPLX_LCMP(X2C_LONGCOMPLEX, X2C_LONGCOMPLEX);

extern X2C_LONGCOMPLEX CPLX_LADD(X2C_LONGCOMPLEX, X2C_LONGCOMPLEX);

extern X2C_LONGCOMPLEX CPLX_LSUB(X2C_LONGCOMPLEX, X2C_LONGCOMPLEX);

extern X2C_LONGCOMPLEX CPLX_LMUL(X2C_LONGCOMPLEX, X2C_LONGCOMPLEX);

extern X2C_LONGCOMPLEX CPLX_LDIV(X2C_LONGCOMPLEX, X2C_LONGCOMPLEX);

extern X2C_LONGCOMPLEX CPLX_LNEG(X2C_LONGCOMPLEX);

extern X2C_LONGCOMPLEX CPLX_L(X2C_COMPLEX);


#endif /* xrcACMPLX_H_ */
