/* XDS v2.60: Copyright (c) 1999-2011 Excelsior, LLC. All Rights Reserved. */
/* Generated by XDS Modula-2 to ANSI C v4.20 translator */

#ifndef xrDTree_H_
#define xrDTree_H_
#ifndef X2C_H_
#include "X2C.h"
#endif

#define xrDTree_dTreeLevel 11

#define xrDTree_lastLevelBase 2048

#define xrDTree_dTreeLen 4095UL

#define xrDTree_numOfLeaves 2048

#define xrDTree_ROOT_NOT_FOUND 0x0FFFFFFFF

extern X2C_CARD32 xrDTree_dTree[4096];

extern void xrDTree_ins(X2C_CARD32);

extern void xrDTree_del(X2C_CARD32);

extern X2C_CARD32 xrDTree_find(X2C_CARD32);

extern void xrDTree_init(void);

extern void xrDTree_weakIns(X2C_CARD32);

extern void xrDTree_weakDel(X2C_CARD32);

extern void xrDTree_recalc(void);


extern void xrDTree_BEGIN(void);


#endif /* xrDTree_H_ */
