/* XDS v2.60: Copyright (c) 1999-2011 Excelsior, LLC. All Rights Reserved. */
#ifndef xrLSETs_H_
#define xrLSETs_H_
#include "X2C.h"
#include "xmRTS.h"

extern LSET X2C_ROTL(LSET, LSET, X2C_INT16, X2C_INT32);

extern LSET X2C_LSHL(LSET, LSET, X2C_INT16, X2C_INT32);

extern LSET X2C_INCL(LSET, X2C_CARD32, X2C_CARD16);

extern LSET X2C_EXCL(LSET, X2C_CARD32, X2C_CARD16);

extern X2C_BOOLEAN X2C_SET_EQU(LSET, LSET, X2C_CARD16);

extern X2C_BOOLEAN X2C_SET_LEQ(LSET, LSET, X2C_CARD16);

extern LSET X2C_LONGSET(LSET, X2C_CARD32, X2C_CARD32, X2C_CARD16);

extern X2C_BOOLEAN X2C_INL(X2C_CARD32, X2C_CARD16, LSET);

extern LSET X2C_AND(LSET, LSET, LSET, X2C_CARD16);

extern LSET X2C_OR(LSET, LSET, LSET, X2C_CARD16);

extern LSET X2C_XOR(LSET, LSET, LSET, X2C_CARD16);

extern LSET X2C_BIC(LSET, LSET, LSET, X2C_CARD16);

extern LSET X2C_COMPLEMENT(LSET, LSET, X2C_CARD16);


#endif /* xrLSETs_H_ */
