/* XDS v2.60: Copyright (c) 1999-2011 Excelsior, LLC. All Rights Reserved. */
/* Generated by XDS Modula-2 to ANSI C v4.20 translator */

#ifndef xtsFIO_H_
#define xtsFIO_H_
#ifndef X2C_H_
#include "X2C.h"
#endif
#ifndef FIO_H_
#include "FIO.h"
#endif
#ifndef IOChan_H_
#include "IOChan.h"
#endif
#ifndef SysClock_H_
#include "SysClock.h"
#endif
#ifndef ChanConsts_H_
#include "ChanConsts.h"
#endif

struct xtsFIO_SpaceInfo;


struct xtsFIO_SpaceInfo {
   X2C_CARD32 clusterSize;
   X2C_CARD32 totalClusters;
   X2C_CARD32 freeClusters;
};

extern void xtsFIO_setShM(X2C_BOOLEAN, X2C_BOOLEAN);

extern void xtsFIO_restoreShM(void);

extern void xtsFIO_mk_chan(IOChan_ChanId, X2C_CARD32, X2C_CARD8,
                X2C_CARD8 *);

extern void xtsFIO_SetDrive(X2C_CARD32, X2C_CARD32 *);

extern X2C_CARD32 xtsFIO_GetDrive(void);

extern void xtsFIO_GetSpaceInfo(X2C_CARD32, struct xtsFIO_SpaceInfo *,
                X2C_CARD32 *);

extern void xtsFIO_GetLabel(X2C_CARD32, X2C_CHAR [], X2C_CARD32,
                X2C_CARD32 *);

extern void xtsFIO_ChgDir(X2C_CHAR [], X2C_CARD32, X2C_CARD32 *);

extern void xtsFIO_GetDir(X2C_CARD32, X2C_CHAR [], X2C_CARD32, X2C_CARD32 *);

extern void xtsFIO_CreateDir(X2C_CHAR [], X2C_CARD32, X2C_CARD32 *);

extern void xtsFIO_RmvDir(X2C_CHAR [], X2C_CARD32, X2C_CARD32 *);

extern void xtsFIO_ScanFirst(X2C_CHAR [], X2C_CARD32, X2C_CARD8,
                struct FIO_DirEntry *, X2C_CARD32 *);

extern void xtsFIO_ScanNext(struct FIO_DirEntry *, X2C_CARD32 *);

extern void xtsFIO_ScanClose(struct FIO_DirEntry *);

extern void xtsFIO_SetFileDate(IOChan_ChanId, struct SysClock_DateTime);

extern X2C_BOOLEAN xtsFIO_GetFileStamp(IOChan_ChanId,
                struct SysClock_DateTime *);


extern void xtsFIO_BEGIN(void);


#endif /* xtsFIO_H_ */
