/* XDS v2.60: Copyright (c) 1999-2011 Excelsior, LLC. All Rights Reserved. */
/* Generated by XDS Modula-2 to ANSI C v4.20 translator */

#ifndef xtsLib_H_
#define xtsLib_H_
#ifndef X2C_H_
#include "X2C.h"
#endif

typedef X2C_CHAR * xtsLib_ExecEnvPtr;

extern void xtsLib_Delay(X2C_CARD32);

extern void xtsLib_Speaker(X2C_CARD32, X2C_CARD32);

extern void xtsLib_Environment(X2C_CARD32, X2C_CHAR [], X2C_CARD32);


extern void xtsLib_BEGIN(void);


#endif /* xtsLib_H_ */
