#!/bin/sh
USER=`whoami`
if [ "$USER" != "root" ]; then
    echo "you must do this as root!"
    exit 1
fi

DSTMAP=/mnt/mmcblk0p2/dxlAPRS/aprsmap
DSTAPRS=/mnt/mmcblk0p2/dxlAPRS/aprs
SOURCE=http://web.oe5xbl.ampr.at/~aprsbuild
FILE=dxlAPRS_armv6-current


[ -d $DSTMAP ] || mkdir -p $DSTMAP
[ -d $DSTMAP/osm ] || mkdir -p $DSTMAP/osm
[ -d $DSTAPRS ] || mkdir -p $DSTAPRS

cd /tmp
[ -d dxlAPRS-update ] || mkdir dxlAPRS-update
cd dxlAPRS-update
[ -r $FILE.tgz ] && rm $FILE.tgz
wget $SOURCE/$FILE.tgz

if [ $? -eq 0 ] && [ -r $FILE.tgz ]; then
	gunzip $FILE.tgz
	tar -xf $FILE.tar
	rm $FILE.tar
	echo "stopping all aprs-executeables ..."
	killall afskmodem 2>/dev/null
	killall gps2aprs 2>/dev/null
	killall gps2digipos 2>/dev/null
	killall sondemod 2>/dev/null
	killall sondeudp 2>/dev/null
	killall udpflex 2>/dev/null
	killall udphub 2>/dev/null
	killall udprfnet 2>/dev/null
	killall udpgate4 2>/dev/null
	killall udpbox 2>/dev/null
	echo "installing aprsmap-components ..."
	mv -f aprsmap_common/* $DSTMAP/
	mv -f aprsmap $DSTMAP/
	rm -r aprsmap_common
	echo "installing aprs-components ..."
	cp -f -r dxlAPRS_common/* $DSTAPRS/
	rm -r dxlAPRS_common
	mv -f * $DSTAPRS/
	chown -R tc:staff $DSTAPRS

	chown root:staff $DSTAPRS/afskmodem
	olddir=`pwd`
	cd $DSTAPRS
	for f in $(\ls); do 
		test -x $f && chmod 0755 $f
	done
	chmod +s afskmodem
	cd $olddir
fi
