#!/bin/sh
USER=`whoami`
if [ "$USER" != "root" ]; then
    echo "you must do this as root!"
    exit 1
fi

DSTMAP=/home/dxlAPRS/aprsmap
DSTAPRS=/home/dxlAPRS/aprs
SOURCE=http://web.oe5xbl.ampr.at/~aprsbuild
FILE=dxlAPRS_armv7hf-current


[ -d $DSTMAP ] || mkdir -p $DSTMAP
[ -d $DSTMAP/osm ] || mkdir -p $DSTMAP/osm
[ -d $DSTAPRS ] || mkdir -p $DSTAPRS

cd /tmp
[ -d dxlAPRS-update ] || mkdir dxlAPRS-update
cd dxlAPRS-update
[ -r $FILE.tgz ] && rm $FILE.tgz
wget $SOURCE/$FILE.tgz

if [ $? -eq 0 ] && [ -r $FILE.tgz ]; then
	gunzip $FILE.tgz
	tar -xf $FILE.tar
	rm $FILE.tar
	echo "installing aprsmap-components ..."
	mv -f aprsmap_common/* $DSTMAP/
	mv -f aprsmap $DSTMAP/
	rm -r aprsmap_common
	echo "installing aprs-components ..."
	cp -r dxlAPRS_common/* $DSTAPRS/
	rm -r dxlAPRS_common
	mv -f * $DSTAPRS/
	chown -R aprs:staff $DSTAPRS
	
	chown root:staff $DSTAPRS/afskmodem
	olddir=`pwd`
	cd $DSTAPRS
	for f in $(\ls); do 
		test -x $f && chmod 0755 $f
	done
	chmod +s afskmodem
	cd $olddir
fi
