#!/bin/bash
SRC_TARBALL=../../fftw-3.3.10.tar.gz
BUILDDIR=`mktemp -d`
export CC=/opt/rpi-tools/arm-bcm2708/arm-bcm2708hardfp-linux-gnueabi/bin/arm-bcm2708hardfp-linux-gnueabi-gcc
export CFLAGS="-march=armv6zk -mfpu=vfp -mfloat-abi=hard -mcpu=arm1176jzf-s"

cp $SRC_TARBALL $BUILDDIR
pushd $BUILDDIR
tar -xf fftw-3.3.10.tar.gz
cd fftw-3.3.10
./configure --prefix=$BUILDDIR --host=arm-none-linux-gnueabi
make -j16
make install
popd
cp $BUILDDIR/lib/libfftw*.a .
cp $BUILDDIR/include/fftw3.h .
rm -r -f $BUILDDIR

