/* X11/ICE/ICE.h  Nov 12  20:52:3  1996 */
/* Generated by H2D v1.18.1 */
/* from module ICE and header X11/ICE/ICE.h. */
/* Types which were created during translation */

/* Copyright (c) 1996 XDS Ltd, Russia. All rights reserved. 
 *
 * $RCSfile: ICE.h,v $ $Revision: 1.3 $ $Date: 1998/02/15 00:04:18 $
 */

#include <X11/ICE/ICE.h>
