/* X11/Intrinsic.h  Oct 28  20:39:39  1996 */
/* Generated by H2D v1.17.7 */
/* from module Intrinsic and header X11/Intrinsic.h. */
/* Types which were created during translation */

/* Copyright (c) 1996 XDS Ltd, Russia. All rights reserved. 
 *
 * $RCSfile: Intrinsic.h,v $ $Revision: 1.4 $ $Date: 1998/07/28 15:58:28 $
 */
#include <X11/Intrinsic.h>

#ifndef Intrinsic_H_
#define Intrinsic_H_

typedef String			*StringList;
typedef Cardinal		*CardinalList;
typedef XtPointer		*XtPointerList;
typedef Dimension		*DimensionList;
typedef Position		*PositionList;
typedef XtWidgetGeometry	*XtWidgetGeometryPtr;

#endif  /* Intrinsic_H_ */
