/* X11/SM/SMlib.h  Nov 12  20:52:3  1996 */
/* Generated by H2D v1.18.1 */
/* from module SMlib and header X11/SM/SMlib.h. */
/* Types which were created during translation */

/* Copyright (c) 1996 XDS Ltd, Russia. All rights reserved. 
 *
 * $RCSfile: SMlib.h,v $ $Revision: 1.4 $ $Date: 1998/07/28 15:58:29 $
 */
#include <X11/SM/SMlib.h>
#include "X.h"

#ifndef SMlib_H_
#define SMlib_H_

typedef SmPropValue	*PASmPropValue;
typedef SmProp		*PASmProp;
typedef struct {
          SmcSaveYourselfProc callback;
          SmPointer client_data;
        } SaveYourselfStruct;
typedef struct {
          SmcDieProc callback;
          SmPointer client_data;
        } DieStruct;
typedef struct {
          SmcSaveCompleteProc callback;
          SmPointer client_data;
        } SaveCompleteStruct;
typedef struct {
          SmcShutdownCanceledProc callback;
          SmPointer client_data;
        } ShutdownCancelledStruct;
typedef struct {
          SmsRegisterClientProc callback;
          SmPointer manager_data;
        } RegisterClientStruct;
typedef struct {
          SmsInteractRequestProc callback;
          SmPointer manager_data;
        } InteractRequestStruct;
typedef struct {
          SmsSaveYourselfRequestProc callback;
          SmPointer manager_data;
        } SaveYourselfRequestStruct;
typedef struct {
          SmsSaveYourselfPhase2RequestProc callback;
          SmPointer manager_data;
        } SaveYourselfPhase2RequestStruct;
typedef struct {
          SmsSaveYourselfDoneProc callback;
          SmPointer manager_data;
        } SaveYourselfDoneStruct;
typedef struct {
          SmsCloseConnectionProc callback;
          SmPointer manager_data;
        } CloseConnectionStruct;
typedef struct {
          SmsSetPropertiesProc callback;
          SmPointer manager_data;
        } SetPropertiesStruct;
typedef struct {
          SmsDeletePropertiesProc callback;
          SmPointer manager_data;
        } DeletePropertiesStruct;
typedef struct {
          SmsGetPropertiesProc callback;
          SmPointer manager_data;
        } GetPropertiesStruct;
typedef SmsCallbacks	*PASmsCallbacks;

#endif  /* SMlib_H_ */
