/* Generated by XDS Modula-2 to ANSI C v4.20 translator */

#ifndef Lib_H_
#define Lib_H_
#ifndef X2C_H_
#include "X2C.h"
#endif

extern void Lib_Fill(X2C_ADDRESS, unsigned long, char);

extern void Lib_NextArg(char [], unsigned long);

extern double Lib_Random(void);

extern void Lib_BEGIN(int argc, char *argv[]);

#endif /* Lib_H_ */
