/* XDS v2.60: Copyright (c) 1999-2011 Excelsior, LLC. All Rights Reserved. */
/* Generated by XDS Modula-2 to ANSI C v4.20 translator */

#ifndef GeneralUserExceptions_H_
#define GeneralUserExceptions_H_
#ifndef X2C_H_
#include "X2C.h"
#endif

enum GeneralUserExceptions_GeneralE {GeneralUserExceptions_problem,
                GeneralUserExceptions_disaster};


extern void GeneralUserExceptions_RaiseGen(X2C_CARD8, X2C_CHAR [],
                X2C_CARD32);

extern X2C_BOOLEAN GeneralUserExceptions_IsGenera(void);

extern X2C_CARD8 GeneralUserExceptions_General0(void);


extern void GeneralUserExceptions_BEGIN(void);


#endif /* GeneralUserExceptions_H_ */
