/* XDS v2.60: Copyright (c) 1999-2011 Excelsior, LLC. All Rights Reserved. */
/* Generated by XDS Modula-2 to ANSI C v4.20 translator */

#ifndef LongStr_H_
#define LongStr_H_
#ifndef X2C_H_
#include "X2C.h"
#endif
#ifndef ConvTypes_H_
#include "ConvTypes.h"
#endif

typedef X2C_LONGREAL LongStr_float;

typedef enum ConvTypes_ConvResults LongStr_ConvResults;

extern void LongStr_StrToReal(X2C_CHAR [], X2C_CARD32, X2C_LONGREAL *,
                X2C_CARD8 *);

extern void LongStr_RealToFloat(X2C_LONGREAL, X2C_CARD32, X2C_CHAR [],
                X2C_CARD32);

extern void LongStr_RealToEng(X2C_LONGREAL, X2C_CARD32, X2C_CHAR [],
                X2C_CARD32);

extern void LongStr_RealToFixed(X2C_LONGREAL, X2C_INT32, X2C_CHAR [],
                X2C_CARD32);

extern void LongStr_RealToStr(X2C_LONGREAL, X2C_CHAR [], X2C_CARD32);


extern void LongStr_BEGIN(void);


#endif /* LongStr_H_ */
