/* XDS v2.60: Copyright (c) 1999-2011 Excelsior, LLC. All Rights Reserved. */
/* Generated by XDS Modula-2 to ANSI C v4.20 translator */

#ifndef LongIO_H_
#define LongIO_H_
#ifndef X2C_H_
#include "X2C.h"
#endif
#ifndef IOChan_H_
#include "IOChan.h"
#endif

extern void LongIO_ReadReal(IOChan_ChanId, X2C_LONGREAL *);

extern void LongIO_WriteFloat(IOChan_ChanId, X2C_LONGREAL, X2C_CARD32,
                X2C_CARD32);

extern void LongIO_WriteEng(IOChan_ChanId, X2C_LONGREAL, X2C_CARD32,
                X2C_CARD32);

extern void LongIO_WriteFixed(IOChan_ChanId, X2C_LONGREAL, X2C_INT32,
                X2C_CARD32);

extern void LongIO_WriteReal(IOChan_ChanId, X2C_LONGREAL, X2C_CARD32);


extern void LongIO_BEGIN(void);


#endif /* LongIO_H_ */
