/* XDS v2.60: Copyright (c) 1999-2011 Excelsior, LLC. All Rights Reserved. */
/* Generated by XDS Modula-2 to ANSI C v4.20 translator */

#ifndef RealInOut_H_
#define RealInOut_H_
#ifndef X2C_H_
#include "X2C.h"
#endif

extern X2C_BOOLEAN RealInOut_Done;

extern void RealInOut_ReadReal(X2C_REAL *);

extern void RealInOut_WriteReal(X2C_REAL, X2C_CARD32);


extern void RealInOut_BEGIN(void);


#endif /* RealInOut_H_ */
