/* XDS v2.60: Copyright (c) 1999-2011 Excelsior, LLC. All Rights Reserved. */
/* Generated by XDS Modula-2 to ANSI C v4.20 translator */

#ifndef SRealIO_H_
#define SRealIO_H_
#ifndef X2C_H_
#include "X2C.h"
#endif

extern void SRealIO_ReadReal(X2C_REAL *);

extern void SRealIO_WriteFloat(X2C_REAL, X2C_CARD32, X2C_CARD32);

extern void SRealIO_WriteEng(X2C_REAL, X2C_CARD32, X2C_CARD32);

extern void SRealIO_WriteFixed(X2C_REAL, X2C_INT32, X2C_CARD32);

extern void SRealIO_WriteReal(X2C_REAL, X2C_CARD32);


extern void SRealIO_BEGIN(void);


#endif /* SRealIO_H_ */
