/* XDS v2.60: Copyright (c) 1999-2011 Excelsior, LLC. All Rights Reserved. */
/* Generated by XDS Modula-2 to ANSI C v4.20 translator */

#ifndef TextIO_H_
#define TextIO_H_
#ifndef X2C_H_
#include "X2C.h"
#endif
#ifndef IOChan_H_
#include "IOChan.h"
#endif

extern void TextIO_ReadChar(IOChan_ChanId, X2C_CHAR *);

extern void TextIO_ReadRestLine(IOChan_ChanId, X2C_CHAR [], X2C_CARD32);

extern void TextIO_ReadString(IOChan_ChanId, X2C_CHAR [], X2C_CARD32);

extern void TextIO_ReadToken(IOChan_ChanId, X2C_CHAR [], X2C_CARD32);

extern void TextIO_SkipLine(IOChan_ChanId);

extern void TextIO_WriteChar(IOChan_ChanId, X2C_CHAR);

extern void TextIO_WriteLn(IOChan_ChanId);

extern void TextIO_WriteString(IOChan_ChanId, X2C_CHAR [], X2C_CARD32);


extern void TextIO_BEGIN(void);


#endif /* TextIO_H_ */
