/* XDS v2.60: Copyright (c) 1999-2011 Excelsior, LLC. All Rights Reserved. */
/* Generated by XDS Modula-2 to ANSI C v4.20 translator */

#ifndef XEXCEPTIONS_H_
#define XEXCEPTIONS_H_
#ifndef X2C_H_
#include "X2C.h"
#endif

enum XEXCEPTIONS_RTSExceptions {XEXCEPTIONS_typeGuardException,
                XEXCEPTIONS_noMemoryException, XEXCEPTIONS_typeCastException,
                 
   XEXCEPTIONS_userBreakException, XEXCEPTIONS_unreachableDLLExce,
                XEXCEPTIONS_internalRTSExcepti};


extern X2C_CARD8 XEXCEPTIONS_RTSException(void);

extern X2C_BOOLEAN XEXCEPTIONS_IsRTSException(void);

extern X2C_BOOLEAN XEXCEPTIONS_IsAssertException(void);

extern X2C_CARD32 XEXCEPTIONS_AssertCode(void);


extern void XEXCEPTIONS_BEGIN(void);


#endif /* XEXCEPTIONS_H_ */
