/* XDS v2.60: Copyright (c) 1999-2011 Excelsior, LLC. All Rights Reserved. */
/* Generated by XDS Modula-2 to ANSI C v4.20 translator */

#ifndef xFilePos_H_
#define xFilePos_H_
#ifndef X2C_H_
#include "X2C.h"
#endif
#ifndef RndFile_H_
#include "RndFile.h"
#endif

typedef RndFile_FilePos xFilePos_FilePos;

extern void xFilePos_CardToPos(RndFile_FilePos, X2C_CARD32);

extern void xFilePos_IntToPos(RndFile_FilePos, X2C_INT32);

extern X2C_BOOLEAN xFilePos_PosToInt(X2C_INT32 *, RndFile_FilePos);

extern X2C_BOOLEAN xFilePos_PosToCard(X2C_CARD32 *, RndFile_FilePos);


extern void xFilePos_BEGIN(void);


#endif /* xFilePos_H_ */
