/* XDS v2.60: Copyright (c) 1999-2011 Excelsior, LLC. All Rights Reserved. */
/* Generated by XDS Modula-2 to ANSI C v4.20 translator */

#ifndef xrHistory_H_
#define xrHistory_H_
#ifndef X2C_H_
#include "X2C.h"
#endif

extern void X2C_scanStackHistory(X2C_ADDRESS, X2C_ADDRESS, X2C_BOOLEAN);

extern void X2C_show_history(void);

extern void X2C_INIT_HISTORY(void);

extern void X2C_show_profile(void);

extern void X2C_HIS_SAVE(X2C_INT16 *);

extern void X2C_HIS_RESTORE(X2C_INT16);

extern void X2C_Profiler_clock(void);

extern void X2C_PROC_INP_F(X2C_CHAR [], X2C_INT32);

extern void X2C_PROC_PRF_F(X2C_CHAR [], X2C_INT32);

extern void X2C_PROC_OUT_F(void);


extern void xrHistory_BEGIN(void);


#endif /* xrHistory_H_ */
